-- AlterTable
ALTER TABLE `Server` ADD COLUMN `backendBaseUrl` VARCHAR(191) NULL,
    ADD COLUMN `browserBaseUrl` VARCHAR(191) NULL,
    ADD COLUMN `defaultCfg` DOUBLE NULL,
    ADD COLUMN `defaultHeight` INTEGER NOT NULL DEFAULT 512,
    ADD COLUMN `defaultSampler` VARCHAR(191) NULL,
    ADD COLUMN `defaultScheduler` VARCHAR(191) NULL,
    ADD COLUMN `defaultSteps` INTEGER NULL,
    ADD COLUMN `defaultTransport` ENUM('BROWSER', 'BACKEND') NOT NULL DEFAULT 'BROWSER',
    ADD COLUMN `defaultWidth` INTEGER NOT NULL DEFAULT 512,
    ADD COLUMN `generationEngine` ENUM('A1111', 'COMFY', 'FLUX', 'KONTEXT', 'OPENAI_IMAGE', 'OTHER') NOT NULL DEFAULT 'A1111',
    ADD COLUMN `supportsBatch` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `supportsFlux` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `supportsImageEdit` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `supportsInpaint` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `supportsKontext` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `supportsOutpaint` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `supportsWorkflowUpload` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `workflowJson` JSON NULL,
    ADD COLUMN `workflowPath` VARCHAR(191) NULL,
    ADD COLUMN `workflowVersion` VARCHAR(191) NULL;
