// /server/chatgpt/registry/currentModels.ts
import { createError } from 'h3'
import type { ChatGptResource } from '../schemas/operationSchemas'

export type CurrentModelConfig = {
  prisma: string
  ownerField?: string
  activeField?: string
  publicField?: string
  searchableFields?: string[]
  filterFields?: string[]
  defaultOrderBy?: {
    field: string
    direction: 'asc' | 'desc'
  }
  hiddenFields?: string[]
  listHiddenFields?: string[]
  adminOnly?: boolean
}

export const CURRENT_MODEL_REGISTRY = {
  artImage: {
    prisma: 'artImage',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'fileName',
      'promptString',
      'negativePrompt',
      'checkpoint',
      'sampler',
      'designer',
      'genres',
      'serverName',
      'artPrompt',
    ],
    filterFields: [
      'checkpointResourceId',
      'designer',
      'fileType',
      'serverId',
      'serverName',
    ],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
    hiddenFields: ['imageData', 'thumbnailData', 'heroData', 'cardData', 'iconData'],
    listHiddenFields: [
      'imageData',
      'thumbnailData',
      'heroData',
      'cardData',
      'iconData',
    ],
  },
  artCollection: {
    prisma: 'artCollection',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'label',
      'slug',
      'parentFolder',
      'description',
      'username',
      'artPrompt',
    ],
    filterFields: ['label', 'slug', 'parentFolder', 'username'],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
  },
  bot: {
    prisma: 'bot',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'BotType',
      'name',
      'slug',
      'subtitle',
      'description',
      'botIntro',
      'userIntro',
      'narrativeVoice',
      'forgeIntro',
      'prompt',
      'theme',
      'personality',
      'modules',
      'sampleResponse',
      'tagline',
      'designer',
      'serverName',
      'artPrompt',
    ],
    filterFields: [
      'BotType',
      'designer',
      'serverId',
      'serverName',
      'underConstruction',
    ],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
  },
  character: {
    prisma: 'character',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'name',
      'slug',
      'honorific',
      'species',
      'class',
      'genre',
      'personality',
      'backstory',
      'drive',
      'quirks',
      'artPrompt',
      'designer',
    ],
    filterFields: [
      'species',
      'class',
      'genre',
      'designer',
      'level',
      'artImageId',
    ],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
  },
  chat: {
    prisma: 'chat',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'sender',
      'recipient',
      'content',
      'title',
      'botName',
      'channel',
      'botResponse',
      'serverName',
    ],
    filterFields: [
      'type',
      'sender',
      'recipient',
      'isFavorite',
      'isRead',
      'originId',
      'previousEntryId',
      'botId',
      'recipientId',
      'artImageId',
      'promptId',
      'characterId',
      'dreamId',
      'projectId',
      'serverId',
      'channel',
    ],
    defaultOrderBy: {
      field: 'createdAt',
      direction: 'desc',
    },
  },
  composition: {
    prisma: 'composition',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'title',
      'description',
      'label',
      'mode',
      'designer',
      'characterBlurb',
      'dreamBlurb',
      'scenarioBlurb',
      'rewardBlurb',
      'narrativeText',
      'artPrompt',
      'imagePath',
      'wishText',
    ],
    filterFields: [
      'mode',
      'status',
      'designer',
      'characterId',
      'dreamId',
      'scenarioId',
      'rewardId',
      'artImageId',
      'outputDreamId',
      'userApproved',
      'bountyId',
    ],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
  },
  dream: {
    prisma: 'dream',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'title',
      'slug',
      'description',
      'pitch',
      'flavorText',
      'examples',
      'artPrompt',
      'imagePath',
      'cardPath',
      'heroPath',
      'highlightImage',
      'icon',
      'designer',
    ],
    filterFields: [
      'slug',
      'dreamType',
      'creationSource',
      'designer',
      'artImageId',
      'artCollectionId',
      'narratorId',
      'allowReviews',
    ],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
  },
  facet: {
    prisma: 'facet',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'title',
      'slug',
      'description',
      'flavorText',
      'examples',
      'artPrompt',
      'imagePath',
      'cardPath',
      'heroPath',
      'icon',
      'designer',
    ],
    filterFields: [
      'slug',
      'kind',
      'creationSource',
      'designer',
      'artImageId',
      'artCollectionId',
    ],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
  },
  project: {
    prisma: 'project',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'title',
      'slug',
      'description',
      'pitch',
      'flavorText',
      'goal',
      'waypoints',
      'conductorSlug',
      'repoUrl',
      'liveUrl',
      'channelKey',
      'tabKey',
      'highlightImage',
      'icon',
      'imagePath',
      'cardPath',
      'heroPath',
      'designer',
    ],
    filterFields: [
      'slug',
      'status',
      'priority',
      'conductorSlug',
      'channelKey',
      'tabKey',
      'managerBotId',
      'artImageId',
      'artCollectionId',
      'allowReviews',
      'creationSource',
    ],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
  },
  prompt: {
    prisma: 'prompt',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: ['prompt', 'artPrompt', 'imagePath', 'batchId', 'errorMessage'],
    filterFields: [
      'creationSource',
      'botId',
      'artImageId',
      'serverId',
      'artStatus',
      'batchId',
      'isBounty',
      'bountyStatus',
      'claimerId',
    ],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
  },
  resource: {
    prisma: 'resource',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'name',
      'slug',
      'customLabel',
      'MediaPath',
      'customUrl',
      'civitaiUrl',
      'huggingUrl',
      'localPath',
      'description',
      'imagePath',
      'generation',
      'artPrompt',
    ],
    filterFields: ['slug', 'resourceType', 'supportedServer', 'artImageId'],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
  },
  reward: {
    prisma: 'reward',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'name',
      'slug',
      'description',
      'flavorText',
      'effect',
      'icon',
      'collection',
      'imagePath',
      'artPrompt',
    ],
    filterFields: ['collection', 'rarity', 'rewardType', 'slug', 'artImageId'],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
  },
  scenario: {
    prisma: 'scenario',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'title',
      'slug',
      'description',
      'intros',
      'imagePath',
      'locations',
      'artPrompt',
      'genres',
      'inspirations',
      'tier',
      'group',
      'secretNotes',
    ],
    filterFields: [
      'slug',
      'artImageId',
      'genres',
      'difficulty',
      'tier',
      'group',
      'outputType',
    ],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
  },
  server: {
    prisma: 'server',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: [
      'title',
      'label',
      'description',
      'category',
      'baseUrl',
      'endpointPath',
      'healthPath',
      'apiLink',
      'model',
      'designer',
      'version',
      'notes',
      'artPrompt',
    ],
    filterFields: [
      'serverType',
      'category',
      'isOfficial',
      'isDefault',
      'isEditable',
      'accessMode',
      'authType',
      'lastStatus',
    ],
    defaultOrderBy: {
      field: 'sortOrder',
      direction: 'asc',
    },
    hiddenFields: ['apiKey'],
    listHiddenFields: ['apiKey'],
    adminOnly: true,
  },
  theme: {
    prisma: 'theme',
    ownerField: 'userId',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: ['name', 'values', 'tagline', 'room', 'colorScheme', 'artPrompt'],
    filterFields: ['name', 'colorScheme', 'prefersDark'],
    defaultOrderBy: {
      field: 'createdAt',
      direction: 'desc',
    },
  },
  user: {
    prisma: 'user',
    ownerField: 'id',
    activeField: 'isActive',
    publicField: 'isPublic',
    searchableFields: ['username', 'name', 'bio', 'languages', 'timezone', 'designerName'],
    filterFields: [
      'username',
      'showMature',
      'Role',
      'customIcons',
      'isMember',
      'isGuest',
      'preferredArtServerId',
      'preferredTextServerId',
    ],
    defaultOrderBy: {
      field: 'updatedAt',
      direction: 'desc',
    },
    hiddenFields: [
      'address1',
      'address2',
      'apiKey',
      'birthday',
      'blockList',
      'city',
      'country',
      'email',
      'googleEmail',
      'googleId',
      'password',
      'phone',
      'referralCode',
      'state',
      'stripeCustomerId',
      'token',
    ],
    listHiddenFields: [
      'address1',
      'address2',
      'apiKey',
      'birthday',
      'blockList',
      'city',
      'country',
      'email',
      'googleEmail',
      'googleId',
      'password',
      'phone',
      'referralCode',
      'state',
      'stripeCustomerId',
      'token',
    ],
    adminOnly: true,
  },
} satisfies Partial<Record<ChatGptResource, CurrentModelConfig>>

export function getCurrentModelConfig(resource: ChatGptResource): CurrentModelConfig {
  const config = CURRENT_MODEL_REGISTRY[resource]

  if (!config) {
    throw createError({
      statusCode: 400,
      statusMessage: `Resource not implemented: ${resource}`,
    })
  }

  return config
}
