// /server/chatgpt/registry/models.ts
import { createError } from 'h3'
import { z } from 'zod'
import type { ChatGptResource } from '../schemas/operationSchemas'

const OptionalStringSchema = z.string().trim().min(1).optional()
const OptionalTextSchema = z.string().trim().min(1).optional()
const OptionalNullableStringSchema = z
  .string()
  .trim()
  .min(1)
  .nullable()
  .optional()
const OptionalBooleanSchema = z.boolean().optional()
const OptionalPositiveIntSchema = z.number().int().positive().optional()
const OptionalIntSchema = z.number().int().optional()

const BaseFlagsSchema = z
  .object({
    isPublic: OptionalBooleanSchema,
    isMature: OptionalBooleanSchema,
    isActive: OptionalBooleanSchema,
  })
  .strict()

const PublicActiveFlagsSchema = z
  .object({
    isPublic: OptionalBooleanSchema,
    isActive: OptionalBooleanSchema,
  })
  .strict()

const PitchTypeSchema = z.enum([
  'ARTPITCH',
  'BRAINSTORM',
  'WEIRDLANDIA',
  'RANDOMLIST',
  'TITLE',
  'VIBE',
  'BOT',
  'ARTGALLERY',
  'INSPIRATION',
  'DREAM',
])

const CreationSourceSchema = z.enum([
  'HUMAN',
  'AI',
  'HYBRID',
  'UPLOAD',
  'UNKNOWN',
])

const ChatTypeSchema = z.enum([
  'ToBot',
  'BotResponse',
  'ToForum',
  'ToUser',
  'ToCharacter',
  'Weirdlandia',
  'Dream',
  'Reward',
  'Story',
  'Scenario',
  'Character',
  'Bot',
])

const DreamAccessModeSchema = z.enum(['OPEN', 'CODE', 'PRIVATE', 'SOLO'])

const ResourceTypeSchema = z.enum([
  'CHECKPOINT',
  'EMBEDDING',
  'LORA',
  'LYCORIS',
  'HYPERNETWORK',
  'SAMPLER',
  'CONTROLNET',
  'URL',
  'API',
])

const SupportedServerSchema = z.enum([
  'SD15',
  'SDXL',
  'COMFY',
  'FLUX',
  'KONTEXT',
  'GENERIC',
  'UNKNOWN',
  'OPENAI',
])

const ServerTypeSchema = z.enum([
  'A1111',
  'COMFY',
  'OPENAI',
  'ANTHROPIC',
  'CUSTOM',
])

const ServerStatusSchema = z.enum(['ONLINE', 'OFFLINE', 'DEGRADED', 'UNKNOWN'])

const ServerAccessModeSchema = z
  .enum([
    'LOCAL',
    'TAILSCALE',
    'BROWSER',
    'BACKEND',
    'PUBLIC',
    'PRIVATE',
    'PUBLIC_PROTECTED',
    'PUBLIC_API_KEY',
    'PUBLIC_OIDC',
    'PUBLIC_UNPROTECTED',
  ])
  .or(z.string().trim().min(1))

const ServerAuthTypeSchema = z
  .enum(['NONE', 'BEARER', 'HEADER', 'API_KEY', 'CUSTOM'])
  .or(z.string().trim().min(1))

const RoleSchema = z.enum([
  'SYSTEM',
  'USER',
  'ASSISTANT',
  'ADMIN',
  'GUEST',
  'BOT',
  'DESIGNER',
  'CHILD',
])

export const ArtImageCreateSchema = BaseFlagsSchema.extend({
  imageData: z.string().trim().min(1).optional(),
  thumbnailData: OptionalTextSchema,
  fileName: OptionalStringSchema,
  fileType: OptionalStringSchema,
  imagePath: OptionalTextSchema,
  rarity: OptionalIntSchema,
  path: OptionalStringSchema,
  promptString: OptionalTextSchema,
  negativePrompt: OptionalTextSchema,
  checkpoint: OptionalStringSchema,
  checkpointResourceId: OptionalPositiveIntSchema,
  sampler: OptionalStringSchema,
  seed: OptionalIntSchema,
  steps: OptionalIntSchema,
  cfg: OptionalIntSchema,
  cfgHalf: OptionalBooleanSchema,
  designer: OptionalStringSchema,
  genres: OptionalTextSchema,
  serverId: OptionalPositiveIntSchema,
  serverName: OptionalStringSchema,
  serverUrl: OptionalStringSchema,
  artPrompt: OptionalTextSchema,
  artId: OptionalPositiveIntSchema,
  botId: OptionalPositiveIntSchema,
  componentId: OptionalPositiveIntSchema,
  milestoneId: OptionalPositiveIntSchema,
  pitchId: OptionalPositiveIntSchema,
  promptId: OptionalPositiveIntSchema,
  resourceId: OptionalPositiveIntSchema,
  rewardId: OptionalPositiveIntSchema,
  chatId: OptionalPositiveIntSchema,
  characterId: OptionalPositiveIntSchema,
  butterflyId: OptionalPositiveIntSchema,
}).strict()

export const ArtImageUpdateSchema = ArtImageCreateSchema.partial().strict()

export const ArtCollectionCreateSchema = BaseFlagsSchema.extend({
  label: OptionalStringSchema,
  description: OptionalTextSchema,
  username: OptionalStringSchema,
}).strict()

export const ArtCollectionUpdateSchema =
  ArtCollectionCreateSchema.partial().strict()

export const BotCreateSchema = BaseFlagsSchema.extend({
  BotType: z.string().trim().min(1).max(764),
  name: z.string().trim().min(1).max(256),
  subtitle: OptionalStringSchema,
  description: OptionalStringSchema,
  avatarImage: OptionalStringSchema,
  botIntro: z.string().trim().min(1).max(3000),
  userIntro: z.string().trim().min(1).max(764),
  prompt: z.string().trim().min(1).max(764),
  trainingPath: OptionalStringSchema,
  theme: OptionalStringSchema,
  personality: OptionalStringSchema,
  modules: OptionalStringSchema,
  sampleResponse: OptionalStringSchema,
  tagline: OptionalStringSchema,
  underConstruction: OptionalBooleanSchema,
  canDelete: OptionalBooleanSchema,
  designer: OptionalStringSchema,
  serverId: OptionalPositiveIntSchema,
  serverName: OptionalStringSchema,
  artImageId: OptionalPositiveIntSchema,
}).strict()

export const BotUpdateSchema = BotCreateSchema.partial().strict()

export const CharacterCreateSchema = BaseFlagsSchema.extend({
  name: z.string().trim().min(1).max(256),
  achievements: OptionalStringSchema,
  alignment: OptionalStringSchema,
  experience: OptionalIntSchema,
  level: OptionalIntSchema,
  class: OptionalStringSchema,
  species: OptionalStringSchema,
  backstory: OptionalTextSchema,
  drive: OptionalStringSchema,
  inventory: OptionalTextSchema,
  statName1: OptionalStringSchema,
  statValue1: OptionalIntSchema,
  statName2: OptionalStringSchema,
  statValue2: OptionalIntSchema,
  statName3: OptionalStringSchema,
  statValue3: OptionalIntSchema,
  statName4: OptionalStringSchema,
  statValue4: OptionalIntSchema,
  statName5: OptionalStringSchema,
  statValue5: OptionalIntSchema,
  statName6: OptionalStringSchema,
  statValue6: OptionalIntSchema,
  quirks: OptionalTextSchema,
  skills: OptionalTextSchema,
  genre: OptionalStringSchema,
  artImageId: OptionalPositiveIntSchema,
  artPrompt: OptionalTextSchema,
  goalStat1Name: OptionalStringSchema,
  goalStat1Value: OptionalIntSchema,
  goalStat2Name: OptionalStringSchema,
  goalStat2Value: OptionalIntSchema,
  goalStat3Name: OptionalStringSchema,
  goalStat3Value: OptionalIntSchema,
  goalStat4Name: OptionalStringSchema,
  goalStat4Value: OptionalIntSchema,
  honorific: OptionalStringSchema,
  imagePath: OptionalStringSchema,
  designer: OptionalStringSchema,
  personality: OptionalStringSchema,
}).strict()

export const CharacterUpdateSchema = CharacterCreateSchema.partial().strict()

export const ChatCreateSchema = BaseFlagsSchema.extend({
  type: ChatTypeSchema,
  sender: z.string().trim().min(1).max(255),
  recipient: OptionalStringSchema,
  content: z.string().trim().min(1),
  title: OptionalStringSchema,
  isFavorite: OptionalBooleanSchema,
  previousEntryId: OptionalPositiveIntSchema,
  originId: OptionalPositiveIntSchema,
  botId: OptionalPositiveIntSchema,
  recipientId: OptionalPositiveIntSchema,
  artImageId: OptionalPositiveIntSchema,
  promptId: OptionalPositiveIntSchema,
  botName: OptionalStringSchema,
  channel: OptionalStringSchema,
  botResponse: OptionalTextSchema,
  characterId: OptionalPositiveIntSchema,
  isRead: OptionalBooleanSchema,
  readAt: z.coerce.date().nullable().optional(),
  dreamId: OptionalPositiveIntSchema,
  serverId: OptionalPositiveIntSchema,
  serverName: OptionalStringSchema,
}).strict()

export const ChatUpdateSchema = ChatCreateSchema.partial().strict()

export const DreamCreateSchema = BaseFlagsSchema.extend({
  title: z.string().trim().min(1).max(255),
  slug: OptionalStringSchema,
  description: OptionalTextSchema,
  currentVibe: OptionalTextSchema,
  currentPrompt: OptionalTextSchema,
  pitchId: OptionalPositiveIntSchema,
  artId: OptionalPositiveIntSchema,
  artImageId: OptionalPositiveIntSchema,
  textServerId: OptionalPositiveIntSchema,
  artServerId: OptionalPositiveIntSchema,
  artCollectionId: OptionalPositiveIntSchema,
  scenarioId: OptionalPositiveIntSchema,
  accessMode: DreamAccessModeSchema.optional(),
  privacyCode: OptionalStringSchema,
}).strict()

export const DreamUpdateSchema = DreamCreateSchema.partial().strict()

export const PitchCreateSchema = BaseFlagsSchema.extend({
  title: OptionalStringSchema,
  pitch: z.string().trim().min(1).max(764),
  designer: OptionalStringSchema,
  flavorText: OptionalStringSchema,
  highlightImage: OptionalStringSchema,
  PitchType: PitchTypeSchema.optional(),
  creationSource: CreationSourceSchema.optional(),
  artPrompt: OptionalStringSchema,
  description: OptionalStringSchema,
  artImageId: OptionalPositiveIntSchema,
  examples: OptionalTextSchema,
  icon: OptionalStringSchema,
}).strict()

export const PitchUpdateSchema = PitchCreateSchema.partial().strict()

export const PromptCreateSchema = BaseFlagsSchema.extend({
  prompt: z.string().trim().min(1),
  creationSource: CreationSourceSchema.optional(),
  pitchId: OptionalPositiveIntSchema,
  botId: OptionalPositiveIntSchema,
  artImageId: OptionalPositiveIntSchema,
}).strict()

export const PromptUpdateSchema = PromptCreateSchema.partial().strict()

export const ResourceCreateSchema = BaseFlagsSchema.extend({
  name: z.string().trim().min(1).max(764),
  customLabel: OptionalStringSchema,
  MediaPath: OptionalStringSchema,
  customUrl: OptionalStringSchema,
  civitaiUrl: OptionalStringSchema,
  huggingUrl: OptionalStringSchema,
  localPath: OptionalStringSchema,
  description: OptionalTextSchema,
  resourceType: ResourceTypeSchema.optional(),
  supportedServer: SupportedServerSchema.optional(),
  artImageId: OptionalPositiveIntSchema,
  generation: OptionalTextSchema,
}).strict()

export const ResourceUpdateSchema = ResourceCreateSchema.partial().strict()

const RaritySchema = z.union([
  z.enum(['COMMON', 'UNCOMMON', 'RARE', 'EPIC', 'LEGENDARY', 'MYTHIC']),
  z.coerce.number().int().min(1).max(6),
])

const RewardTypeSchema = z.enum([
  'SKILL',
  'ITEM',
  'TREASURE',
  'TITLE',
  'POWER',
  'STORY',
])

export const RewardCreateSchema = BaseFlagsSchema.extend({
  icon: z.string().trim().min(1).max(256),
  text: z.string().trim().min(1).max(764),
  power: z.string().trim().min(1).max(764),
  collection: z.string().trim().min(1).max(764),
  rarity: RaritySchema.optional(),
  rewardType: RewardTypeSchema.optional(),
  label: OptionalStringSchema,
  artImageId: OptionalPositiveIntSchema,
  imagePath: OptionalTextSchema,
  artPrompt: OptionalTextSchema,
}).strict()

export const RewardUpdateSchema = RewardCreateSchema.partial().strict()

export const ScenarioCreateSchema = BaseFlagsSchema.extend({
  title: z.string().trim().min(1),
  description: z.string().trim().min(1),
  intros: z.string().trim().min(1),
  artImageId: OptionalPositiveIntSchema,
  imagePath: OptionalTextSchema,
  locations: OptionalTextSchema,
  artPrompt: OptionalTextSchema,
  genres: OptionalTextSchema,
  inspirations: OptionalTextSchema,
}).strict()

export const ScenarioUpdateSchema = ScenarioCreateSchema.partial().strict()

export const ServerCreateSchema = BaseFlagsSchema.extend({
  title: z.string().trim().min(1),
  label: OptionalStringSchema,
  description: OptionalTextSchema,
  serverType: ServerTypeSchema.optional(),
  category: OptionalStringSchema,
  baseUrl: OptionalStringSchema,
  endpointPath: OptionalStringSchema,
  healthPath: OptionalStringSchema,
  isOfficial: OptionalBooleanSchema,
  isDefault: OptionalBooleanSchema,
  isEditable: OptionalBooleanSchema,
  accessMode: ServerAccessModeSchema.optional(),
  authType: ServerAuthTypeSchema.optional(),
  apiKeyName: OptionalStringSchema,
  apiKey: OptionalTextSchema,
  useOidc: OptionalBooleanSchema,
  oidcProvider: OptionalStringSchema,
  apiLink: OptionalStringSchema,
  model: OptionalStringSchema,
  designer: OptionalStringSchema,
  version: OptionalStringSchema,
  notes: OptionalTextSchema,
  sortOrder: OptionalIntSchema,
  lastCheckedAt: z.coerce.date().nullable().optional(),
  lastStatus: ServerStatusSchema.optional(),
  artPrompt: OptionalTextSchema,
}).strict()

export const ServerUpdateSchema = ServerCreateSchema.partial().strict()

export const TagCreateSchema = BaseFlagsSchema.extend({
  label: z.string().trim().min(1).max(256),
  title: z.string().trim().min(1).max(256),
  flavorText: OptionalStringSchema,
  pitch: OptionalStringSchema,
  artImageId: OptionalPositiveIntSchema,
}).strict()

export const TagUpdateSchema = TagCreateSchema.partial().strict()

export const ThemeCreateSchema = PublicActiveFlagsSchema.extend({
  name: z.string().trim().min(1),
  values: z.string().trim().min(1),
  tagline: OptionalTextSchema,
  room: OptionalTextSchema,
  colorScheme: z.string().trim().min(1).optional(),
  prefersDark: OptionalBooleanSchema,
}).strict()

export const ThemeUpdateSchema = ThemeCreateSchema.partial().strict()

export const UserCreateSchema = PublicActiveFlagsSchema.extend({
  username: z.string().trim().min(1).max(255),
  email: z.string().trim().email().optional(),
  questPoints: OptionalIntSchema,
  emailVerified: z.coerce.date().optional(),
  name: OptionalStringSchema,
  avatarImage: OptionalTextSchema,
  bio: OptionalTextSchema,
  languages: OptionalTextSchema,
  timezone: OptionalStringSchema,
  apiKey: OptionalTextSchema,
  karma: OptionalIntSchema,
  mana: OptionalIntSchema,
  clickRecord: OptionalIntSchema,
  matchRecord: OptionalIntSchema,
  showMature: OptionalBooleanSchema,
  Role: RoleSchema.optional(),
  artImageId: OptionalPositiveIntSchema,
  token: OptionalTextSchema,
  designerName: OptionalStringSchema,
  googleEmail: z.string().trim().email().optional(),
  googleId: OptionalStringSchema,
  blockList: OptionalTextSchema,
  smartBar: OptionalTextSchema,
  customIcons: OptionalBooleanSchema,
  isMember: OptionalBooleanSchema,
  preferredArtServerId: OptionalPositiveIntSchema,
  preferredTextServerId: OptionalPositiveIntSchema,
  memberUntil: z.coerce.date().optional(),
  stripeCustomerId: OptionalStringSchema,
  artModels: OptionalTextSchema,
  lastReward: OptionalTextSchema,
  textModels: OptionalTextSchema,
  vibes: OptionalTextSchema,
  hiddenServerIds: z.unknown().optional(),
}).strict()

export const UserUpdateSchema = UserCreateSchema.partial()
  .omit({
    username: true,
    email: true,
  })
  .strict()

export type ModelConfig = {
  prisma: string
  ownerField?: string
  activeField?: string
  createSchema: z.ZodTypeAny
  updateSchema: z.ZodTypeAny
  publicSelect: Record<string, boolean>
  searchableFields?: string[]
  filterFields?: string[]
  defaultOrderBy?: Record<string, 'asc' | 'desc'>
}

export const CHATGPT_MODEL_REGISTRY = {
  artImage: {
    prisma: 'artImage',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: ArtImageCreateSchema,
    updateSchema: ArtImageUpdateSchema,
    searchableFields: [
      'fileName',
      'promptString',
      'negativePrompt',
      'checkpoint',
      'sampler',
      'designer',
      'genres',
      'serverName',
      'artPrompt',
    ],
    filterFields: [
      'serverId',
      'artId',
      'botId',
      'characterId',
      'chatId',
      'componentId',
      'milestoneId',
      'pitchId',
      'promptId',
      'resourceId',
      'rewardId',
      'butterflyId',
      'checkpointResourceId',
      'designer',
      'fileType',
    ],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      imageData: true,
      thumbnailData: true,
      fileName: true,
      fileType: true,
      imagePath: true,
      rarity: true,
      path: true,
      promptString: true,
      negativePrompt: true,
      checkpoint: true,
      checkpointResourceId: true,
      sampler: true,
      seed: true,
      steps: true,
      cfg: true,
      cfgHalf: true,
      designer: true,
      genres: true,
      isPublic: true,
      isMature: true,
      isActive: true,
      artPrompt: true,
      serverId: true,
      serverName: true,
      serverUrl: true,
      userId: true,
      artId: true,
      botId: true,
      componentId: true,
      milestoneId: true,
      pitchId: true,
      promptId: true,
      resourceId: true,
      rewardId: true,
      chatId: true,
      characterId: true,
      butterflyId: true,
    },
  },

  artCollection: {
    prisma: 'artCollection',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: ArtCollectionCreateSchema,
    updateSchema: ArtCollectionUpdateSchema,
    searchableFields: ['label', 'description', 'username'],
    filterFields: ['label', 'username'],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      userId: true,
      label: true,
      isMature: true,
      isPublic: true,
      isActive: true,
      description: true,
      username: true,
    },
  },

  bot: {
    prisma: 'bot',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: BotCreateSchema,
    updateSchema: BotUpdateSchema,
    searchableFields: [
      'name',
      'subtitle',
      'description',
      'botIntro',
      'userIntro',
      'prompt',
      'theme',
      'personality',
      'modules',
      'sampleResponse',
      'tagline',
      'designer',
      'serverName',
    ],
    filterFields: [
      'BotType',
      'designer',
      'serverId',
      'serverName',
      'underConstruction',
    ],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      BotType: true,
      name: true,
      subtitle: true,
      description: true,
      avatarImage: true,
      botIntro: true,
      userIntro: true,
      prompt: true,
      trainingPath: true,
      theme: true,
      personality: true,
      modules: true,
      sampleResponse: true,
      tagline: true,
      isPublic: true,
      isMature: true,
      isActive: true,
      underConstruction: true,
      canDelete: true,
      userId: true,
      designer: true,
      serverId: true,
      serverName: true,
      artImageId: true,
    },
  },

  character: {
    prisma: 'character',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: CharacterCreateSchema,
    updateSchema: CharacterUpdateSchema,
    searchableFields: [
      'name',
      'honorific',
      'species',
      'class',
      'genre',
      'personality',
      'backstory',
      'drive',
      'inventory',
      'quirks',
      'skills',
      'artPrompt',
      'designer',
    ],
    filterFields: [
      'species',
      'class',
      'genre',
      'designer',
      'level',
      'artImageId',
    ],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      name: true,
      achievements: true,
      alignment: true,
      experience: true,
      level: true,
      class: true,
      species: true,
      backstory: true,
      drive: true,
      inventory: true,
      statName1: true,
      statValue1: true,
      statName2: true,
      statValue2: true,
      statName3: true,
      statValue3: true,
      statName4: true,
      statValue4: true,
      statName5: true,
      statValue5: true,
      statName6: true,
      statValue6: true,
      quirks: true,
      skills: true,
      genre: true,
      artImageId: true,
      isPublic: true,
      isMature: true,
      isActive: true,
      userId: true,
      artPrompt: true,
      goalStat1Name: true,
      goalStat1Value: true,
      goalStat2Name: true,
      goalStat2Value: true,
      goalStat3Name: true,
      goalStat3Value: true,
      goalStat4Name: true,
      goalStat4Value: true,
      honorific: true,
      imagePath: true,
      designer: true,
      personality: true,
    },
  },

  chat: {
    prisma: 'chat',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: ChatCreateSchema,
    updateSchema: ChatUpdateSchema,
    searchableFields: [
      'sender',
      'recipient',
      'content',
      'title',
      'botName',
      'channel',
      'botResponse',
      'serverName',
    ],
    filterFields: [
      'type',
      'sender',
      'recipient',
      'isFavorite',
      'isRead',
      'originId',
      'previousEntryId',
      'botId',
      'recipientId',
      'artImageId',
      'promptId',
      'characterId',
      'dreamId',
      'serverId',
      'channel',
    ],
    defaultOrderBy: {
      createdAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      type: true,
      sender: true,
      recipient: true,
      content: true,
      title: true,
      isFavorite: true,
      previousEntryId: true,
      originId: true,
      userId: true,
      botId: true,
      recipientId: true,
      artImageId: true,
      promptId: true,
      botName: true,
      channel: true,
      botResponse: true,
      characterId: true,
      isRead: true,
      readAt: true,
      isPublic: true,
      isActive: true,
      isMature: true,
      dreamId: true,
      serverId: true,
      serverName: true,
    },
  },

  dream: {
    prisma: 'dream',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: DreamCreateSchema,
    updateSchema: DreamUpdateSchema,
    searchableFields: [
      'title',
      'slug',
      'description',
      'currentVibe',
      'currentPrompt',
      'privacyCode',
    ],
    filterFields: [
      'slug',
      'pitchId',
      'artId',
      'artImageId',
      'textServerId',
      'artServerId',
      'artCollectionId',
      'scenarioId',
      'accessMode',
    ],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      title: true,
      slug: true,
      description: true,
      currentVibe: true,
      currentPrompt: true,
      userId: true,
      pitchId: true,
      artImageId: true,
      textServerId: true,
      artServerId: true,
      artCollectionId: true,
      scenarioId: true,
      accessMode: true,
      privacyCode: true,
      isPublic: true,
      isMature: true,
      isActive: true,
    },
  },

  pitch: {
    prisma: 'pitch',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: PitchCreateSchema,
    updateSchema: PitchUpdateSchema,
    searchableFields: [
      'title',
      'pitch',
      'designer',
      'flavorText',
      'highlightImage',
      'artPrompt',
      'description',
      'examples',
      'icon',
    ],
    filterFields: ['PitchType', 'creationSource', 'designer', 'artImageId'],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      title: true,
      pitch: true,
      designer: true,
      flavorText: true,
      highlightImage: true,
      PitchType: true,
      creationSource: true,
      isMature: true,
      isPublic: true,
      isActive: true,
      userId: true,
      artPrompt: true,
      description: true,
      artImageId: true,
      examples: true,
      icon: true,
    },
  },

  prompt: {
    prisma: 'prompt',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: PromptCreateSchema,
    updateSchema: PromptUpdateSchema,
    searchableFields: ['prompt'],
    filterFields: ['creationSource', 'pitchId', 'botId', 'artImageId'],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      prompt: true,
      userId: true,
      isMature: true,
      isPublic: true,
      isActive: true,
      creationSource: true,
      pitchId: true,
      botId: true,
      artImageId: true,
    },
  },

  resource: {
    prisma: 'resource',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: ResourceCreateSchema,
    updateSchema: ResourceUpdateSchema,
    searchableFields: [
      'name',
      'customLabel',
      'MediaPath',
      'customUrl',
      'civitaiUrl',
      'huggingUrl',
      'localPath',
      'description',
      'generation',
    ],
    filterFields: ['resourceType', 'supportedServer', 'artImageId'],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      name: true,
      customLabel: true,
      MediaPath: true,
      customUrl: true,
      civitaiUrl: true,
      huggingUrl: true,
      localPath: true,
      description: true,
      isPublic: true,
      isMature: true,
      isActive: true,
      resourceType: true,
      supportedServer: true,
      userId: true,
      artImageId: true,
      generation: true,
    },
  },

  reward: {
    prisma: 'reward',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: RewardCreateSchema,
    updateSchema: RewardUpdateSchema,
    searchableFields: [
      'icon',
      'text',
      'power',
      'collection',
      'label',
      'imagePath',
      'artPrompt',
    ],
    filterFields: ['collection', 'rarity', 'label', 'artImageId'],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      icon: true,
      text: true,
      power: true,
      collection: true,
      rarity: true,
      rewardType: true,
      label: true,
      userId: true,
      artImageId: true,
      imagePath: true,
      artPrompt: true,
      isPublic: true,
      isMature: true,
      isActive: true,
    },
  },

  scenario: {
    prisma: 'scenario',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: ScenarioCreateSchema,
    updateSchema: ScenarioUpdateSchema,
    searchableFields: [
      'title',
      'description',
      'intros',
      'imagePath',
      'locations',
      'artPrompt',
      'genres',
      'inspirations',
    ],
    filterFields: ['artImageId', 'genres'],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      title: true,
      description: true,
      intros: true,
      userId: true,
      artImageId: true,
      imagePath: true,
      locations: true,
      artPrompt: true,
      genres: true,
      inspirations: true,
      isMature: true,
      isPublic: true,
      isActive: true,
    },
  },

  server: {
    prisma: 'server',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: ServerCreateSchema,
    updateSchema: ServerUpdateSchema,
    searchableFields: [
      'title',
      'label',
      'description',
      'category',
      'baseUrl',
      'endpointPath',
      'healthPath',
      'apiLink',
      'model',
      'designer',
      'version',
      'notes',
      'artPrompt',
    ],
    filterFields: [
      'serverType',
      'category',
      'isOfficial',
      'isDefault',
      'isEditable',
      'accessMode',
      'authType',
      'useOidc',
      'lastStatus',
    ],
    defaultOrderBy: {
      sortOrder: 'asc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      title: true,
      label: true,
      description: true,
      serverType: true,
      category: true,
      baseUrl: true,
      endpointPath: true,
      healthPath: true,
      userId: true,
      isActive: true,
      isMature: true,
      isPublic: true,
      isOfficial: true,
      isDefault: true,
      isEditable: true,
      accessMode: true,
      authType: true,
      apiKeyName: true,
      useOidc: true,
      oidcProvider: true,
      apiLink: true,
      model: true,
      designer: true,
      version: true,
      notes: true,
      sortOrder: true,
      lastCheckedAt: true,
      lastStatus: true,
      artPrompt: true,
    },
  },

  tag: {
    prisma: 'tag',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: TagCreateSchema,
    updateSchema: TagUpdateSchema,
    searchableFields: ['label', 'title', 'flavorText', 'pitch'],
    filterFields: ['label', 'title', 'artImageId'],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      label: true,
      title: true,
      flavorText: true,
      pitch: true,
      isPublic: true,
      isMature: true,
      isActive: true,
      userId: true,
      artImageId: true,
    },
  },

  theme: {
    prisma: 'theme',
    ownerField: 'userId',
    activeField: 'isActive',
    createSchema: ThemeCreateSchema,
    updateSchema: ThemeUpdateSchema,
    searchableFields: ['name', 'values', 'tagline', 'room', 'colorScheme'],
    filterFields: ['name', 'colorScheme', 'prefersDark'],
    defaultOrderBy: {
      createdAt: 'desc',
    },
    publicSelect: {
      id: true,
      name: true,
      values: true,
      userId: true,
      isPublic: true,
      isActive: true,
      createdAt: true,
      tagline: true,
      room: true,
      colorScheme: true,
      prefersDark: true,
    },
  },

  user: {
    prisma: 'user',
    ownerField: 'id',
    activeField: 'isActive',
    createSchema: UserCreateSchema,
    updateSchema: UserUpdateSchema,
    searchableFields: [
      'username',
      'email',
      'name',
      'avatarImage',
      'bio',
      'languages',
      'timezone',
      'designerName',
      'googleEmail',
      'smartBar',
      'artModels',
      'lastReward',
      'textModels',
      'vibes',
    ],
    filterFields: [
      'username',
      'email',
      'showMature',
      'Role',
      'customIcons',
      'isMember',
      'preferredArtServerId',
      'preferredTextServerId',
    ],
    defaultOrderBy: {
      updatedAt: 'desc',
    },
    publicSelect: {
      id: true,
      createdAt: true,
      updatedAt: true,
      username: true,
      email: true,
      questPoints: true,
      emailVerified: true,
      name: true,
      avatarImage: true,
      bio: true,
      languages: true,
      timezone: true,
      karma: true,
      mana: true,
      clickRecord: true,
      matchRecord: true,
      showMature: true,
      Role: true,
      artImageId: true,
      designerName: true,
      googleEmail: true,
      isPublic: true,
      isActive: true,
      smartBar: true,
      customIcons: true,
      isMember: true,
      preferredArtServerId: true,
      preferredTextServerId: true,
      memberUntil: true,
      artModels: true,
      lastReward: true,
      textModels: true,
      vibes: true,
      hiddenServerIds: true,
    },
  },
} satisfies Record<ChatGptResource, ModelConfig>

export function getModelConfig(resource: ChatGptResource): ModelConfig {
  const config = CHATGPT_MODEL_REGISTRY[resource]

  if (!config) {
    throw createError({
      statusCode: 400,
      statusMessage: `Resource not implemented: ${resource}`,
    })
  }

  return config
}
