-- AlterTable
ALTER TABLE `Art` ADD COLUMN `promptString` VARCHAR(191) NOT NULL DEFAULT ' ';

-- AlterTable
ALTER TABLE `Resource` MODIFY `resourceType` ENUM('CHECKPOINT', 'EMBEDDING', 'LORA', 'LYCORIS', 'HYPERNETWORK', 'CONTROLNET', 'URL', 'API') NOT NULL DEFAULT 'EMBEDDING';
