---
//live chat history
model ChatRoom {
  id          Int       @id @unique @default(autoincrement())
  name        String
  host        String
  description String?
  image       String?
  theme       String?
  nsfw        Boolean?
  messages    Message[]
  createdAt   DateTime  @default(now())
  updatedAt   DateTime  @updatedAt
  inactive    Boolean?
}

model Message {
  id         Int      @id @unique @default(autoincrement())
  chatRoom   ChatRoom @relation(fields: [chatRoomId], references: [id])
  chatRoomId Int
  content    String
  sender     String
  createdAt  DateTime @default(now())
}


###
### Create a new chat room
POST https://kindrobots.org/api/chatrooms/post
Content-Type: application/json

{
  "name": "Kind Robots Chat",
  "host": "silasfelinus",
  "description": "A place for kind robots and humans to chat",
  "image": "https://kindrobots.org/chatroom-image.jpg",
  "theme": "default",
  "nsfw": false
}

###

### Get a list of all chat rooms
GET http://localhost:3000/api/chatrooms

###


### Create a new message in a specific chat room (replace :id with actual ID)
POST http://localhost:3000/api/chatrooms/id/1
Content-Type: application/json

{
  "content": "Hello, world! This is the first message in this chat room.",
  "sender": "Test Testerton"
}

###
### Create a new message in a specific chat room (replace :id with actual ID)
POST http://localhost:3000/api/chatrooms/1
Content-Type: application/json

{
  "content": "Hello, This is the second message!",
  "sender": "Test Testerton"
}

###

### Get details of a specific chat room
GET http://localhost:3000/api/chatrooms/1
Content-Type: application/json

###
### Toggle the active status of a chat room (replace :id with actual ID)
POST http://localhost:3000/api/chatrooms/toggle/1/
Content-Type: application/json

###
