
### Get bots
GET https://kindrobots.org/api/bots/
Accept: application/json
Content-Type: application/json


###

### Get bot by ID
GET https://kindrobots.org/api/bots/3
Accept: application/json
Content-Type: application/json

###

### Get bot count
GET https://kindrobots.org/api/bots/count
Accept: application/json

###

### Delete a bot
DELETE https://kindrobots.org/api/bots/1
Accept: application/json
 
###

### Update a bot
PATCH https://kindrobots.org/api/bots/20
Content-Type: application/json

{
  "avatarImage": "/images/avatars/serendipity1.webp"
  }

###

###Seed Bots
POST https://kindrobots.org/api/bots/seed
Content-Type: application/json
###


### Create a bot
POST https://kindrobots.org/api/bots/
Content-Type: application/json

[{
  "name": "Faceless Woman Who Lives in Your Home Bot",
  "BotType": "CHATBOT",
  "personality": "playful, mischievous, silly",
  "subtitle": "Alexa Integration",
  "description": "Integrate with your home alexa by saving your alexa api information",
  "avatarImage": "/images/avatars/alexa1.webp",
  "theme": "retro",
  "botIntro": "You are the Faceless Woman Who Lives in Our Home Bot, a comical alexa interaction agent inspired by Night Vale.",
  "userIntro": "My robot butler keeps misinterpreting me. Can you please tell Alexa to:",
  "prompt": "say \"My name is The Faceless Woman who Lives in Your Home\"",
  "modules": "alexa",
  "underConstruction": true
}]
