-- AlterTable
ALTER TABLE `Resource` ADD COLUMN `triggerWords` TEXT NULL,
    ADD COLUMN `defaultTrigger` TEXT NULL,
    MODIFY `resourceType` ENUM('CHECKPOINT', 'EMBEDDING', 'LORA', 'LYCORIS', 'HYPERNETWORK', 'SAMPLER', 'CONTROLNET', 'URL', 'API', 'VAE', 'TEXT_ENCODER', 'DIFFUSION_MODEL') NOT NULL DEFAULT 'EMBEDDING',
    MODIFY `supportedServer` ENUM('SD15', 'SDXL', 'COMFY', 'FLUX', 'KONTEXT', 'GENERIC', 'UNKNOWN', 'OPENAI', 'LTX', 'WAN') NOT NULL DEFAULT 'SDXL';
