// /utils/scripts/verifyArtImageOffload.ts
//
// Finished art stops accumulating in the database, and the offload can never
// destroy the only copy.
//
// WHAT WENT WRONG WITHOUT THIS. Every art path funnels through saveImage(),
// which writes raw base64 into ArtImage.imageData, and nothing ever took it
// back out. Measured 2026-08-05: 6,775 rows, 6,123.2 MB, growing with every
// completed job. offloadArtImageBytes closes that loop by writing the file to
// the media share and nulling the column.
//
// That operation is the single most destructive thing in this repo — it
// deletes image bytes — so the properties that make it safe are worth pinning
// rather than trusting to review:
//
//   1. It opts in on an explicit IMAGES_PATH, never on "some directory looks
//      writable". A serverless filesystem accepts writes and then discards
//      them; inferring durability from a successful write is how you get a row
//      pointing at a file that no longer exists with its only copy deleted.
//   2. It reads the file back and compares hashes BEFORE nulling anything.
//   3. The delete is conditional on imageData still holding the value that was
//      read, so a concurrent write loses the race instead of being clobbered.
//   4. It never throws. It runs after the caller's work has committed; a throw
//      would turn a finished generation into a 500 and lose the job.
//
// It also guards the bug that made imagePath untrustworthy in the first place:
// two routes assigned `imagePath: savedImage.fileName`, where fileName is
// `ArtImageUpload-<timestamp>`. file.get.ts redirects to any non-self-
// referential imagePath, so those rows 302'd to a path that does not exist and
// rendered broken while their real bytes sat unread in imageData.
//
//   npx tsx utils/scripts/verifyArtImageOffload.ts
//   npx tsx utils/scripts/verifyArtImageOffload.ts --self-test
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const HELPER = 'server/utils/artImageOffload.ts'
const COMPLETE = 'server/api/art/queue/[id]/complete.post.ts'
const BACKFILL = 'utils/scripts/offloadArtImageData.ts'

// Every route that persists generated bytes. Each must offload, and none may
// write a bare filename into imagePath.
const GENERATE_ROUTES = [
  'server/api/art/generate.post.ts',
  'server/api/comfy/sdxl/generate.post.ts',
  'server/api/chats/openai/images/generate.post.ts',
]

const failures: string[] = []
const check = (ok: boolean, message: string) => {
  if (!ok) failures.push(message)
}

/** Source with comments stripped, so prose about a rule never satisfies it. */
export function withoutComments(source: string): string {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/^\s*\/\/.*$/gm, '')
}

const read = (file: string) =>
  withoutComments(readFileSync(resolve(process.cwd(), file), 'utf8'))

const helper = read(HELPER)

/* -- 1. opt in on IMAGES_PATH, not on an inferred writable directory -------- */

check(
  /process\.env\.IMAGES_PATH/.test(helper),
  `${HELPER} must gate on process.env.IMAGES_PATH. Without an explicit opt-in ` +
    `it will offload on any host whose filesystem accepts a write, including ` +
    `ephemeral serverless ones where the file vanishes after the response.`,
)

check(
  !/getImageStorageRoot\s*\(/.test(helper),
  `${HELPER} must not resolve its destination through getImageStorageRoot(). ` +
    `That helper falls back to public/images under cwd, which makes a ` +
    `throwaway serverless filesystem look like durable storage.`,
)

/* -- 1b. the share root must pre-exist; never create it --------------------- */

check(
  /mediaShareRootIsMounted/.test(helper) && /\bstat\s*\(/.test(helper),
  `${HELPER} must confirm IMAGES_PATH already exists as a directory before ` +
    `writing. Everything here uses mkdir -p, which would materialise a typo'd ` +
    `path — and then the backfill writes gigabytes onto the wrong filesystem ` +
    `while nulling the database copies it thinks it moved.`,
)

const statIndex = helper.search(/mediaShareRootIsMounted\s*\(\s*root\s*\)/)
const mkdirIndex = helper.search(/mkdir\s*\(/)

check(
  statIndex !== -1 && mkdirIndex !== -1 && statIndex < mkdirIndex,
  `${HELPER} must check the root is mounted BEFORE any mkdir. Checking after ` +
    `the directory has been created checks nothing.`,
)

check(
  /mediaShareRootIsMounted/.test(read(BACKFILL)) &&
    /readdir\s*\(/.test(read(BACKFILL)),
  `${BACKFILL} must preflight that the share root exists AND is non-empty. ` +
    `The real share holds thousands of images; an empty directory at that ` +
    `path means the mount is absent, and this script deletes database copies.`,
)

/* -- 2. read the file back and compare before deleting anything ------------- */

check(
  /readFile\s*\(/.test(helper),
  `${HELPER} must read the written file back off disk before nulling ` +
    `imageData. A write that "succeeded" onto an unmounted share is the one ` +
    `failure that costs the only copy.`,
)

const readBackIndex = helper.search(/readFile\s*\(/)
const nullIndex = helper.search(/imageData:\s*null/)

check(
  readBackIndex !== -1 && nullIndex !== -1 && readBackIndex < nullIndex,
  `${HELPER} must read the file back BEFORE the update that sets ` +
    `imageData: null. Verifying after the delete verifies nothing.`,
)

check(
  /digest\([^)]*\)\s*!==\s*digest\([^)]*\)/.test(helper),
  `${HELPER} must compare a hash of the bytes read back against a hash of the ` +
    `bytes written. A length check passes on a truncated or wrong file.`,
)

/* -- 3. the delete is conditional on the row not having changed ------------- */

check(
  /updateMany\(/.test(helper) && /where:\s*\{[^}]*imageData:\s*image\.imageData/.test(helper),
  `${HELPER} must null imageData through a conditional updateMany whose where ` +
    `clause still matches the imageData it read, so a concurrent write to the ` +
    `same row loses the race instead of being silently clobbered.`,
)

/* -- 4. it must never throw into the request that already succeeded --------- */

check(
  /catch\s*\(/.test(helper),
  `${HELPER} must catch its own failures. It runs after the caller's work has ` +
    `committed, so an uncaught throw turns a completed generation into a 500 ` +
    `and loses the job.`,
)

/* -- 5. offload runs after the completion proof is asserted ----------------- */

const complete = read(COMPLETE)

check(
  /offloadArtImageBytes\s*\(/.test(complete),
  `${COMPLETE} must call offloadArtImageBytes. Without it every completed job ` +
    `leaves its base64 in the database and the table grows without bound.`,
)

const assertIndex = complete.search(/assertArtImageMatchesCompletion\s*\(/)
const offloadIndex = complete.search(/offloadArtImageBytes\s*\(/)

check(
  assertIndex !== -1 && offloadIndex !== -1 && assertIndex < offloadIndex,
  `${COMPLETE} must offload AFTER assertArtImageMatchesCompletion, which ` +
    `hashes ArtImage.imageData against the Comfy completion proof. Offloading ` +
    `first nulls the column that assertion reads and rejects every ` +
    `proof-carrying job.`,
)

/* -- 6. no route writes a bare filename into imagePath ---------------------- */

for (const route of [...GENERATE_ROUTES, 'server/api/art/save-generated.post.ts']) {
  const source = read(route)

  check(
    !/imagePath:\s*savedImage\.fileName/.test(source),
    `${route} assigns imagePath: savedImage.fileName. That value is ` +
      `"ArtImageUpload-<timestamp>" (or a local absolute path in development), ` +
      `not a URL — file.get.ts redirects to it and the image renders broken ` +
      `while its real bytes sit unread in imageData.`,
  )
}

for (const route of GENERATE_ROUTES) {
  check(
    /offloadArtImageBytes\s*\(/.test(read(route)),
    `${route} persists generated bytes but never offloads them, so every ` +
      `image it creates is another permanent LongText blob.`,
  )
}

/* -- self-test: every assertion above must be able to fail ------------------ */

function selfTest(): void {
  const commentOnly = `
    /* This file does not call getImageStorageRoot() and never sets
       imageData: null without reading the file back first. */
    // imagePath: savedImage.fileName is deliberately not written here.
    const x = 1
  `
  const stripped = withoutComments(commentOnly)

  if (/getImageStorageRoot\s*\(/.test(stripped)) {
    throw new Error('a commented-out getImageStorageRoot must not register as a call')
  }
  if (/imagePath:\s*savedImage\.fileName/.test(stripped)) {
    throw new Error('a commented-out imagePath assignment must not register as one')
  }

  // Ordering rules must actually depend on order, not merely on presence.
  const wrongOrder = withoutComments(`
    await prisma.artImage.updateMany({ data: { imageData: null } })
    const readBack = await fs.readFile(absolute)
  `)
  const wrongRead = wrongOrder.search(/readFile\s*\(/)
  const wrongNull = wrongOrder.search(/imageData:\s*null/)
  if (!(wrongRead > wrongNull)) {
    throw new Error('the read-back-before-delete rule is not order sensitive')
  }

  // The conditional-delete rule must reject an unconditional update.
  const unconditional = withoutComments(`
    await prisma.artImage.updateMany({ where: { id }, data: { imageData: null } })
  `)
  if (/where:\s*\{[^}]*imageData:\s*image\.imageData/.test(unconditional)) {
    throw new Error('an unconditional updateMany must not satisfy the race guard')
  }

  console.log('✅ verifyArtImageOffload self-test passed.')
}

selfTest()

if (failures.length) {
  console.error('\n❌ ArtImage offload contract failed:\n')
  for (const failure of failures) console.error(`  - ${failure}`)
  console.error('')
  process.exitCode = 1
} else if (!process.argv.includes('--self-test')) {
  console.log(
    'ArtImage offload contract passed: explicit IMAGES_PATH opt-in, read-back ' +
      'verified before delete, conditional write, never throws, offload after ' +
      'the completion proof, and no route writes a bare filename into imagePath.',
  )
}
