/*
 * One plate per section (Silas, 2026-10-10: "if we have 400 sections, we have 400 pieces of art").
 * Keyed by section id, separate from PLATES because many section ids (dust-road, hollow-bell, coyote...) are also
 * shared plate keys. Files live in public/zuzu-gamebook/scenes/sections/<id>.webp. Each render is reviewed in
 * conductor projects/zuzu-gamebook/art/ROUND-6.yaml / ROUND-7.yaml before it lands here; a section without an
 * entry shows its shared plate (art.ts sectionPlate()).
 */
import type { ScenePlate } from './art'

export const SECTION_PLATES: Record<string, ScenePlate> = {
  'a1-bowl-night': {
    file: 'sections/a1-bowl-night',
    alt: 'A cracked grey stone bowl holding a little dark water sits alone on bare ground at night.',
    artImageId: 243649,
    source: 'Gamebook round 6, gb6-a1-bowl-night-1',
    fit: 'exact',
    shape: 'square',
  },
  'a1-downwind-fail': {
    file: 'sections/a1-downwind-fail',
    alt: "The one-eyed coyote in a long coat and wide hat stands among black reeds at the water's edge under a pale moon.",
    artImageId: 243614,
    source: 'Gamebook round 6, gb6-a1-downwind-fail-2',
    fit: 'exact',
    shape: 'square',
  },
  'a1-eggs-eaten': {
    file: 'sections/a1-eggs-eaten',
    alt: 'A broken pale shell lies open on a stone slab beside a rust-brown cloth, shell fragments scattered around it.',
    artImageId: 243635,
    source: 'Gamebook round 6, gb6-a1-eggs-eaten-1',
    fit: 'exact',
    shape: 'square',
  },
  'a1-far-bank': {
    file: 'sections/a1-far-bank',
    alt: 'Zuzu, a short grey koala in a rust-brown poncho, orange sash and wide hat, stands alone on a red rock in the desert.',
    artImageId: 243643,
    source: 'Gamebook round 6, gb6-a1-far-bank-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-gun-drowned': {
    file: 'sections/a1-gun-drowned',
    alt: 'A tall black rock is mirrored in a still pool among dark reeds, rings spreading where something has just sunk.',
    artImageId: 243631,
    source: 'Gamebook round 6, gb6-a1-gun-drowned-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-gun-returned': {
    file: 'sections/a1-gun-returned',
    alt: 'The coyote stands in the desert in his long coat, revolver in his left hand, his right forearm wrapped in cloth.',
    artImageId: 243628,
    source: 'Gamebook round 6, gb6-a1-gun-returned-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-nest': {
    file: 'sections/a1-nest',
    alt: 'A single pale leathery egg rests in a hollow of sand among dry reeds on a flat riverbank.',
    artImageId: 243634,
    source: 'Gamebook round 6, gb6-a1-nest-2',
    fit: 'exact',
  },
  'a1-on-the-stones': {
    file: 'sections/a1-on-the-stones',
    alt: 'Zuzu stands alone on a black stone at the edge of dark water, katana on his back, braced and watchful.',
    artImageId: 243617,
    source: 'Gamebook round 6, gb6-a1-on-the-stones-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-stones-watch': {
    file: 'sections/a1-stones-watch',
    alt: 'The one-eyed coyote stands knee-deep in a dark pool among red rocks, rings spreading around him, one paw near his revolver.',
    artImageId: 243607,
    source: 'Gamebook round 6, gb6-a1-stones-watch-1',
    fit: 'exact',
  },
  'a1-the-shot': {
    file: 'sections/a1-the-shot',
    alt: 'The coyote fires his revolver from one knee as a great crocodile surges out of the water beside him.',
    artImageId: 243624,
    source: 'Gamebook round 6, gb6-a1-the-shot-2',
    fit: 'exact',
  },
  'a2-badger': {
    file: 'sections/a2-badger',
    alt: 'An old badger shopkeeper in a white shirt and orange apron sits slumped in a doorway between flour sacks.',
    artImageId: 243667,
    source: 'Gamebook round 6, gb6-a2-badger-1',
    fit: 'exact',
  },
  'a2-song': {
    file: 'sections/a2-song',
    alt: 'Zuzu stands bareheaded in a smoky street at dusk, a tall wooden bell tower rising behind him.',
    artImageId: 243665,
    source: 'Gamebook round 6, gb6-a2-song-1',
    fit: 'exact',
    shape: 'tall',
  },
  aftermath: {
    file: 'sections/aftermath',
    alt: 'The coyote kneels in the dust in his long coat and hat, his right arm wrapped, beside the body of the crocodile.',
    artImageId: 243588,
    source: 'Gamebook round 6, gb6-aftermath-1',
    fit: 'exact',
    shape: 'square',
  },
  'cold-camp': {
    file: 'sections/cold-camp',
    alt: 'Zuzu crouches on a rock under the stars with no fire, his breath a small cloud in the cold night air.',
    artImageId: 243595,
    source: 'Gamebook round 6, gb6-cold-camp-2',
    fit: 'exact',
  },
  'dust-road': {
    file: 'sections/dust-road',
    alt: 'A twisted bare tree leans over a dirt track climbing toward a small shrine on a ridge under a purple dusk sky.',
    artImageId: 243592,
    source: 'Gamebook round 6, gb6-dust-road-1',
    fit: 'exact',
    shape: 'tall',
  },
  'hb-store-empty': {
    file: 'sections/hb-store-empty',
    alt: 'A dim, empty general store: bare shelves, a long wooden counter and dust hanging in the light from one window.',
    artImageId: 243659,
    source: 'Gamebook round 6, gb6-hb-store-empty-1',
    fit: 'exact',
  },
  'hb-store-find': {
    file: 'sections/hb-store-find',
    alt: 'A shallow wooden box packed with clean white linen sits on a scuffed store counter.',
    artImageId: 243658,
    source: 'Gamebook round 6, gb6-hb-store-find-2',
    fit: 'exact',
    shape: 'square',
  },
  'hollow-bell': {
    file: 'sections/hollow-bell',
    alt: 'Zuzu stands in a stone gateway with fire roaring behind him, paper notices pinned to the wall on either side.',
    artImageId: 243651,
    source: 'Gamebook round 6, gb6-hollow-bell-1',
    fit: 'exact',
  },
  'sister-trust': {
    file: 'sections/sister-trust',
    alt: 'Zuzu sits cross-legged in the ash, his wide hat shading his eyes, as a small fennec settles in close in front of him.',
    artImageId: 243663,
    source: 'Gamebook round 6, gb6-sister-trust-1',
    fit: 'exact',
    shape: 'tall',
  },
  standoff: {
    file: 'sections/standoff',
    alt: 'The one-eyed coyote kneels in dark water under a shaft of light, his hand resting near his revolver.',
    artImageId: 243579,
    source: 'Gamebook round 6, gb6-standoff-2',
    fit: 'exact',
    shape: 'square',
  },
  survivors: {
    file: 'sections/survivors',
    alt: 'A fennec girl with fierce orange eyes crouches on a burned boardwalk, clutching her little brother.',
    artImageId: 243661,
    source: 'Gamebook round 6, gb6-survivors-1',
    fit: 'exact',
  },
}
