/*
 * One plate per section (Silas, 2026-10-10: "if we have 400 sections, we have 400 pieces of art").
 * Keyed by section id, separate from PLATES because many section ids (dust-road, hollow-bell, coyote...) are also
 * shared plate keys. Files live in public/zuzu-gamebook/scenes/sections/<id>.webp. Each render is reviewed in
 * conductor projects/zuzu-gamebook/art/ROUND-6.yaml / ROUND-7.yaml before it lands here; a section without an
 * entry shows its shared plate (art.ts sectionPlate()).
 */
import type { ScenePlate } from './art'

export const SECTION_PLATES: Record<string, ScenePlate> = {
  'a1-bad-ground': {
    file: 'sections/a1-bad-ground',
    alt: 'Zuzu lies sprawled on his back in the mud while a grinning crocodile looms over him from the dark.',
    artImageId: 244399,
    source: 'Gamebook round 8, gb8-a1-bad-ground-k',
    fit: 'exact',
  },
  'a1-black-stones': {
    file: 'sections/a1-black-stones',
    alt: 'Zuzu wades through a shallow desert pool at sunset, stocky in his zigzag poncho and straw hat, his katana at his side.',
    artImageId: 244679,
    source: 'Gamebook round 8, gb8h-a1-black-stones-1',
    fit: 'exact',
  },
  'a1-bowl-night': {
    file: 'sections/a1-bowl-night',
    alt: 'A cracked grey stone bowl holding a little dark water sits alone on bare ground at night.',
    artImageId: 243649,
    source: 'Gamebook round 6, gb6-a1-bowl-night-1',
    fit: 'exact',
    shape: 'square',
  },
  'a1-downwind-fail': {
    file: 'sections/a1-downwind-fail',
    alt: "The one-eyed coyote in a long coat and wide hat stands among black reeds at the water's edge under a pale moon.",
    artImageId: 243614,
    source: 'Gamebook round 6, gb6-a1-downwind-fail-2',
    fit: 'exact',
    shape: 'square',
  },
  'a1-eggs-eaten': {
    file: 'sections/a1-eggs-eaten',
    alt: 'A broken pale shell lies open on a stone slab beside a rust-brown cloth, shell fragments scattered around it.',
    artImageId: 243635,
    source: 'Gamebook round 6, gb6-a1-eggs-eaten-1',
    fit: 'exact',
    shape: 'square',
  },
  'a1-eggs-left': {
    file: 'sections/a1-eggs-left',
    alt: 'A small animal sits on a curving riverbank below a red rock peak at sunset.',
    artImageId: 244589,
    source: 'Gamebook round 8, gb8-a1-eggs-left-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-eggs-shared': {
    file: 'sections/a1-eggs-shared',
    alt: 'Zuzu sits on the bank of a red-lit desert pool at sunset, two small eggs in the sand beside him.',
    artImageId: 244869,
    source: 'Gamebook round 9, gb9-a1-eggs-shared-1',
    fit: 'exact',
  },
  'a1-far-bank': {
    file: 'sections/a1-far-bank',
    alt: 'Zuzu, a short grey koala in a rust-brown poncho, orange sash and wide hat, stands alone on a red rock in the desert.',
    artImageId: 243643,
    source: 'Gamebook round 6, gb6-a1-far-bank-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-gun': {
    file: 'sections/a1-gun',
    alt: 'An old revolver lies half-sunk in still, dark water at dusk.',
    artImageId: 244419,
    source: 'Gamebook round 8, gb8-a1-gun-1',
    fit: 'exact',
    shape: 'square',
  },
  'a1-gun-drowned': {
    file: 'sections/a1-gun-drowned',
    alt: 'A tall black rock is mirrored in a still pool among dark reeds, rings spreading where something has just sunk.',
    artImageId: 243631,
    source: 'Gamebook round 6, gb6-a1-gun-drowned-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-gun-kept': {
    file: 'sections/a1-gun-kept',
    alt: 'Zuzu stands knee-deep in red-lit water at sunset, his katana slung behind him.',
    artImageId: 244871,
    source: 'Gamebook round 9, gb9-a1-gun-kept-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-gun-returned': {
    file: 'sections/a1-gun-returned',
    alt: 'The coyote stands in the desert in his long coat, revolver in his left hand, his right forearm wrapped in cloth.',
    artImageId: 243628,
    source: 'Gamebook round 6, gb6-a1-gun-returned-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-gun-road': {
    file: 'sections/a1-gun-road',
    alt: 'Zuzu walks out of the dark holding a revolver, another lying in the dirt behind him while a shadowed figure watches.',
    artImageId: 244402,
    source: 'Gamebook round 8, gb8-a1-gun-road-k',
    fit: 'exact',
  },
  'a1-laid-out': {
    file: 'sections/a1-laid-out',
    alt: 'The coyote stands in his long coat among black rocks, a revolver at his side and a cracked bowl at his feet.',
    artImageId: 244416,
    source: 'Gamebook round 8, gb8-a1-laid-out-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-nest': {
    file: 'sections/a1-nest',
    alt: 'A single pale leathery egg rests in a hollow of sand among dry reeds on a flat riverbank.',
    artImageId: 243634,
    source: 'Gamebook round 6, gb6-a1-nest-2',
    fit: 'exact',
  },
  'a1-on-the-stones': {
    file: 'sections/a1-on-the-stones',
    alt: 'Zuzu stands alone on a black stone at the edge of dark water, katana on his back, braced and watchful.',
    artImageId: 243617,
    source: 'Gamebook round 6, gb6-a1-on-the-stones-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-reeds': {
    file: 'sections/a1-reeds',
    alt: 'Zuzu stands among dead reeds in his zigzag poncho and wide straw hat, his sheathed katana planted at his side.',
    artImageId: 244691,
    source: 'Gamebook round 8, gb8h-a1-reeds-2',
    fit: 'exact',
    shape: 'square',
  },
  'a1-stars': {
    file: 'sections/a1-stars',
    alt: 'Zuzu stands on a dark rock ridge under a sky full of stars, his poncho bright against the night.',
    artImageId: 244682,
    source: 'Gamebook round 8, gb8h-a1-stars-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-stones-watch': {
    file: 'sections/a1-stones-watch',
    alt: 'The one-eyed coyote stands knee-deep in a dark pool among red rocks, rings spreading around him, one paw near his revolver.',
    artImageId: 243607,
    source: 'Gamebook round 6, gb6-a1-stones-watch-1',
    fit: 'exact',
  },
  'a1-terrain': {
    file: 'sections/a1-terrain',
    alt: 'Zuzu stands small in a thicket of dead reeds while two huge glowing eyes watch him from the blackness above.',
    artImageId: 244397,
    source: 'Gamebook round 8, gb8-a1-terrain-k',
    fit: 'exact',
  },
  'a1-the-shot': {
    file: 'sections/a1-the-shot',
    alt: 'The coyote fires his revolver from one knee as a great crocodile surges out of the water beside him.',
    artImageId: 243624,
    source: 'Gamebook round 6, gb6-a1-the-shot-2',
    fit: 'exact',
  },
  'a2-back': {
    file: 'sections/a2-back',
    alt: 'A tiny fennec toddler with enormous ears creeps forward along a dark road under the moon.',
    artImageId: 244705,
    source: 'Gamebook round 9, gb9-a2-back-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-badger': {
    file: 'sections/a2-badger',
    alt: 'An old badger shopkeeper in a white shirt and orange apron sits slumped in a doorway between flour sacks.',
    artImageId: 243667,
    source: 'Gamebook round 6, gb6-a2-badger-1',
    fit: 'exact',
  },
  'a2-badger-dies': {
    file: 'sections/a2-badger-dies',
    alt: 'A pair of round spectacles and a few brass shell casings lie on a dusty wooden counter.',
    artImageId: 243676,
    source: 'Gamebook round 6, gb6-a2-badger-dies-2',
    fit: 'exact',
    shape: 'square',
  },
  'a2-badger-lie': {
    file: 'sections/a2-badger-lie',
    alt: 'A battered metal canteen lies on its side on dusty floorboards in a dim room.',
    artImageId: 244698,
    source: 'Gamebook round 9, gb9-a2-badger-lie-1',
    fit: 'exact',
  },
  'a2-badger-turned': {
    file: 'sections/a2-badger-turned',
    alt: 'Zuzu stands in a sunlit doorway in his zigzag poncho and straw hat, a full canteen at his hip.',
    artImageId: 244701,
    source: 'Gamebook round 9, gb9-a2-badger-turned-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-badger-water': {
    file: 'sections/a2-badger-water',
    alt: 'The old badger shopkeeper tips a glass bottle to his mouth by a dusty window, eyes closed.',
    artImageId: 244696,
    source: 'Gamebook round 9, gb9-a2-badger-water-1',
    fit: 'exact',
    shape: 'square',
  },
  'a2-candle': {
    file: 'sections/a2-candle',
    alt: 'A single candle burns on the floor at the far end of a dark wooden hall, framed by an open doorway.',
    artImageId: 244592,
    source: 'Gamebook round 8, gb8-a2-candle-2',
    fit: 'exact',
  },
  'a2-gift': {
    file: 'sections/a2-gift',
    alt: "A raccoon's masked face is carved into a weathered wooden post at the edge of the desert.",
    artImageId: 243725,
    source: 'Gamebook round 6, gb6-a2-gift-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-hum': {
    file: 'sections/a2-hum',
    alt: 'Zuzu sits by a small campfire in a dark valley at night, humming under his straw hat.',
    artImageId: 244702,
    source: 'Gamebook round 9, gb9-a2-hum-1',
    fit: 'exact',
  },
  'a2-leaving': {
    file: 'sections/a2-leaving',
    alt: 'A squat brick gatehouse stands alone in the dunes, a chain hanging in its dark arch.',
    artImageId: 244711,
    source: 'Gamebook round 9, gb9-a2-leaving-2',
    fit: 'exact',
  },
  'a2-linen': {
    file: 'sections/a2-linen',
    alt: 'A folded grey cloth lies on dark floorboards in a shaft of light.',
    artImageId: 243689,
    source: 'Gamebook round 6, gb6-a2-linen-1',
    fit: 'exact',
    shape: 'square',
  },
  'a2-looter': {
    file: 'sections/a2-looter',
    alt: 'A young raccoon in a vest and a long cloak kneels in a burned street holding a knife, a pair of boots beside him.',
    artImageId: 243677,
    source: 'Gamebook round 6, gb6-a2-looter-1',
    fit: 'exact',
  },
  'a2-looter-broken': {
    file: 'sections/a2-looter-broken',
    alt: 'A kitchen knife lies dropped in grey ash, small footprints leading away from it.',
    artImageId: 243682,
    source: 'Gamebook round 6, gb6-a2-looter-broken-2',
    fit: 'exact',
    shape: 'square',
  },
  'a2-looter-cut': {
    file: 'sections/a2-looter-cut',
    alt: 'Zuzu lies face-down in a grey street with his katana still on his back while a distant figure watches from the end of the lane.',
    artImageId: 244435,
    source: 'Gamebook round 8, gb8-a2-looter-cut-1',
    fit: 'exact',
  },
  'a2-looter-disarmed': {
    file: 'sections/a2-looter-disarmed',
    alt: 'A kitchen knife lies on dark floorboards under a starry sky.',
    artImageId: 244709,
    source: 'Gamebook round 9, gb9-a2-looter-disarmed-2',
    fit: 'exact',
  },
  'a2-looter-night': {
    file: 'sections/a2-looter-night',
    alt: 'A young raccoon walks out of a lit bell tower at night, a kitchen knife low in his paw.',
    artImageId: 244707,
    source: 'Gamebook round 9, gb9-a2-looter-night-2',
    fit: 'exact',
    shape: 'square',
  },
  'a2-looter-shamed': {
    file: 'sections/a2-looter-shamed',
    alt: 'Zuzu kneels in a ruined doorway, paws on his knees, a pair of worn boots set down beside him.',
    artImageId: 243683,
    source: 'Gamebook round 6, gb6-a2-looter-shamed-1',
    fit: 'exact',
  },
  'a2-looter-spared': {
    file: 'sections/a2-looter-spared',
    alt: 'A young raccoon in a vest walks out through a town archway at dusk, smoke rising over the roofs behind him.',
    artImageId: 243685,
    source: 'Gamebook round 6, gb6-a2-looter-spared-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-looter-watch': {
    file: 'sections/a2-looter-watch',
    alt: 'A thin young raccoon kneels on the ground under a smoke-streaked orange sky, looking up.',
    artImageId: 244882,
    source: 'Gamebook round 9, gb9-a2-looter-watch-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-noon': {
    file: 'sections/a2-noon',
    alt: 'An empty alley between wooden buildings at noon, a broom leaning on a wall and a bell tower beyond.',
    artImageId: 243705,
    source: 'Gamebook round 6, gb6-a2-noon-1',
    fit: 'exact',
  },
  'a2-sister-snarl': {
    file: 'sections/a2-sister-snarl',
    alt: 'The fennec girl clutches her bandaged paws to her chest and bares her teeth, ears flat with fury.',
    artImageId: 243718,
    source: 'Gamebook round 6, gb6-a2-sister-snarl-2',
    fit: 'exact',
    shape: 'square',
  },
  'a2-sister-wall': {
    file: 'sections/a2-sister-wall',
    alt: 'The fennec girl stands alone against a wall of planks, wrists bandaged, ears up and wary.',
    artImageId: 243714,
    source: 'Gamebook round 6, gb6-a2-sister-wall-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-sister-water': {
    file: 'sections/a2-sister-water',
    alt: 'Zuzu crouches to set a small water bottle on the ground while a little fennec watches from across the floor.',
    artImageId: 243716,
    source: 'Gamebook round 6, gb6-a2-sister-water-2',
    fit: 'exact',
  },
  'a2-song': {
    file: 'sections/a2-song',
    alt: 'Zuzu stands bareheaded in a smoky street at dusk, a tall wooden bell tower rising behind him.',
    artImageId: 243665,
    source: 'Gamebook round 6, gb6-a2-song-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-tower': {
    file: 'sections/a2-tower',
    alt: 'Zuzu stands at the top of wooden steps in the evening, a lookout tower and pines behind him.',
    artImageId: 243720,
    source: 'Gamebook round 6, gb6-a2-tower-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-tower-fall': {
    file: 'sections/a2-tower-fall',
    alt: 'Zuzu stands in a dim timber stairwell, light falling on him from above.',
    artImageId: 243721,
    source: 'Gamebook round 6, gb6-a2-tower-fall-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-tracks': {
    file: 'sections/a2-tracks',
    alt: 'A pair of worn boots stands in a wooden tub among scattered brass shell casings.',
    artImageId: 243707,
    source: 'Gamebook round 6, gb6-a2-tracks-1',
    fit: 'exact',
    shape: 'square',
  },
  'a2-tracks-close': {
    file: 'sections/a2-tracks-close',
    alt: 'Zuzu crouches low under his wide straw hat, studying the dusty ground at his feet.',
    artImageId: 244436,
    source: 'Gamebook round 8, gb8-a2-tracks-close-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-vigil': {
    file: 'sections/a2-vigil',
    alt: 'Zuzu sits bareheaded by a small fire beneath the bell tower at night, the bell hanging above him.',
    artImageId: 243696,
    source: 'Gamebook round 6, gb6-a2-vigil-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-walk-away': {
    file: 'sections/a2-walk-away',
    alt: 'An empty road runs through the dark toward a lone wooden tower with a lamp lit at its top.',
    artImageId: 243694,
    source: 'Gamebook round 6, gb6-a2-walk-away-2',
    fit: 'exact',
  },
  'a3-apple-days': {
    file: 'sections/a3-apple-days',
    alt: 'A small campfire burns in a hollow ringed by dry brush at night.',
    artImageId: 243758,
    source: 'Gamebook round 6, gb6-a3-apple-days-1',
    fit: 'exact',
  },
  'a3-before-dawn': {
    file: 'sections/a3-before-dawn',
    alt: 'Zuzu stands in the blue dark before dawn, the last embers glowing at his feet.',
    artImageId: 244728,
    source: 'Gamebook round 9, gb9-a3-before-dawn-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-candle-watch': {
    file: 'sections/a3-candle-watch',
    alt: 'A black candle drips wax across cracked stone, its smoke curling upward like a question mark.',
    artImageId: 243793,
    source: 'Gamebook round 6, gb6-a3-candle-watch-2',
    fit: 'exact',
    shape: 'square',
  },
  'a3-close-fires': {
    file: 'sections/a3-close-fires',
    alt: 'A road runs between towering red canyon walls under a night sky toward one small, far-off fire.',
    artImageId: 244595,
    source: 'Gamebook round 8, gb8-a3-close-fires-1',
    fit: 'exact',
  },
  'a3-cold-dawn': {
    file: 'sections/a3-cold-dawn',
    alt: 'The fennec girl crouches by a small fire at dawn, poking it with a stick.',
    artImageId: 243742,
    source: 'Gamebook round 6, gb6-a3-cold-dawn-1',
    fit: 'exact',
  },
  'a3-far-fires': {
    file: 'sections/a3-far-fires',
    alt: 'Zuzu sits hunched by a small campfire at night under his wide hat, his katana across his back.',
    artImageId: 244454,
    source: 'Gamebook round 8, gb8-a3-far-fires-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-fever': {
    file: 'sections/a3-fever',
    alt: 'The fennec girl stands alone in the dark with her wrists bandaged, ears drooping with worry.',
    artImageId: 243772,
    source: 'Gamebook round 6, gb6-a3-fever-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-fever-bandage': {
    file: 'sections/a3-fever-bandage',
    alt: 'A small metal pot sits on a folded white cloth by a campfire at night.',
    artImageId: 244721,
    source: 'Gamebook round 9, gb9-a3-fever-bandage-1',
    fit: 'exact',
    shape: 'square',
  },
  'a3-fever-long-night': {
    file: 'sections/a3-fever-long-night',
    alt: 'Zuzu sits by a small fire at night with a fennec child bundled in his lap.',
    artImageId: 244452,
    source: 'Gamebook round 8, gb8-a3-fever-long-night-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-fever-vigil': {
    file: 'sections/a3-fever-vigil',
    alt: 'Zuzu sits on a log by the fire through the night, a small bundle cradled in his lap.',
    artImageId: 244718,
    source: 'Gamebook round 9, gb9-a3-fever-vigil-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-fever-walk': {
    file: 'sections/a3-fever-walk',
    alt: 'The fennec girl walks alone down a long empty road under a grey sky.',
    artImageId: 244724,
    source: 'Gamebook round 9, gb9-a3-fever-walk-2',
    fit: 'exact',
  },
  'a3-fever-water': {
    file: 'sections/a3-fever-water',
    alt: 'A dented metal canteen lies on its side on a folded cloth beside a small campfire at night.',
    artImageId: 244448,
    source: 'Gamebook round 8, gb8-a3-fever-water-1',
    fit: 'exact',
  },
  'a3-first-day': {
    file: 'sections/a3-first-day',
    alt: 'Zuzu stands under a bare tree on a pale plain while a small fennec sits watching him from a distance.',
    artImageId: 243735,
    source: 'Gamebook round 6, gb6-a3-first-day-1',
    fit: 'exact',
  },
  'a3-going-back': {
    file: 'sections/a3-going-back',
    alt: 'The fennec girl sits alone on a rock under a huge full moon, ears up, watching the dark.',
    artImageId: 243881,
    source: 'Gamebook round 6, gb6-a3-going-back-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-hard-pace': {
    file: 'sections/a3-hard-pace',
    alt: 'The fennec girl walks a pale dune at dusk, carrying her little brother against her chest.',
    artImageId: 243741,
    source: 'Gamebook round 6, gb6-a3-hard-pace-1',
    fit: 'exact',
  },
  'a3-hollow-stone': {
    file: 'sections/a3-hollow-stone',
    alt: 'A flat-topped stone with a shallow hollow sits alone on bare ground in slanting light.',
    artImageId: 243739,
    source: 'Gamebook round 6, gb6-a3-hollow-stone-1',
    fit: 'exact',
    shape: 'square',
  },
  'a3-last-camp': {
    file: 'sections/a3-last-camp',
    alt: 'Zuzu sits on a rock by his campfire before red canyons at dusk.',
    artImageId: 244726,
    source: 'Gamebook round 9, gb9-a3-last-camp-2',
    fit: 'exact',
  },
  'a3-one-fire': {
    file: 'sections/a3-one-fire',
    alt: 'A koala and the fennec girl sit together at one small fire at the foot of a canyon.',
    artImageId: 243786,
    source: 'Gamebook round 6, gb6-a3-one-fire-1',
    fit: 'exact',
  },
  'a3-salt-carry': {
    file: 'sections/a3-salt-carry',
    alt: 'Two lines of footprints lead across pale sand into a dark tunnel mouth.',
    artImageId: 244712,
    source: 'Gamebook round 9, gb9-a3-salt-carry-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-salt-pan': {
    file: 'sections/a3-salt-pan',
    alt: 'The fennec girl kneels on a white salt flat, her paws clasped, enormous ears spread.',
    artImageId: 243750,
    source: 'Gamebook round 6, gb6-a3-salt-pan-1',
    fit: 'exact',
  },
  'a3-salt-refused': {
    file: 'sections/a3-salt-refused',
    alt: 'The fennec girl stands her ground on a ridge of salt, scowling, with her fists at her sides.',
    artImageId: 243756,
    source: 'Gamebook round 6, gb6-a3-salt-refused-1',
    fit: 'exact',
    shape: 'square',
  },
  'a3-salt-wait': {
    file: 'sections/a3-salt-wait',
    alt: 'Zuzu sits alone on a rock in a grey-green mountain valley, his katana over his shoulder.',
    artImageId: 244441,
    source: 'Gamebook round 8, gb8-a3-salt-wait-1',
    fit: 'exact',
  },
  'a3-sandal-tracks': {
    file: 'sections/a3-sandal-tracks',
    alt: 'A black candle burns on cracked ground, a thin thread of smoke rising from it.',
    artImageId: 243744,
    source: 'Gamebook round 6, gb6-a3-sandal-tracks-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-search-dark': {
    file: 'sections/a3-search-dark',
    alt: 'The fennec girl stands alone in a dark rocky hollow, looking out with wide eyes.',
    artImageId: 243764,
    source: 'Gamebook round 6, gb6-a3-search-dark-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-search-dawn': {
    file: 'sections/a3-search-dawn',
    alt: 'The fennec girl lies asleep on the bare ground of the desert at dawn, curled on her side.',
    artImageId: 243767,
    source: 'Gamebook round 6, gb6-a3-search-dawn-2',
    fit: 'exact',
  },
  'a3-shade': {
    file: 'sections/a3-shade',
    alt: 'The fennec girl sits at the foot of a dead tree holding her little brother in her lap.',
    artImageId: 243737,
    source: 'Gamebook round 6, gb6-a3-shade-1',
    fit: 'exact',
    shape: 'square',
  },
  'a3-theft': {
    file: 'sections/a3-theft',
    alt: 'The thin fennec girl kneels by a campfire at night in her pale dress, holding a heel of bread.',
    artImageId: 244714,
    source: 'Gamebook round 9, gb9-a3-theft-1',
    fit: 'exact',
  },
  'a3-theft-caught': {
    file: 'sections/a3-theft-caught',
    alt: 'Zuzu kneels by a small campfire in a dark canyon at night, holding up his thumb.',
    artImageId: 244888,
    source: 'Gamebook round 9, gb9-a3-theft-caught-2',
    fit: 'exact',
  },
  'a3-theft-kept': {
    file: 'sections/a3-theft-kept',
    alt: 'The fennec girl sits on a rock beside a small fire, holding something close against her chest.',
    artImageId: 243769,
    source: 'Gamebook round 6, gb6-a3-theft-kept-2',
    fit: 'exact',
    shape: 'square',
  },
  'a3-tracks-lost': {
    file: 'sections/a3-tracks-lost',
    alt: 'Zuzu stands small on a desert road at sunset, red cliffs rising behind him.',
    artImageId: 243748,
    source: 'Gamebook round 6, gb6-a3-tracks-lost-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-canyon-floor': {
    file: 'sections/a4-canyon-floor',
    alt: 'Zuzu walks the canyon floor beside the fennec girl and her little brother, high walls glowing above them.',
    artImageId: 243800,
    source: 'Gamebook round 6, gb6-a4-canyon-floor-1',
    fit: 'exact',
  },
  'a4-crossroads': {
    file: 'sections/a4-crossroads',
    alt: 'Zuzu stands beneath a dead tree against a huge red sun at the crossroads.',
    artImageId: 244893,
    source: 'Gamebook round 9, gb9-a4-crossroads-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-dry-well': {
    file: 'sections/a4-dry-well',
    alt: 'A grey she-jackal in a white shirt crouches among dark rocks beside a battered bowl.',
    artImageId: 243816,
    source: 'Gamebook round 6, gb6-a4-dry-well-1',
    fit: 'exact',
  },
  'a4-face-covered': {
    file: 'sections/a4-face-covered',
    alt: 'A tall weathered stone carved with a skull-like face leans in the desert under a pale sun.',
    artImageId: 244729,
    source: 'Gamebook round 9, gb9-a4-face-covered-1',
    fit: 'exact',
    shape: 'square',
  },
  'a4-face-listen': {
    file: 'sections/a4-face-listen',
    alt: 'Zuzu stands still in drifting dust, katana on his back, head tilted as if listening.',
    artImageId: 243809,
    source: 'Gamebook round 6, gb6-a4-face-listen-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-face-near': {
    file: 'sections/a4-face-near',
    alt: 'Zuzu sits small in the sand between guttering candles while a vast dark carved figure looms behind him.',
    artImageId: 244498,
    source: 'Gamebook round 8, gb8-a4-face-near-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-face-offerings': {
    file: 'sections/a4-face-offerings',
    alt: 'A single candle burns in a stone basin at the foot of a huge carved stone leg.',
    artImageId: 244497,
    source: 'Gamebook round 8, gb8-a4-face-offerings-2',
    fit: 'exact',
  },
  'a4-feather-look': {
    file: 'sections/a4-feather-look',
    alt: 'Two fennec children stand side by side on a pale dune, looking at each other.',
    artImageId: 243867,
    source: 'Gamebook round 6, gb6-a4-feather-look-2',
    fit: 'exact',
  },
  'a4-hollis-why': {
    file: 'sections/a4-hollis-why',
    alt: 'A gaunt she-jackal in a patched shirt stands in a stone archway with a knife in her hand.',
    artImageId: 243824,
    source: 'Gamebook round 6, gb6-a4-hollis-why-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-mission-road': {
    file: 'sections/a4-mission-road',
    alt: 'A long straight road runs through the dunes toward a mission tower silhouetted against the setting sun.',
    artImageId: 244752,
    source: 'Gamebook round 9, gb9-a4-mission-road-2',
    fit: 'exact',
  },
  'a4-peddler-exposed': {
    file: 'sections/a4-peddler-exposed',
    alt: 'An old prairie-dog woman in a long dress pours water from a jar onto the ground, a pup at her feet.',
    artImageId: 243849,
    source: 'Gamebook round 6, gb6-a4-peddler-exposed-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-peddler-paid': {
    file: 'sections/a4-peddler-paid',
    alt: 'A hare in a dark coat sits cross-legged by a small fire beside a glass jar, a young animal across from him.',
    artImageId: 243853,
    source: 'Gamebook round 6, gb6-a4-peddler-paid-2',
    fit: 'exact',
  },
  'a4-peddler-silent': {
    file: 'sections/a4-peddler-silent',
    alt: 'A weary prairie dog sits wrapped in a shawl against a wall, holding a small jar of water.',
    artImageId: 243850,
    source: 'Gamebook round 6, gb6-a4-peddler-silent-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-raider-kits': {
    file: 'sections/a4-raider-kits',
    alt: 'A small jackal kit in a grey wrap clutches a red cup, looking up with wide frightened eyes.',
    artImageId: 243838,
    source: 'Gamebook round 6, gb6-a4-raider-kits-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-shared-water': {
    file: 'sections/a4-shared-water',
    alt: 'A wide-eyed young jackal clutches a red clay flask to his chest in the desert heat.',
    artImageId: 244743,
    source: 'Gamebook round 9, gb9-a4-shared-water-1',
    fit: 'exact',
    shape: 'square',
  },
  'a4-shrine': {
    file: 'sections/a4-shrine',
    alt: 'A long empty stone corridor leads to a closed door with light behind it.',
    artImageId: 243872,
    source: 'Gamebook round 6, gb6-a4-shrine-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-shrine-song': {
    file: 'sections/a4-shrine-song',
    alt: 'Zuzu sits slumped against a stone wall under his hat while the fennec girl sleeps curled against his side.',
    artImageId: 244511,
    source: 'Gamebook round 8, gb8-a4-shrine-song-1',
    fit: 'exact',
    shape: 'square',
  },
  'a4-shrine-watch': {
    file: 'sections/a4-shrine-watch',
    alt: 'A hooded figure with no face walks out of a dark archway between two burning candles.',
    artImageId: 243876,
    source: 'Gamebook round 6, gb6-a4-shrine-watch-1',
    fit: 'exact',
  },
  'a4-stone-face': {
    file: 'sections/a4-stone-face',
    alt: 'The tiny fennec toddler stands wide-eyed while a dark shape with glowing eyes looms behind him.',
    artImageId: 244892,
    source: 'Gamebook round 9, gb9-a4-stone-face-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-storm': {
    file: 'sections/a4-storm',
    alt: 'A tall dark ruin stands alone under slanting grey rain on the desert flat.',
    artImageId: 244748,
    source: 'Gamebook round 9, gb9-a4-storm-2',
    fit: 'exact',
  },
  'a4-storm-lost': {
    file: 'sections/a4-storm-lost',
    alt: 'The fennec girl stands in a grey downpour with her huge ears drooping, rain streaming across the sand.',
    artImageId: 244749,
    source: 'Gamebook round 9, gb9-a4-storm-lost-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-waystation': {
    file: 'sections/a4-waystation',
    alt: 'A tall hare in a long black coat stands at a desert waystation holding a jar of water beside a smaller hare.',
    artImageId: 243847,
    source: 'Gamebook round 6, gb6-a4-waystation-2',
    fit: 'exact',
  },
  'a4-well-grab': {
    file: 'sections/a4-well-grab',
    alt: 'Zuzu reaches over his shoulder for his katana, crouched and ready in the dusty noon heat.',
    artImageId: 244733,
    source: 'Gamebook round 9, gb9-a4-well-grab-1',
    fit: 'exact',
    shape: 'square',
  },
  'a4-well-hostage': {
    file: 'sections/a4-well-hostage',
    alt: 'A stone water jar bound with rope stands on the dusty ground.',
    artImageId: 244742,
    source: 'Gamebook round 9, gb9-a4-well-hostage-2',
    fit: 'exact',
    shape: 'square',
  },
  'a4-well-paid': {
    file: 'sections/a4-well-paid',
    alt: 'A gaunt she-jackal in a long red cloak stands in a stone doorway beside a cooking pot.',
    artImageId: 243834,
    source: 'Gamebook round 6, gb6-a4-well-paid-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-well-scout': {
    file: 'sections/a4-well-scout',
    alt: 'A young raccoon in a long coat leaps down a rocky slope, kicking up dust.',
    artImageId: 243818,
    source: 'Gamebook round 6, gb6-a4-well-scout-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-well-toll': {
    file: 'sections/a4-well-toll',
    alt: 'Hollis the grey jackal stands by an old stone well with a knife held loosely at her side.',
    artImageId: 244731,
    source: 'Gamebook round 9, gb9-a4-well-toll-1',
    fit: 'exact',
  },
  'a4-well-tricked': {
    file: 'sections/a4-well-tricked',
    alt: 'The fennec girl stands by an old stone well in a pale ragged dress, holding her wrapped wrists out.',
    artImageId: 244739,
    source: 'Gamebook round 9, gb9-a4-well-tricked-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-well-vouched': {
    file: 'sections/a4-well-vouched',
    alt: 'A coil of rope lies beside a small wooden bucket lid on the dusty ground.',
    artImageId: 243820,
    source: 'Gamebook round 6, gb6-a4-well-vouched-1',
    fit: 'exact',
    shape: 'square',
  },
  'a4-well-won': {
    file: 'sections/a4-well-won',
    alt: 'A grey she-jackal kneels on the stones by the well, her knife lowered to the ground.',
    artImageId: 243831,
    source: 'Gamebook round 6, gb6-a4-well-won-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-witch-blood': {
    file: 'sections/a4-witch-blood',
    alt: 'A single long black feather lies across a bare branch.',
    artImageId: 243862,
    source: 'Gamebook round 6, gb6-a4-witch-blood-1',
    fit: 'exact',
    shape: 'square',
  },
  'a4-witch-memory': {
    file: 'sections/a4-witch-memory',
    alt: 'A wooden temple house with a curved roof stands alone in a valley ringed by mountains.',
    artImageId: 243860,
    source: 'Gamebook round 6, gb6-a4-witch-memory-1',
    fit: 'exact',
  },
  'a4-witch-refused': {
    file: 'sections/a4-witch-refused',
    alt: 'Zuzu stands alone beneath a huge dead tree at dusk, hands at his sides.',
    artImageId: 243864,
    source: 'Gamebook round 6, gb6-a4-witch-refused-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-bath': {
    file: 'sections/a5-bath',
    alt: 'The fennec toddler stands scrubbed and fluffy in a little blue smock, his huge ears up.',
    artImageId: 244767,
    source: 'Gamebook round 9, gb9-a5-bath-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-commission': {
    file: 'sections/a5-commission',
    alt: 'The otter abbess pours water from a jug at a desk in a book-lined study.',
    artImageId: 243941,
    source: 'Gamebook round 7, gb7-a5-commission-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-crypt-key': {
    file: 'sections/a5-crypt-key',
    alt: 'A rabbit kit sits on the floor of a long lamplit crypt corridor beside two smaller rabbits.',
    artImageId: 243967,
    source: 'Gamebook round 7, gb7-a5-crypt-key-1',
    fit: 'exact',
  },
  'a5-crypt-wren': {
    file: 'sections/a5-crypt-wren',
    alt: 'A frightened otter novice in a grey habit stands in the dark arch of the crypt stair, between two wall candles.',
    artImageId: 243966,
    source: 'Gamebook round 7, gb7-a5-crypt-wren-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-dawn': {
    file: 'sections/a5-dawn',
    alt: 'A small closed wagon stands inside a dark barn, pink dawn showing through the windows.',
    artImageId: 244782,
    source: 'Gamebook round 9, gb9-a5-dawn-2',
    fit: 'exact',
  },
  'a5-day-two': {
    file: 'sections/a5-day-two',
    alt: 'A wooden bowl of honey-colored porridge sits on a bench under a bright window.',
    artImageId: 243927,
    source: 'Gamebook round 7, gb7-a5-day-two-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-delivered': {
    file: 'sections/a5-delivered',
    alt: 'Zuzu stands alone between wooden barrels in a rocky hollow, one paw open at his side.',
    artImageId: 243987,
    source: 'Gamebook round 7, gb7-a5-delivered-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-dream': {
    file: 'sections/a5-dream',
    alt: 'A pale road runs across dark desert toward a black jagged spire under a sky of stars.',
    artImageId: 243973,
    source: 'Gamebook round 7, gb7-a5-dream-1',
    fit: 'exact',
  },
  'a5-dream-empty': {
    file: 'sections/a5-dream-empty',
    alt: 'A black hole in the shape of a crow with spread wings hangs over a long empty road.',
    artImageId: 243977,
    source: 'Gamebook round 7, gb7-a5-dream-empty-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-dream-home': {
    file: 'sections/a5-dream-home',
    alt: 'A small temple tower with one lit window stands at the end of a wet path among mountains.',
    artImageId: 243975,
    source: 'Gamebook round 7, gb7-a5-dream-home-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-dream-wake': {
    file: 'sections/a5-dream-wake',
    alt: 'The fennec girl in a dark dress stands in a moonlit doorway, eyes half closed.',
    artImageId: 243980,
    source: 'Gamebook round 7, gb7-a5-dream-wake-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-errand-refused': {
    file: 'sections/a5-errand-refused',
    alt: 'The fennec girl sits alone on a step outside a closed wooden door.',
    artImageId: 243945,
    source: 'Gamebook round 7, gb7-a5-errand-refused-1',
    fit: 'exact',
  },
  'a5-errand-taken': {
    file: 'sections/a5-errand-taken',
    alt: 'A sealed letter and a glass of water sit on a table while a dark shape watches through the window.',
    artImageId: 243943,
    source: 'Gamebook round 7, gb7-a5-errand-taken-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-her-hands': {
    file: 'sections/a5-her-hands',
    alt: 'The otter abbess smiles over a bowl of stew between black candles, dark wax beneath her claws.',
    artImageId: 243919,
    source: 'Gamebook round 7, gb7-a5-her-hands-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-kit-box': {
    file: 'sections/a5-kit-box',
    alt: 'A candle burns inside an open wooden box on dark floorboards beside an old leather boot.',
    artImageId: 244522,
    source: 'Gamebook round 8, gb8-a5-kit-box-1',
    fit: 'exact',
  },
  'a5-kit-caught': {
    file: 'sections/a5-kit-caught',
    alt: 'A rabbit kit kneels scrubbing the chapel steps with a bucket of water at dawn.',
    artImageId: 243972,
    source: 'Gamebook round 7, gb7-a5-kit-caught-2',
    fit: 'exact',
  },
  'a5-kit-shielded': {
    file: 'sections/a5-kit-shielded',
    alt: 'A lantern lights a dark plank corridor where something small lies curled at the foot of a closed door.',
    artImageId: 244780,
    source: 'Gamebook round 9, gb9-a5-kit-shielded-2',
    fit: 'exact',
    shape: 'square',
  },
  'a5-kit-supper': {
    file: 'sections/a5-kit-supper',
    alt: 'The fennec toddler hunches over a steaming bowl of stew on a low bench by candlelight.',
    artImageId: 244517,
    source: 'Gamebook round 8, gb8-a5-kit-supper-2',
    fit: 'exact',
    shape: 'square',
  },
  'a5-night-two': {
    file: 'sections/a5-night-two',
    alt: 'In a bare wooden room, Zuzu sits against the wall under his wide hat while a young fennec sits on the floor nearby.',
    artImageId: 244530,
    source: 'Gamebook round 8, gb8-a5-night-two-1',
    fit: 'exact',
  },
  'a5-note-burned': {
    file: 'sections/a5-note-burned',
    alt: 'A scrap of paper burns in a small iron pot hanging from a beam.',
    artImageId: 243956,
    source: 'Gamebook round 7, gb7-a5-note-burned-2',
    fit: 'exact',
    shape: 'square',
  },
  'a5-paw-print': {
    file: 'sections/a5-paw-print',
    alt: 'A small paw print is pressed into the wall of an adobe hut while two eyes glow in its dark window.',
    artImageId: 244520,
    source: 'Gamebook round 8, gb8-a5-paw-print-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-rags-burned': {
    file: 'sections/a5-rags-burned',
    alt: 'The fennec girl huddles in a doorway in a plain white dress, arms wrapped around her knees.',
    artImageId: 243936,
    source: 'Gamebook round 7, gb7-a5-rags-burned-2',
    fit: 'exact',
    shape: 'square',
  },
  'a5-rags-kept': {
    file: 'sections/a5-rags-kept',
    alt: 'Zuzu sits heavily on the sand under his wide straw hat with the small fennec girl perched at his side.',
    artImageId: 244519,
    source: 'Gamebook round 8, gb8-a5-rags-kept-1',
    fit: 'exact',
  },
  'a5-scullery': {
    file: 'sections/a5-scullery',
    alt: 'An otter nun stands in a lamplit doorway, a steaming washbasin on the floor beside her.',
    artImageId: 243926,
    source: 'Gamebook round 7, gb7-a5-scullery-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-tell-abbess': {
    file: 'sections/a5-tell-abbess',
    alt: 'An elderly otter nun reads a small folded note by candlelight at a wooden bench.',
    artImageId: 244771,
    source: 'Gamebook round 9, gb9-a5-tell-abbess-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-threshold': {
    file: 'sections/a5-threshold',
    alt: 'An otter nun kneels in a sunlit stone entry, gently washing the feet of a small fennec beside a basket of bread.',
    artImageId: 243917,
    source: 'Gamebook round 7, gb7-a5-threshold-1',
    fit: 'exact',
  },
  'a5-true-face': {
    file: 'sections/a5-true-face',
    alt: 'The otter abbess sits at a small round table across from the little fennec, a candle and a cup between them.',
    artImageId: 243922,
    source: 'Gamebook round 7, gb7-a5-true-face-2',
    fit: 'exact',
  },
  'a5-trusted-night': {
    file: 'sections/a5-trusted-night',
    alt: 'Zuzu lies awake on a rumpled blanket in a dark room, moonlight falling through the window.',
    artImageId: 244773,
    source: 'Gamebook round 9, gb9-a5-trusted-night-1',
    fit: 'exact',
  },
  'a5-vigil': {
    file: 'sections/a5-vigil',
    alt: 'A tall dark veiled shape with glowing eyes waits in a candlelit stone arch.',
    artImageId: 244778,
    source: 'Gamebook round 9, gb9-a5-vigil-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-wagon-look': {
    file: 'sections/a5-wagon-look',
    alt: 'A covered wagon in the dark, a sealed letter lying on the floorboards beneath a candle.',
    artImageId: 243985,
    source: 'Gamebook round 7, gb7-a5-wagon-look-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-wall': {
    file: 'sections/a5-wall',
    alt: 'Zuzu stands in a muddy pit at dusk, his poncho and wide straw hat dark against the hills.',
    artImageId: 244765,
    source: 'Gamebook round 9, gb9-a5-wall-1',
    fit: 'exact',
  },
  'a5-well': {
    file: 'sections/a5-well',
    alt: 'A wooden bucket of water sits on dark floorboards, a small scrap floating on its surface.',
    artImageId: 244770,
    source: 'Gamebook round 9, gb9-a5-well-2',
    fit: 'exact',
    shape: 'square',
  },
  'a5-wren-afraid': {
    file: 'sections/a5-wren-afraid',
    alt: 'A single candle burns on a stone block in a dark chapel.',
    artImageId: 244895,
    source: 'Gamebook round 9, gb9-a5-wren-afraid-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-wren-taken': {
    file: 'sections/a5-wren-taken',
    alt: 'An empty bare room with plank walls, a small figure watching through the high window.',
    artImageId: 243953,
    source: 'Gamebook round 7, gb7-a5-wren-taken-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-badger': {
    file: 'sections/a6-badger',
    alt: 'A grizzled badger bounty hunter in a long coat and hat stands beside a lamp post with a coil of rope.',
    artImageId: 244001,
    source: 'Gamebook round 7, gb7-a6-badger-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-badger-doubts': {
    file: 'sections/a6-badger-doubts',
    alt: 'A lantern hangs from a wooden post on a dark boardwalk at night.',
    artImageId: 244787,
    source: 'Gamebook round 9, gb9-a6-badger-doubts-1',
    fit: 'exact',
    shape: 'square',
  },
  'a6-badger-iron': {
    file: 'sections/a6-badger-iron',
    alt: 'A revolver lies on a wet plank beside a lit lantern in the rain.',
    artImageId: 244006,
    source: 'Gamebook round 7, gb7-a6-badger-iron-2',
    fit: 'exact',
    shape: 'square',
  },
  'a6-badger-lied': {
    file: 'sections/a6-badger-lied',
    alt: 'The badger bounty hunter walks a dark forest road in his long coat and hat.',
    artImageId: 244007,
    source: 'Gamebook round 7, gb7-a6-badger-lied-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-badger-rides': {
    file: 'sections/a6-badger-rides',
    alt: 'Under a sky full of stars, the badger bounty hunter stands on a ridge beside a small companion.',
    artImageId: 244015,
    source: 'Gamebook round 7, gb7-a6-badger-rides-1',
    fit: 'exact',
  },
  'a6-badger-spares': {
    file: 'sections/a6-badger-spares',
    alt: 'The badger bounty hunter tips his hat with one paw, a lantern in the other.',
    artImageId: 244013,
    source: 'Gamebook round 7, gb7-a6-badger-spares-1',
    fit: 'exact',
    shape: 'square',
  },
  'a6-badger-stand': {
    file: 'sections/a6-badger-stand',
    alt: 'A badger in a long dusty coat and hat stands on a night street by a hanging lantern.',
    artImageId: 244786,
    source: 'Gamebook round 9, gb9-a6-badger-stand-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-bowl-given': {
    file: 'sections/a6-bowl-given',
    alt: 'Mags sits at her lamplit bar holding a small cracked bowl in both paws.',
    artImageId: 244019,
    source: 'Gamebook round 7, gb7-a6-bowl-given-1',
    fit: 'exact',
    shape: 'square',
  },
  'a6-bowl-kept': {
    file: 'sections/a6-bowl-kept',
    alt: 'The rabbit barkeep wipes down her bar under a hanging lamp, bottles at her elbow.',
    artImageId: 244791,
    source: 'Gamebook round 9, gb9-a6-bowl-kept-1',
    fit: 'exact',
  },
  'a6-cistern': {
    file: 'sections/a6-cistern',
    alt: 'A lizard in a work apron trims a lantern on a stool in a dark plank room.',
    artImageId: 244541,
    source: 'Gamebook round 8, gb8-a6-cistern-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-coyote-roped': {
    file: 'sections/a6-coyote-roped',
    alt: 'The badger bounty hunter leads the coyote, hunched and roped, through a doorway in the lamplight.',
    artImageId: 244030,
    source: 'Gamebook round 7, gb7-a6-coyote-roped-2',
    fit: 'exact',
  },
  'a6-delivered': {
    file: 'sections/a6-delivered',
    alt: 'A top hat sits on a desk beside an ink bottle and a lit lantern.',
    artImageId: 244040,
    source: 'Gamebook round 7, gb7-a6-delivered-2',
    fit: 'exact',
    shape: 'square',
  },
  'a6-flood': {
    file: 'sections/a6-flood',
    alt: 'Water pours from a broken cistern down stone steps while a small mouse girl watches beside an older mouse.',
    artImageId: 244052,
    source: 'Gamebook round 7, gb7-a6-flood-2',
    fit: 'exact',
  },
  'a6-hask': {
    file: 'sections/a6-hask',
    alt: 'A huge boar fills a lamplit doorway, a spiked club hanging from one fist.',
    artImageId: 244795,
    source: 'Gamebook round 9, gb9-a6-hask-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-kasa': {
    file: 'sections/a6-kasa',
    alt: 'A small mouse girl in an oversized grey cardigan holds up a lantern in a plank corridor, smiling.',
    artImageId: 243999,
    source: 'Gamebook round 7, gb7-a6-kasa-1',
    fit: 'exact',
    shape: 'square',
  },
  'a6-lark': {
    file: 'sections/a6-lark',
    alt: 'The rabbit barkeep stands behind her lamplit bar among the bottles, looking up.',
    artImageId: 244897,
    source: 'Gamebook round 9, gb9-a6-lark-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-mags-cold': {
    file: 'sections/a6-mags-cold',
    alt: 'Mags stands in her long coat and red kerchief beside a lamp, her face hard.',
    artImageId: 244025,
    source: 'Gamebook round 7, gb7-a6-mags-cold-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-mags-vane': {
    file: 'sections/a6-mags-vane',
    alt: 'A battered steel bowl of water sits alone on dark floorboards.',
    artImageId: 244027,
    source: 'Gamebook round 7, gb7-a6-mags-vane-1',
    fit: 'exact',
    shape: 'square',
  },
  'a6-mob-breaks': {
    file: 'sections/a6-mob-breaks',
    alt: 'Zuzu stands in the blue night under a full moon, his zigzag poncho lit by a distant lantern.',
    artImageId: 244802,
    source: 'Gamebook round 9, gb9-a6-mob-breaks-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-mob-gather': {
    file: 'sections/a6-mob-gather',
    alt: 'Mags stands at the top of the cellar steps between two burning braziers, a torch in her hand.',
    artImageId: 244063,
    source: 'Gamebook round 7, gb7-a6-mob-gather-1',
    fit: 'exact',
  },
  'a6-mob-lead': {
    file: 'sections/a6-mob-lead',
    alt: 'Zuzu stands alone on a dark road between the hills, a fire burning beside him.',
    artImageId: 244069,
    source: 'Gamebook round 7, gb7-a6-mob-lead-1',
    fit: 'exact',
  },
  'a6-mob-slip': {
    file: 'sections/a6-mob-slip',
    alt: 'Zuzu stands alone by a small fire at the edge of a dark lake.',
    artImageId: 244071,
    source: 'Gamebook round 7, gb7-a6-mob-slip-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-pilgrim-girl': {
    file: 'sections/a6-pilgrim-girl',
    alt: "Mags sits behind her bar between two lanterns, a sealed letter before her and a small rabbit at the counter's end.",
    artImageId: 244023,
    source: 'Gamebook round 7, gb7-a6-pilgrim-girl-1',
    fit: 'exact',
  },
  'a6-riot-let': {
    file: 'sections/a6-riot-let',
    alt: 'A silver horn cap lies in the dust beside a line of footprints.',
    artImageId: 244061,
    source: 'Gamebook round 7, gb7-a6-riot-let-1',
    fit: 'exact',
    shape: 'square',
  },
  'a6-riot-pulled': {
    file: 'sections/a6-riot-pulled',
    alt: 'A pair of worn boots lies in the dust of a dark street.',
    artImageId: 244799,
    source: 'Gamebook round 9, gb9-a6-riot-pulled-1',
    fit: 'exact',
    shape: 'square',
  },
  'a6-vane': {
    file: 'sections/a6-vane',
    alt: 'Gideon Vane, a horned pronghorn in a black coat and waistcoat, sits at his lamplit desk.',
    artImageId: 244035,
    source: 'Gamebook round 7, gb7-a6-vane-1',
    fit: 'exact',
  },
  'a6-vane-bound': {
    file: 'sections/a6-vane-bound',
    alt: 'Vane sits at his desk under a hanging lamp, a written confession before him.',
    artImageId: 244044,
    source: 'Gamebook round 7, gb7-a6-vane-bound-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-vane-gun': {
    file: 'sections/a6-vane-gun',
    alt: 'Vane stands at his desk holding a revolver in both hands.',
    artImageId: 244041,
    source: 'Gamebook round 7, gb7-a6-vane-gun-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-vane-killed': {
    file: 'sections/a6-vane-killed',
    alt: 'A silver horn cap lies in a spreading pool of spilled ink on the floorboards.',
    artImageId: 244049,
    source: 'Gamebook round 7, gb7-a6-vane-killed-1',
    fit: 'exact',
    shape: 'square',
  },
  'a6-vane-refuses': {
    file: 'sections/a6-vane-refuses',
    alt: 'Vane hunches over his desk beside a lamp, a dark shape on the wall behind him.',
    artImageId: 244046,
    source: 'Gamebook round 7, gb7-a6-vane-refuses-2',
    fit: 'exact',
  },
  'a6-vane-why': {
    file: 'sections/a6-vane-why',
    alt: 'Vane leans over his desk under a lamp, hands spread on his papers.',
    artImageId: 244038,
    source: 'Gamebook round 7, gb7-a6-vane-why-2',
    fit: 'exact',
    shape: 'square',
  },
  'a6-wall': {
    file: 'sections/a6-wall',
    alt: 'Zuzu sits by a lantern beside a small mouse girl in a dress, both looking at the wall of notices.',
    artImageId: 243997,
    source: 'Gamebook round 7, gb7-a6-wall-1',
    fit: 'exact',
  },
  'a6-water-house': {
    file: 'sections/a6-water-house',
    alt: 'Two boar guards squat by the barred windows of the water house.',
    artImageId: 244031,
    source: 'Gamebook round 7, gb7-a6-water-house-1',
    fit: 'exact',
  },
  'a7-ash-knows': {
    file: 'sections/a7-ash-knows',
    alt: 'Zuzu stands by a fence on the desert road with a black crow perched on his shoulder.',
    artImageId: 244555,
    source: 'Gamebook round 8, gb8-a7-ash-knows-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a7-black-rocks': {
    file: 'sections/a7-black-rocks',
    alt: 'Zuzu stands in a stone archway under a full moon, katana on his back.',
    artImageId: 244091,
    source: 'Gamebook round 7, gb7-a7-black-rocks-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a7-cup-on-post': {
    file: 'sections/a7-cup-on-post',
    alt: 'A tin cup sits on a wooden sill beneath a moonlit window.',
    artImageId: 244110,
    source: 'Gamebook round 7, gb7-a7-cup-on-post-2',
    fit: 'exact',
    shape: 'square',
  },
  'a7-first-mile': {
    file: 'sections/a7-first-mile',
    alt: 'A straight dark road runs between bare trees toward a far rider under a pale moon.',
    artImageId: 244079,
    source: 'Gamebook round 7, gb7-a7-first-mile-1',
    fit: 'exact',
  },
  'a7-high-ground': {
    file: 'sections/a7-high-ground',
    alt: 'Zuzu crouches on a ridge at dusk, a lone stone spire rising far behind him.',
    artImageId: 244101,
    source: 'Gamebook round 7, gb7-a7-high-ground-1',
    fit: 'exact',
  },
  'a7-hollis-band': {
    file: 'sections/a7-hollis-band',
    alt: 'A grey she-jackal with long pale hair stands on the moonlit road, a knife low in her paw.',
    artImageId: 244810,
    source: 'Gamebook round 9, gb9-a7-hollis-band-2',
    fit: 'exact',
  },
  'a7-hollis-home': {
    file: 'sections/a7-hollis-home',
    alt: 'Hollis crouches in a dark wood, drawing a route in the dust beside a scrap of map.',
    artImageId: 244117,
    source: 'Gamebook round 7, gb7-a7-hollis-home-1',
    fit: 'exact',
    shape: 'square',
  },
  'a7-long-way': {
    file: 'sections/a7-long-way',
    alt: 'Zuzu stands alone on a long empty road between dark hills.',
    artImageId: 244105,
    source: 'Gamebook round 7, gb7-a7-long-way-1',
    fit: 'exact',
  },
  'a7-lost': {
    file: 'sections/a7-lost',
    alt: 'A great bare tree stands alone in a dim field, a thin path running to it.',
    artImageId: 244104,
    source: 'Gamebook round 7, gb7-a7-lost-2',
    fit: 'exact',
    shape: 'square',
  },
  'a7-road-shifts': {
    file: 'sections/a7-road-shifts',
    alt: 'A pale road curves away between bare trees under a low moon.',
    artImageId: 244090,
    source: 'Gamebook round 7, gb7-a7-road-shifts-2',
    fit: 'exact',
  },
  'a7-stumble': {
    file: 'sections/a7-stumble',
    alt: 'Zuzu stands braced in drifting dust, his poncho stirring.',
    artImageId: 244082,
    source: 'Gamebook round 7, gb7-a7-stumble-2',
    fit: 'exact',
    shape: 'square',
  },
  'a7-thin-out': {
    file: 'sections/a7-thin-out',
    alt: 'Zuzu walks a moonlit road under a full moon, stocky in his zigzag poncho and straw hat, a pale stray dog at his side.',
    artImageId: 244552,
    source: 'Gamebook round 8, gb8-a7-thin-out-1',
    fit: 'exact',
  },
  'a7-thin-voice': {
    file: 'sections/a7-thin-voice',
    alt: 'Zuzu stands on a flat rock in a dark valley under a thin crescent moon.',
    artImageId: 244095,
    source: 'Gamebook round 7, gb7-a7-thin-voice-1',
    fit: 'exact',
  },
  'a7-thin-walk': {
    file: 'sections/a7-thin-walk',
    alt: 'Zuzu walks a narrow path between tall black rocks.',
    artImageId: 244093,
    source: 'Gamebook round 7, gb7-a7-thin-walk-1',
    fit: 'exact',
    shape: 'square',
  },
  'a7-torches': {
    file: 'sections/a7-torches',
    alt: 'Zuzu stands alone by a fire in a dark valley, one paw held over the flames.',
    artImageId: 244084,
    source: 'Gamebook round 7, gb7-a7-torches-2',
    fit: 'exact',
  },
  'a7-torches-ahead': {
    file: 'sections/a7-torches-ahead',
    alt: 'Zuzu stands in a dark canyon, a lit wooden watchtower rising beside him.',
    artImageId: 244108,
    source: 'Gamebook round 7, gb7-a7-torches-ahead-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a7-torches-held': {
    file: 'sections/a7-torches-held',
    alt: 'The rabbit barkeep stands in a walled night road between burning fires, a long gun lowered at her side.',
    artImageId: 244806,
    source: 'Gamebook round 9, gb9-a7-torches-held-2',
    fit: 'exact',
  },
  'a7-torches-pass': {
    file: 'sections/a7-torches-pass',
    alt: 'Zuzu stands with head lowered on the night road, sparks drifting around his poncho.',
    artImageId: 244807,
    source: 'Gamebook round 9, gb9-a7-torches-pass-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a7-turn-back': {
    file: 'sections/a7-turn-back',
    alt: 'Zuzu stands in a stone archway framed by a huge full moon, leaning on his sheathed katana.',
    artImageId: 244100,
    source: 'Gamebook round 7, gb7-a7-turn-back-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a7-wall-in-time': {
    file: 'sections/a7-wall-in-time',
    alt: 'Zuzu crouches in a stone room beneath a tall arched window, ready to move.',
    artImageId: 244121,
    source: 'Gamebook round 7, gb7-a7-wall-in-time-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-abbess-bound': {
    file: 'sections/a8-abbess-bound',
    alt: 'The old abbess sits against the crypt wall by candlelight, smiling faintly.',
    artImageId: 244833,
    source: 'Gamebook round 9, gb9-a8-abbess-bound-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-abbess-down': {
    file: 'sections/a8-abbess-down',
    alt: 'The otter abbess kneels on the crypt floor between two candles, paws spread.',
    artImageId: 244211,
    source: 'Gamebook round 7, gb7-a8-abbess-down-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-abbess-killed': {
    file: 'sections/a8-abbess-killed',
    alt: 'A curved dagger stands beside a dripping candle on a worn stone altar.',
    artImageId: 244575,
    source: 'Gamebook round 8, gb8-a8-abbess-killed-2',
    fit: 'exact',
  },
  'a8-afraid-nun': {
    file: 'sections/a8-afraid-nun',
    alt: 'A small otter nun stares at the knife in her paw by candlelight.',
    artImageId: 244915,
    source: 'Gamebook round 9, gb9-a8-afraid-nun-1',
    fit: 'exact',
    shape: 'square',
  },
  'a8-altar-door': {
    file: 'sections/a8-altar-door',
    alt: 'A heavy wooden door stands shut between two tall candelabra.',
    artImageId: 244913,
    source: 'Gamebook round 9, gb9-a8-altar-door-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-bargain': {
    file: 'sections/a8-bargain',
    alt: 'A narrow stone passage glows with warm light at its far end, a small red cloth lying on the floor.',
    artImageId: 244840,
    source: 'Gamebook round 9, gb9-a8-bargain-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-cells': {
    file: 'sections/a8-cells',
    alt: 'An otter nun stands in a bare cell beside a candle and a stool.',
    artImageId: 244171,
    source: 'Gamebook round 7, gb7-a8-cells-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-cells-gone': {
    file: 'sections/a8-cells-gone',
    alt: 'An empty cell: a rolled bedroll, a pair of small sandals and footprints leading out.',
    artImageId: 244185,
    source: 'Gamebook round 7, gb7-a8-cells-gone-1',
    fit: 'exact',
    shape: 'square',
  },
  'a8-cells-late': {
    file: 'sections/a8-cells-late',
    alt: 'The rabbit kit stands in an open cell doorway beside a candle and a bowl.',
    artImageId: 244183,
    source: 'Gamebook round 7, gb7-a8-cells-late-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-cells-open': {
    file: 'sections/a8-cells-open',
    alt: 'A young raccoon and an older one push open a cell door into the corridor.',
    artImageId: 244177,
    source: 'Gamebook round 7, gb7-a8-cells-open-1',
    fit: 'exact',
  },
  'a8-children-run': {
    file: 'sections/a8-children-run',
    alt: 'A small porcupine child stands in a gap in the wall, pointing up at the moon in wonder.',
    artImageId: 244911,
    source: 'Gamebook round 9, gb9-a8-children-run-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-clapper': {
    file: 'sections/a8-clapper',
    alt: 'A heavy iron clapper wrapped in black cloth lies coiled with rope beside a candle.',
    artImageId: 244193,
    source: 'Gamebook round 7, gb7-a8-clapper-1',
    fit: 'exact',
  },
  'a8-coyote-gun': {
    file: 'sections/a8-coyote-gun',
    alt: 'The one-eyed coyote grips his revolver in both hands, his right forearm wrapped.',
    artImageId: 244149,
    source: 'Gamebook round 7, gb7-a8-coyote-gun-1',
    fit: 'exact',
    shape: 'square',
  },
  'a8-coyote-split': {
    file: 'sections/a8-coyote-split',
    alt: 'The one-eyed coyote crouches in a dim refectory beside an overturned bowl, head tilted, listening.',
    artImageId: 244821,
    source: 'Gamebook round 9, gb9-a8-coyote-split-1',
    fit: 'exact',
  },
  'a8-crypt': {
    file: 'sections/a8-crypt',
    alt: 'A long stone crypt lit by two wall candles leads to a dark arch where a robed shape waits.',
    artImageId: 244615,
    source: 'Gamebook round 8, gb8-a8-crypt-1',
    fit: 'exact',
  },
  'a8-crypt-lamp': {
    file: 'sections/a8-crypt-lamp',
    alt: 'A young otter nun holds a basin under a hanging lamp in a narrow stone crypt, eyes wide.',
    artImageId: 244824,
    source: 'Gamebook round 9, gb9-a8-crypt-lamp-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-fire-cellar-late': {
    file: 'sections/a8-fire-cellar-late',
    alt: 'A fire burns at the end of a dark road under a column of smoke, a small figure before it.',
    artImageId: 244170,
    source: 'Gamebook round 7, gb7-a8-fire-cellar-late-2',
    fit: 'exact',
  },
  'a8-fire-spreads': {
    file: 'sections/a8-fire-spreads',
    alt: 'Flames burst from the doorway of a dark wooden building, smoke rising into the night.',
    artImageId: 244163,
    source: 'Gamebook round 7, gb7-a8-fire-spreads-1',
    fit: 'exact',
  },
  'a8-jailer-feather': {
    file: 'sections/a8-jailer-feather',
    alt: 'A young otter nun sits in a cell in cold blue light, staring ahead.',
    artImageId: 244175,
    source: 'Gamebook round 7, gb7-a8-jailer-feather-1',
    fit: 'exact',
  },
  'a8-jailer-wakes': {
    file: 'sections/a8-jailer-wakes',
    alt: 'A young otter nun sits on a stool between racks of blades, eyes wide.',
    artImageId: 244173,
    source: 'Gamebook round 7, gb7-a8-jailer-wakes-1',
    fit: 'exact',
    shape: 'square',
  },
  'a8-kit-crypt': {
    file: 'sections/a8-kit-crypt',
    alt: "The rabbit kit stands in the crypt passage holding a smaller rabbit's paw.",
    artImageId: 244182,
    source: 'Gamebook round 7, gb7-a8-kit-crypt-2',
    fit: 'exact',
    shape: 'square',
  },
  'a8-knifepoint': {
    file: 'sections/a8-knifepoint',
    alt: 'Candle flames bend before a stone altar in an empty crypt, a strange sigil glowing on the wall.',
    artImageId: 244825,
    source: 'Gamebook round 9, gb9-a8-knifepoint-1',
    fit: 'exact',
  },
  'a8-mags-cells': {
    file: 'sections/a8-mags-cells',
    alt: 'Mags stands in a long cell passage holding up a lantern.',
    artImageId: 244162,
    source: 'Gamebook round 7, gb7-a8-mags-cells-2',
    fit: 'exact',
    shape: 'square',
  },
  'a8-mob-gate': {
    file: 'sections/a8-mob-gate',
    alt: 'A great crowd fills the yard before the mission gate, fire burning in its arch.',
    artImageId: 244155,
    source: 'Gamebook round 7, gb7-a8-mob-gate-1',
    fit: 'exact',
  },
  'a8-mob-stilled': {
    file: 'sections/a8-mob-stilled',
    alt: "Zuzu stands stocky on a rooftop at night in his zigzag poncho and straw hat, a fire burning at the roof's edge.",
    artImageId: 244563,
    source: 'Gamebook round 8, gb8-a8-mob-stilled-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-mob-waits': {
    file: 'sections/a8-mob-waits',
    alt: 'Mags walks a lantern-lit street at night with a small rabbit at her side.',
    artImageId: 244160,
    source: 'Gamebook round 7, gb7-a8-mob-waits-2',
    fit: 'exact',
  },
  'a8-raiders-wall': {
    file: 'sections/a8-raiders-wall',
    alt: 'Gaunt jackals in long coats crouch along a wall while one stands watch at an open door.',
    artImageId: 244154,
    source: 'Gamebook round 7, gb7-a8-raiders-wall-2',
    fit: 'exact',
  },
  'a8-refused': {
    file: 'sections/a8-refused',
    alt: 'A thin golden light fades in a dark arch behind an empty candlelit altar.',
    artImageId: 244838,
    source: 'Gamebook round 9, gb9-a8-refused-2',
    fit: 'exact',
  },
  'a8-sacristy': {
    file: 'sections/a8-sacristy',
    alt: 'An otter nun pushes open a sacristy door onto a room lit by a lamp, a small animal waiting by the table.',
    artImageId: 244145,
    source: 'Gamebook round 7, gb7-a8-sacristy-1',
    fit: 'exact',
  },
  'a8-sister-bites': {
    file: 'sections/a8-sister-bites',
    alt: 'The fennec girl crouches on a stone altar between candles, teeth bared.',
    artImageId: 244832,
    source: 'Gamebook round 9, gb9-a8-sister-bites-2',
    fit: 'exact',
    shape: 'square',
  },
  'a8-stair': {
    file: 'sections/a8-stair',
    alt: 'A narrow timber stair passage leads down to a closed door between two wall candles.',
    artImageId: 244141,
    source: 'Gamebook round 7, gb7-a8-stair-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-standoff': {
    file: 'sections/a8-standoff',
    alt: 'The fennec girl with bandaged wrists braces both paws on a stone altar beside a candle.',
    artImageId: 244206,
    source: 'Gamebook round 7, gb7-a8-standoff-2',
    fit: 'exact',
    shape: 'square',
  },
  'a8-standoff-break': {
    file: 'sections/a8-standoff-break',
    alt: 'A curved dagger stands upright in a candlelit stone basin beside a coil of rope.',
    artImageId: 244830,
    source: 'Gamebook round 9, gb9-a8-standoff-break-2',
    fit: 'exact',
  },
  'a8-two-blades': {
    file: 'sections/a8-two-blades',
    alt: 'The coyote stands in a narrow stair, holding back a kneeling otter nun.',
    artImageId: 244151,
    source: 'Gamebook round 7, gb7-a8-two-blades-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-voice': {
    file: 'sections/a8-voice',
    alt: 'A golden road runs straight to a lit temple house among mountains at dusk.',
    artImageId: 244217,
    source: 'Gamebook round 7, gb7-a8-voice-1',
    fit: 'exact',
  },
  'a8-voice-wound': {
    file: 'sections/a8-voice-wound',
    alt: 'Zuzu kneels in a golden-lit stone archway with a paw pressed to his shoulder.',
    artImageId: 244836,
    source: 'Gamebook round 9, gb9-a8-voice-wound-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-wall-whisper': {
    file: 'sections/a8-wall-whisper',
    alt: 'Zuzu stands in a stone niche holding a candle, listening to the wall.',
    artImageId: 244192,
    source: 'Gamebook round 7, gb7-a8-wall-whisper-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-word-broken': {
    file: 'sections/a8-word-broken',
    alt: 'The old abbess smiles in candlelight, holding a candle and a small curved dagger.',
    artImageId: 244827,
    source: 'Gamebook round 9, gb9-a8-word-broken-1',
    fit: 'exact',
    shape: 'square',
  },
  'a8-word-kept': {
    file: 'sections/a8-word-kept',
    alt: 'The fennec girl walks away down an aisle toward a candlelit altar.',
    artImageId: 244202,
    source: 'Gamebook round 7, gb7-a8-word-kept-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a8-wren-door': {
    file: 'sections/a8-wren-door',
    alt: 'The otter novice in a grey habit stands in an open doorway beside a lamp.',
    artImageId: 244144,
    source: 'Gamebook round 7, gb7-a8-wren-door-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-abbess-gone': {
    file: 'sections/a9-abbess-gone',
    alt: 'A black clawed hand reaches down toward a single candle burning in a stone basin on a crypt floor.',
    artImageId: 244293,
    source: 'Gamebook round 7, gb7-a9-abbess-gone-1',
    fit: 'exact',
    shape: 'square',
  },
  'a9-behind': {
    file: 'sections/a9-behind',
    alt: 'Zuzu stands at the top of a narrow stone stair in dawn light.',
    artImageId: 244859,
    source: 'Gamebook round 9, gb9-a9-behind-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-bury': {
    file: 'sections/a9-bury',
    alt: 'Zuzu, in his wide straw hat, stands in a dark stone archway with the fennec girl in her pale dress at his side.',
    artImageId: 244296,
    source: 'Gamebook round 7, gb7-a9-bury-2',
    fit: 'exact',
  },
  'a9-cells': {
    file: 'sections/a9-cells',
    alt: 'A low stone cellar tunnel runs off into darkness, lit only by a single candle stub on its floor.',
    artImageId: 244256,
    source: 'Gamebook round 7, gb7-a9-cells-2',
    fit: 'exact',
  },
  'a9-children': {
    file: 'sections/a9-children',
    alt: 'In a stone archway at dawn, a gangly rabbit youth holds the paw of a much smaller rabbit kit.',
    artImageId: 244263,
    source: 'Gamebook round 7, gb7-a9-children-1',
    fit: 'exact',
  },
  'a9-cistern': {
    file: 'sections/a9-cistern',
    alt: 'A padlocked stone well-head stands in a pool of black, still water under a grey sky.',
    artImageId: 244278,
    source: 'Gamebook round 7, gb7-a9-cistern-2',
    fit: 'exact',
  },
  'a9-coyote-stair': {
    file: 'sections/a9-coyote-stair',
    alt: 'The coyote climbs down a steep round stone stair toward a candle glowing below.',
    artImageId: 244846,
    source: 'Gamebook round 9, gb9-a9-coyote-stair-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-dawn-yard': {
    file: 'sections/a9-dawn-yard',
    alt: 'The fennec girl stands alone in a dark stone archway at the edge of the sand, her ears up.',
    artImageId: 244291,
    source: 'Gamebook round 7, gb7-a9-dawn-yard-1',
    fit: 'exact',
  },
  'a9-desert': {
    file: 'sections/a9-desert',
    alt: 'Zuzu stands in a narrow stone passage in his zigzag poncho and straw hat, the gate shut behind him.',
    artImageId: 244921,
    source: 'Gamebook round 9, gb9-a9-desert-1',
    fit: 'exact',
  },
  'a9-flight': {
    file: 'sections/a9-flight',
    alt: 'Two glowing eyes watch from a dark stone archway beyond a single candle.',
    artImageId: 244233,
    source: 'Gamebook round 7, gb7-a9-flight-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-forge': {
    file: 'sections/a9-forge',
    alt: 'A hammer strikes red-hot iron on a stone block, sparks bursting into the night.',
    artImageId: 244862,
    source: 'Gamebook round 9, gb9-a9-forge-2',
    fit: 'exact',
  },
  'a9-forge-crack': {
    file: 'sections/a9-forge-crack',
    alt: 'Zuzu stands in a dark doorway with the fennec girl sitting curled at his feet.',
    artImageId: 244287,
    source: 'Gamebook round 7, gb7-a9-forge-crack-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-graves': {
    file: 'sections/a9-graves',
    alt: 'Zuzu kneels in a sweep of pale sand with his katana on his back, and the fennec girl crouches close beside him.',
    artImageId: 244259,
    source: 'Gamebook round 7, gb7-a9-graves-1',
    fit: 'exact',
  },
  'a9-gun-tongue': {
    file: 'sections/a9-gun-tongue',
    alt: 'Zuzu stands in his zigzag poncho and straw hat against a dusky pink sky, rubbing his eye.',
    artImageId: 244923,
    source: 'Gamebook round 9, gb9-a9-gun-tongue-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-hang': {
    file: 'sections/a9-hang',
    alt: 'Zuzu stands stocky against a dusky pink sky in his zigzag poncho and straw hat, one paw raised.',
    artImageId: 244635,
    source: 'Gamebook round 8, gb8-a9-hang-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-hollow': {
    file: 'sections/a9-hollow',
    alt: 'Zuzu stands in a lit doorway with open paws, a flame burning above his head.',
    artImageId: 244235,
    source: 'Gamebook round 7, gb7-a9-hollow-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-kneel-blood': {
    file: 'sections/a9-kneel-blood',
    alt: 'A thin fennec girl in a grey tunic, her wrists bandaged, stands in a candlelit doorway and stares ahead with wide, wary eyes.',
    artImageId: 244247,
    source: 'Gamebook round 7, gb7-a9-kneel-blood-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-kneeling': {
    file: 'sections/a9-kneeling',
    alt: 'Four knives stand stuck in a wooden board around a small fire on the refectory floor.',
    artImageId: 244917,
    source: 'Gamebook round 9, gb9-a9-kneeling-1',
    fit: 'exact',
  },
  'a9-many': {
    file: 'sections/a9-many',
    alt: 'Zuzu trudges across pale desert sand with his katana slung low, and the fennec girl walks at his heels.',
    artImageId: 244266,
    source: 'Gamebook round 7, gb7-a9-many-2',
    fit: 'exact',
  },
  'a9-mob': {
    file: 'sections/a9-mob',
    alt: 'The rabbit barkeep walks a fenced road with a lantern as a huge dark cloud with glowing eyes rises behind her.',
    artImageId: 244850,
    source: 'Gamebook round 9, gb9-a9-mob-2',
    fit: 'exact',
  },
  'a9-only-two': {
    file: 'sections/a9-only-two',
    alt: 'A small rabbit kit walks alone down a long empty road toward a dusky horizon, a stick in his paw.',
    artImageId: 244629,
    source: 'Gamebook round 8, gb8-a9-only-two-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-river-song': {
    file: 'sections/a9-river-song',
    alt: 'The fennec girl stands with her eyes closed by a wall at sunset, humming.',
    artImageId: 244854,
    source: 'Gamebook round 9, gb9-a9-river-song-2',
    fit: 'exact',
    shape: 'square',
  },
  'a9-rope': {
    file: 'sections/a9-rope',
    alt: 'A small bell hangs on a long rope down the middle of a candlelit stone corridor.',
    artImageId: 244289,
    source: 'Gamebook round 7, gb7-a9-rope-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-sealed': {
    file: 'sections/a9-sealed',
    alt: 'Zuzu kneels in the crypt while the little fennec sits close beside him.',
    artImageId: 244232,
    source: 'Gamebook round 7, gb7-a9-sealed-2',
    fit: 'exact',
  },
  'a9-sister-knife': {
    file: 'sections/a9-sister-knife',
    alt: 'The fennec girl crouches on a candlelit stone altar with her teeth bared, while a horned shadow with glowing eyes looms behind her.',
    artImageId: 244271,
    source: 'Gamebook round 7, gb7-a9-sister-knife-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-thrown': {
    file: 'sections/a9-thrown',
    alt: 'A shadowy beast with glowing eyes looms in a crypt arch beside a guttering candle, a dagger on the floor.',
    artImageId: 244843,
    source: 'Gamebook round 9, gb9-a9-thrown-1',
    fit: 'exact',
    shape: 'square',
  },
  'a9-tower': {
    file: 'sections/a9-tower',
    alt: 'A stone arcade opens onto a desert sunset, a lone small animal crossing the sand beyond the arches.',
    artImageId: 244634,
    source: 'Gamebook round 8, gb8-a9-tower-2',
    fit: 'exact',
  },
  'a9-wall': {
    file: 'sections/a9-wall',
    alt: 'Zuzu stands in a stone alcove lit gold from within, his ear turned to the warm wall.',
    artImageId: 244851,
    source: 'Gamebook round 9, gb9-a9-wall-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-with-wren': {
    file: 'sections/a9-with-wren',
    alt: 'Zuzu kneels at a cellar doorway in a sunlit courtyard, hammer in paw.',
    artImageId: 244856,
    source: 'Gamebook round 9, gb9-a9-with-wren-2',
    fit: 'exact',
  },
  'a9-wren-ally': {
    file: 'sections/a9-wren-ally',
    alt: 'A tired otter novice in a grey habit and pale veil sits on the chapel steps at dawn with a small brass key in her paws.',
    artImageId: 244249,
    source: 'Gamebook round 7, gb7-a9-wren-ally-1',
    fit: 'exact',
    shape: 'square',
  },
  'a9-wren-cell': {
    file: 'sections/a9-wren-cell',
    alt: 'An otter novice in a black habit sits slumped against the stone wall of a narrow cell beside its heavy wooden door, her eyes lowered.',
    artImageId: 244251,
    source: 'Gamebook round 7, gb7-a9-wren-cell-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a9-wren-dorm': {
    file: 'sections/a9-wren-dorm',
    alt: 'Under a shaft of grey light, an otter novice sits alone on a wooden bench with a small orange doll in her lap and a red ball of yarn beside her.',
    artImageId: 244254,
    source: 'Gamebook round 7, gb7-a9-wren-dorm-2',
    fit: 'exact',
  },
  abbess: {
    file: 'sections/abbess',
    alt: 'Zuzu stands braced in a candlelit stone hall with his katana drawn.',
    artImageId: 244815,
    source: 'Gamebook round 9, gb9-abbess-1',
    fit: 'exact',
    shape: 'tall',
  },
  'abbess-read': {
    file: 'sections/abbess-read',
    alt: 'The otter abbess in her black habit sits at a candlelit table, smiling over a bowl of stew.',
    artImageId: 243889,
    source: 'Gamebook round 7, gb7-abbess-read-1',
    fit: 'exact',
    shape: 'square',
  },
  'abbess-strikes': {
    file: 'sections/abbess-strikes',
    alt: 'The otter abbess stands among candles, a dagger held point-down before her.',
    artImageId: 244129,
    source: 'Gamebook round 7, gb7-abbess-strikes-1',
    fit: 'exact',
    shape: 'square',
  },
  'after-supper': {
    file: 'sections/after-supper',
    alt: "A long timber corridor lit by one lamp, a nun's dark silhouette standing in the far doorway.",
    artImageId: 243892,
    source: 'Gamebook round 7, gb7-after-supper-2',
    fit: 'exact',
  },
  aftermath: {
    file: 'sections/aftermath',
    alt: 'The coyote kneels in the dust in his long coat and hat, his right arm wrapped, beside the body of the crocodile.',
    artImageId: 243588,
    source: 'Gamebook round 6, gb6-aftermath-1',
    fit: 'exact',
    shape: 'square',
  },
  'bell-tower': {
    file: 'sections/bell-tower',
    alt: 'Zuzu stands stocky in his poncho and wide straw hat on the dunes under a full moon.',
    artImageId: 244600,
    source: 'Gamebook round 8, gb8-bell-tower-1',
    fit: 'exact',
    shape: 'tall',
  },
  'bone-river': {
    file: 'sections/bone-river',
    alt: 'A huge bleached skull lies half buried in the sand of a red canyon.',
    artImageId: 243802,
    source: 'Gamebook round 6, gb6-bone-river-1',
    fit: 'exact',
  },
  'bridge-fall': {
    file: 'sections/bridge-fall',
    alt: 'Zuzu stands braced between swaying ropes in a deep canyon, dust rising around him.',
    artImageId: 243798,
    source: 'Gamebook round 6, gb6-bridge-fall-1',
    fit: 'exact',
    shape: 'tall',
  },
  'canyon-road': {
    file: 'sections/canyon-road',
    alt: 'A narrow wooden bridge stretches deep between towering red canyon walls toward a pale sun.',
    artImageId: 243797,
    source: 'Gamebook round 6, gb6-canyon-road-2',
    fit: 'exact',
  },
  caught: {
    file: 'sections/caught',
    alt: 'Zuzu crouches at a heavy door in lantern light, his poncho and straw hat lit from behind.',
    artImageId: 244757,
    source: 'Gamebook round 9, gb9-caught-1',
    fit: 'exact',
    shape: 'square',
  },
  chapel: {
    file: 'sections/chapel',
    alt: 'A plain chapel with tall windows, a bell rope hanging over an altar where something stands shrouded in white cloth.',
    artImageId: 243897,
    source: 'Gamebook round 7, gb7-chapel-1',
    fit: 'exact',
    shape: 'tall',
  },
  'cold-camp': {
    file: 'sections/cold-camp',
    alt: 'Zuzu crouches on a rock under the stars with no fire, his breath a small cloud in the cold night air.',
    artImageId: 243595,
    source: 'Gamebook round 6, gb6-cold-camp-2',
    fit: 'exact',
  },
  courtyard: {
    file: 'sections/courtyard',
    alt: 'A long adobe mission building with a small bell tower stands dark across an empty courtyard at night.',
    artImageId: 243893,
    source: 'Gamebook round 7, gb7-courtyard-1',
    fit: 'exact',
  },
  coyote: {
    file: 'sections/coyote',
    alt: 'The one-eyed coyote kneels on the desert shore at sunset, a battered canteen at his feet.',
    artImageId: 244695,
    source: 'Gamebook round 9, gb9-coyote-2',
    fit: 'exact',
  },
  'croc-ready': {
    file: 'sections/croc-ready',
    alt: 'Zuzu stands his ground in his zigzag poncho and straw hat, katana raised over his shoulder.',
    artImageId: 244686,
    source: 'Gamebook round 8, gb8h-croc-ready-1',
    fit: 'exact',
    shape: 'tall',
  },
  crocodile: {
    file: 'sections/crocodile',
    alt: 'A crocodile glides through a round stone-ringed pool, only its head and ridged back above the water.',
    artImageId: 244877,
    source: 'Gamebook round 9, gb9-crocodile-1',
    fit: 'exact',
  },
  'crypt-glimpse': {
    file: 'sections/crypt-glimpse',
    alt: 'A vaulted stone crypt, a dark coiled shape carved or shadowed in the wall behind the altar.',
    artImageId: 243907,
    source: 'Gamebook round 7, gb7-crypt-glimpse-1',
    fit: 'exact',
  },
  dormitory: {
    file: 'sections/dormitory',
    alt: 'The fennec girl lies asleep on the floor of a bare room beside a single candle.',
    artImageId: 243902,
    source: 'Gamebook round 7, gb7-dormitory-2',
    fit: 'exact',
  },
  'dust-road': {
    file: 'sections/dust-road',
    alt: 'A twisted bare tree leans over a dirt track climbing toward a small shrine on a ridge under a purple dusk sky.',
    artImageId: 243592,
    source: 'Gamebook round 6, gb6-dust-road-1',
    fit: 'exact',
    shape: 'tall',
  },
  'ending-alone': {
    file: 'sections/ending-alone',
    alt: 'Zuzu walks alone toward the viewer down an empty desert road between dark ridges, his long shadow behind him.',
    artImageId: 244298,
    source: 'Gamebook round 7, gb7-ending-alone-2',
    fit: 'exact',
  },
  'ending-altar': {
    file: 'sections/ending-altar',
    alt: 'A lone stone gate stands in the desert at dusk with a small bell hanging in its arch and a dark shape at its foot.',
    artImageId: 244639,
    source: 'Gamebook round 8, gb8-ending-altar-1',
    fit: 'exact',
    shape: 'tall',
  },
  'ending-ashes': {
    file: 'sections/ending-ashes',
    alt: 'A blackened mission tower stands in a dark crater, fire glowing through its arch and smoke rolling into an orange sky.',
    artImageId: 244645,
    source: 'Gamebook round 8, gb8-ending-ashes-2',
    fit: 'exact',
  },
  'ending-bargain': {
    file: 'sections/ending-bargain',
    alt: 'Zuzu stands stocky in a lantern-lit wooden doorway in his zigzag poncho and wide straw hat.',
    artImageId: 244643,
    source: 'Gamebook round 8, gb8-ending-bargain-1',
    fit: 'exact',
    shape: 'square',
  },
  'ending-bell': {
    file: 'sections/ending-bell',
    alt: 'In a dusty tower room, Zuzu in a wide red hat holds a short rope while a small fox kit tumbles at his feet.',
    artImageId: 244315,
    source: 'Gamebook round 7, gb7-ending-bell-1',
    fit: 'exact',
    shape: 'tall',
  },
  'ending-coyote-road': {
    file: 'sections/ending-coyote-road',
    alt: 'Zuzu stands in a dark stone doorway in his wide straw hat, a trail of footprints leading away across the floor.',
    artImageId: 244319,
    source: 'Gamebook round 7, gb7-ending-coyote-road-1',
    fit: 'exact',
    shape: 'tall',
  },
  'ending-four': {
    file: 'sections/ending-four',
    alt: 'By a small fire under the night sky, Zuzu sits cross-legged in his poncho and wide hat with a little fennec tucked in his lap.',
    artImageId: 244307,
    source: 'Gamebook round 7, gb7-ending-four-1',
    fit: 'exact',
  },
  'ending-hollow-saint': {
    file: 'sections/ending-hollow-saint',
    alt: 'The fennec girl sits awake by a campfire at night, a knife across her knees.',
    artImageId: 244868,
    source: 'Gamebook round 9, gb9-ending-hollow-saint-2',
    fit: 'exact',
  },
  'ending-hunted': {
    file: 'sections/ending-hunted',
    alt: 'In the mouth of a red rock tunnel, Zuzu lies curled in the sand beside the fennec girl.',
    artImageId: 244304,
    source: 'Gamebook round 7, gb7-ending-hunted-2',
    fit: 'exact',
    shape: 'square',
  },
  'ending-seal': {
    file: 'sections/ending-seal',
    alt: 'Zuzu kneels spent in the dust at dawn, his zigzag poncho streaked with soot.',
    artImageId: 244865,
    source: 'Gamebook round 9, gb9-ending-seal-1',
    fit: 'exact',
    shape: 'tall',
  },
  'ending-warning': {
    file: 'sections/ending-warning',
    alt: 'A lamplit wooden jailhouse corridor runs between barred cells to a small shuttered window.',
    artImageId: 244299,
    source: 'Gamebook round 7, gb7-ending-warning-1',
    fit: 'exact',
  },
  'hb-dead': {
    file: 'sections/hb-dead',
    alt: 'Zuzu kneels alone in the ash of a burned-out street between leaning wooden buildings.',
    artImageId: 244423,
    source: 'Gamebook round 8, gb8-hb-dead-1',
    fit: 'exact',
    shape: 'tall',
  },
  'hb-notices': {
    file: 'sections/hb-notices',
    alt: "A faded poster of a long-eared animal's face is nailed to a scorched brick wall.",
    artImageId: 244425,
    source: 'Gamebook round 8, gb8-hb-notices-2',
    fit: 'exact',
    shape: 'square',
  },
  'hb-store-empty': {
    file: 'sections/hb-store-empty',
    alt: 'A dim, empty general store: bare shelves, a long wooden counter and dust hanging in the light from one window.',
    artImageId: 243659,
    source: 'Gamebook round 6, gb6-hb-store-empty-1',
    fit: 'exact',
  },
  'hb-store-find': {
    file: 'sections/hb-store-find',
    alt: 'A shallow wooden box packed with clean white linen sits on a scuffed store counter.',
    artImageId: 243658,
    source: 'Gamebook round 6, gb6-hb-store-find-2',
    fit: 'exact',
    shape: 'square',
  },
  'hidden-pool': {
    file: 'sections/hidden-pool',
    alt: 'Zuzu stands on a rock ledge above a dark pool, looking down at the still water.',
    artImageId: 244407,
    source: 'Gamebook round 8, gb8-hidden-pool-1',
    fit: 'exact',
    shape: 'tall',
  },
  'hollow-bell': {
    file: 'sections/hollow-bell',
    alt: 'Zuzu stands in a stone gateway with fire roaring behind him, paper notices pinned to the wall on either side.',
    artImageId: 243651,
    source: 'Gamebook round 6, gb6-hollow-bell-1',
    fit: 'exact',
  },
  'last-breath': {
    file: 'sections/last-breath',
    alt: 'Zuzu stands on cracked flagstones beside a single guttering candle.',
    artImageId: 244135,
    source: 'Gamebook round 7, gb7-last-breath-1',
    fit: 'exact',
    shape: 'tall',
  },
  'locked-door': {
    file: 'sections/locked-door',
    alt: 'A dark doorway stands ajar, two glowing eyes watching from the blackness inside.',
    artImageId: 243903,
    source: 'Gamebook round 7, gb7-locked-door-1',
    fit: 'exact',
    shape: 'tall',
  },
  'lost-them': {
    file: 'sections/lost-them',
    alt: 'Zuzu stands alone on a road between dark rocks under a full moon.',
    artImageId: 243730,
    source: 'Gamebook round 6, gb6-lost-them-2',
    fit: 'exact',
    shape: 'tall',
  },
  mission: {
    file: 'sections/mission',
    alt: "Zuzu stands in the shadow of the mission gate's iron arch in the hot afternoon light.",
    artImageId: 244762,
    source: 'Gamebook round 9, gb9-mission-2',
    fit: 'exact',
  },
  'mission-gate': {
    file: 'sections/mission-gate',
    alt: 'A black-robed nun stands in an open doorway at dusk holding a lantern low.',
    artImageId: 244753,
    source: 'Gamebook round 9, gb9-mission-gate-1',
    fit: 'exact',
    shape: 'tall',
  },
  'mission-night': {
    file: 'sections/mission-night',
    alt: 'A loaf of bread and an overturned bowl lie on the floor of a dark candlelit refectory.',
    artImageId: 244905,
    source: 'Gamebook round 9, gb9-mission-night-1',
    fit: 'exact',
  },
  morning: {
    file: 'sections/morning',
    alt: 'The fennec girl stands in a dark doorway looking out into the pink morning light.',
    artImageId: 244760,
    source: 'Gamebook round 9, gb9-morning-2',
    fit: 'exact',
    shape: 'tall',
  },
  'night-flight': {
    file: 'sections/night-flight',
    alt: 'A dark stone hall leads to a tall moonlit window, small footprints on the floor.',
    artImageId: 244763,
    source: 'Gamebook round 9, gb9-night-flight-1',
    fit: 'exact',
    shape: 'tall',
  },
  'night-watch': {
    file: 'sections/night-watch',
    alt: 'A tall hooded figure with no face stands in the dark behind a single burning candle.',
    artImageId: 243733,
    source: 'Gamebook round 6, gb6-night-watch-1',
    fit: 'exact',
    shape: 'tall',
  },
  parting: {
    file: 'sections/parting',
    alt: 'Zuzu walks away across the desert flat at dusk, his katana across his back.',
    artImageId: 244876,
    source: 'Gamebook round 9, gb9-parting-2',
    fit: 'exact',
  },
  posters: {
    file: 'sections/posters',
    alt: 'A long dim boardwalk under a roof, paper notices pinned on the plank walls.',
    artImageId: 243991,
    source: 'Gamebook round 7, gb7-posters-1',
    fit: 'exact',
  },
  relic: {
    file: 'sections/relic',
    alt: 'A huge bleached skull lies half-buried in the desert at sunset, small footprints stopping before it.',
    artImageId: 244890,
    source: 'Gamebook round 9, gb9-relic-2',
    fit: 'exact',
  },
  rescue: {
    file: 'sections/rescue',
    alt: 'A single candle burns before a dark open arch in the crypt wall.',
    artImageId: 244842,
    source: 'Gamebook round 9, gb9-rescue-2',
    fit: 'exact',
  },
  'rescue-quiet': {
    file: 'sections/rescue-quiet',
    alt: 'Zuzu stands at the top of the altar steps between iron candelabra, his katana at his side.',
    artImageId: 244819,
    source: 'Gamebook round 9, gb9-rescue-quiet-1',
    fit: 'exact',
  },
  'run-back': {
    file: 'sections/run-back',
    alt: 'Zuzu stands on the road at the foot of a tall stone tower lit at its top.',
    artImageId: 244073,
    source: 'Gamebook round 7, gb7-run-back-1',
    fit: 'exact',
  },
  'run-late': {
    file: 'sections/run-late',
    alt: 'Zuzu crouches in a narrow stone gap under the full moon, catching his breath.',
    artImageId: 244076,
    source: 'Gamebook round 7, gb7-run-late-2',
    fit: 'exact',
    shape: 'tall',
  },
  saloon: {
    file: 'sections/saloon',
    alt: 'A rabbit barkeep with a red kerchief and dark vest stands behind her bar, bottles on the shelves.',
    artImageId: 243993,
    source: 'Gamebook round 7, gb7-saloon-1',
    fit: 'exact',
    shape: 'tall',
  },
  'saloon-truth': {
    file: 'sections/saloon-truth',
    alt: 'The rabbit barkeep leans her arms on the bar under a lamp, her eyes wet.',
    artImageId: 243996,
    source: 'Gamebook round 7, gb7-saloon-truth-2',
    fit: 'exact',
    shape: 'square',
  },
  'sister-trust': {
    file: 'sections/sister-trust',
    alt: 'Zuzu sits cross-legged in the ash, his wide hat shading his eyes, as a small fennec settles in close in front of him.',
    artImageId: 243663,
    source: 'Gamebook round 6, gb6-sister-trust-1',
    fit: 'exact',
    shape: 'tall',
  },
  stabbed: {
    file: 'sections/stabbed',
    alt: 'Zuzu stands in a candlelit crypt between two candelabra, one paw pressed to his side.',
    artImageId: 244131,
    source: 'Gamebook round 7, gb7-stabbed-1',
    fit: 'exact',
  },
  standoff: {
    file: 'sections/standoff',
    alt: 'The one-eyed coyote kneels in dark water under a shaft of light, his hand resting near his revolver.',
    artImageId: 243579,
    source: 'Gamebook round 6, gb6-standoff-2',
    fit: 'exact',
    shape: 'square',
  },
  survivors: {
    file: 'sections/survivors',
    alt: 'A fennec girl with fierce orange eyes crouches on a burned boardwalk, clutching her little brother.',
    artImageId: 243661,
    source: 'Gamebook round 6, gb6-survivors-1',
    fit: 'exact',
  },
  'take-them': {
    file: 'sections/take-them',
    alt: 'An otter nun stands with folded paws before a barred iron gate.',
    artImageId: 243912,
    source: 'Gamebook round 7, gb7-take-them-2',
    fit: 'exact',
    shape: 'tall',
  },
  'the-crossing': {
    file: 'sections/the-crossing',
    alt: 'Zuzu stands on a grey rocky bank above a canyon stream, his poncho drawn about him and his katana at his back.',
    artImageId: 244406,
    source: 'Gamebook round 8, gb8-the-crossing-1',
    fit: 'exact',
  },
  'they-follow': {
    file: 'sections/they-follow',
    alt: 'Zuzu walks a desert road at sunset, a small fennec trailing a few steps behind him.',
    artImageId: 243728,
    source: 'Gamebook round 6, gb6-they-follow-2',
    fit: 'exact',
  },
  tracks: {
    file: 'sections/tracks',
    alt: 'A tall iron gate stands shut under a stone arch, small footprints leading in and none coming out.',
    artImageId: 243896,
    source: 'Gamebook round 7, gb7-tracks-2',
    fit: 'exact',
    shape: 'square',
  },
  'two-fires': {
    file: 'sections/two-fires',
    alt: 'Zuzu sits on a rock beside a campfire on the open desert at night.',
    artImageId: 243732,
    source: 'Gamebook round 6, gb6-two-fires-2',
    fit: 'exact',
  },
  wagon: {
    file: 'sections/wagon',
    alt: 'An abandoned covered wagon stands on a desert road, a vulture perched on its roof.',
    artImageId: 243854,
    source: 'Gamebook round 6, gb6-wagon-1',
    fit: 'exact',
  },
  'wagon-find': {
    file: 'sections/wagon-find',
    alt: "Several pairs of small worn boots and an iron ring lie on the floorboards beside the wagon's side.",
    artImageId: 243856,
    source: 'Gamebook round 6, gb6-wagon-find-1',
    fit: 'exact',
    shape: 'square',
  },
}
