/*
 * One plate per section (Silas, 2026-10-10: "if we have 400 sections, we have 400 pieces of art").
 * Keyed by section id, separate from PLATES because many section ids (dust-road, hollow-bell, coyote...) are also
 * shared plate keys. Files live in public/zuzu-gamebook/scenes/sections/<id>.webp. Each render is reviewed in
 * conductor projects/zuzu-gamebook/art/ROUND-6.yaml / ROUND-7.yaml before it lands here; a section without an
 * entry shows its shared plate (art.ts sectionPlate()).
 */
import type { ScenePlate } from './art'

export const SECTION_PLATES: Record<string, ScenePlate> = {
  'a1-bowl-night': {
    file: 'sections/a1-bowl-night',
    alt: 'A cracked grey stone bowl holding a little dark water sits alone on bare ground at night.',
    artImageId: 243649,
    source: 'Gamebook round 6, gb6-a1-bowl-night-1',
    fit: 'exact',
    shape: 'square',
  },
  'a1-downwind-fail': {
    file: 'sections/a1-downwind-fail',
    alt: "The one-eyed coyote in a long coat and wide hat stands among black reeds at the water's edge under a pale moon.",
    artImageId: 243614,
    source: 'Gamebook round 6, gb6-a1-downwind-fail-2',
    fit: 'exact',
    shape: 'square',
  },
  'a1-eggs-eaten': {
    file: 'sections/a1-eggs-eaten',
    alt: 'A broken pale shell lies open on a stone slab beside a rust-brown cloth, shell fragments scattered around it.',
    artImageId: 243635,
    source: 'Gamebook round 6, gb6-a1-eggs-eaten-1',
    fit: 'exact',
    shape: 'square',
  },
  'a1-far-bank': {
    file: 'sections/a1-far-bank',
    alt: 'Zuzu, a short grey koala in a rust-brown poncho, orange sash and wide hat, stands alone on a red rock in the desert.',
    artImageId: 243643,
    source: 'Gamebook round 6, gb6-a1-far-bank-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-gun-drowned': {
    file: 'sections/a1-gun-drowned',
    alt: 'A tall black rock is mirrored in a still pool among dark reeds, rings spreading where something has just sunk.',
    artImageId: 243631,
    source: 'Gamebook round 6, gb6-a1-gun-drowned-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-gun-returned': {
    file: 'sections/a1-gun-returned',
    alt: 'The coyote stands in the desert in his long coat, revolver in his left hand, his right forearm wrapped in cloth.',
    artImageId: 243628,
    source: 'Gamebook round 6, gb6-a1-gun-returned-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-nest': {
    file: 'sections/a1-nest',
    alt: 'A single pale leathery egg rests in a hollow of sand among dry reeds on a flat riverbank.',
    artImageId: 243634,
    source: 'Gamebook round 6, gb6-a1-nest-2',
    fit: 'exact',
  },
  'a1-on-the-stones': {
    file: 'sections/a1-on-the-stones',
    alt: 'Zuzu stands alone on a black stone at the edge of dark water, katana on his back, braced and watchful.',
    artImageId: 243617,
    source: 'Gamebook round 6, gb6-a1-on-the-stones-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a1-stones-watch': {
    file: 'sections/a1-stones-watch',
    alt: 'The one-eyed coyote stands knee-deep in a dark pool among red rocks, rings spreading around him, one paw near his revolver.',
    artImageId: 243607,
    source: 'Gamebook round 6, gb6-a1-stones-watch-1',
    fit: 'exact',
  },
  'a1-the-shot': {
    file: 'sections/a1-the-shot',
    alt: 'The coyote fires his revolver from one knee as a great crocodile surges out of the water beside him.',
    artImageId: 243624,
    source: 'Gamebook round 6, gb6-a1-the-shot-2',
    fit: 'exact',
  },
  'a2-badger': {
    file: 'sections/a2-badger',
    alt: 'An old badger shopkeeper in a white shirt and orange apron sits slumped in a doorway between flour sacks.',
    artImageId: 243667,
    source: 'Gamebook round 6, gb6-a2-badger-1',
    fit: 'exact',
  },
  'a2-badger-dies': {
    file: 'sections/a2-badger-dies',
    alt: 'A pair of round spectacles and a few brass shell casings lie on a dusty wooden counter.',
    artImageId: 243676,
    source: 'Gamebook round 6, gb6-a2-badger-dies-2',
    fit: 'exact',
    shape: 'square',
  },
  'a2-gift': {
    file: 'sections/a2-gift',
    alt: "A raccoon's masked face is carved into a weathered wooden post at the edge of the desert.",
    artImageId: 243725,
    source: 'Gamebook round 6, gb6-a2-gift-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-linen': {
    file: 'sections/a2-linen',
    alt: 'A folded grey cloth lies on dark floorboards in a shaft of light.',
    artImageId: 243689,
    source: 'Gamebook round 6, gb6-a2-linen-1',
    fit: 'exact',
    shape: 'square',
  },
  'a2-looter': {
    file: 'sections/a2-looter',
    alt: 'A young raccoon in a vest and a long cloak kneels in a burned street holding a knife, a pair of boots beside him.',
    artImageId: 243677,
    source: 'Gamebook round 6, gb6-a2-looter-1',
    fit: 'exact',
  },
  'a2-looter-broken': {
    file: 'sections/a2-looter-broken',
    alt: 'A kitchen knife lies dropped in grey ash, small footprints leading away from it.',
    artImageId: 243682,
    source: 'Gamebook round 6, gb6-a2-looter-broken-2',
    fit: 'exact',
    shape: 'square',
  },
  'a2-looter-shamed': {
    file: 'sections/a2-looter-shamed',
    alt: 'Zuzu kneels in a ruined doorway, paws on his knees, a pair of worn boots set down beside him.',
    artImageId: 243683,
    source: 'Gamebook round 6, gb6-a2-looter-shamed-1',
    fit: 'exact',
  },
  'a2-looter-spared': {
    file: 'sections/a2-looter-spared',
    alt: 'A young raccoon in a vest walks out through a town archway at dusk, smoke rising over the roofs behind him.',
    artImageId: 243685,
    source: 'Gamebook round 6, gb6-a2-looter-spared-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-noon': {
    file: 'sections/a2-noon',
    alt: 'An empty alley between wooden buildings at noon, a broom leaning on a wall and a bell tower beyond.',
    artImageId: 243705,
    source: 'Gamebook round 6, gb6-a2-noon-1',
    fit: 'exact',
  },
  'a2-sister-snarl': {
    file: 'sections/a2-sister-snarl',
    alt: 'The fennec girl clutches her bandaged paws to her chest and bares her teeth, ears flat with fury.',
    artImageId: 243718,
    source: 'Gamebook round 6, gb6-a2-sister-snarl-2',
    fit: 'exact',
    shape: 'square',
  },
  'a2-sister-wall': {
    file: 'sections/a2-sister-wall',
    alt: 'The fennec girl stands alone against a wall of planks, wrists bandaged, ears up and wary.',
    artImageId: 243714,
    source: 'Gamebook round 6, gb6-a2-sister-wall-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-sister-water': {
    file: 'sections/a2-sister-water',
    alt: 'Zuzu crouches to set a small water bottle on the ground while a little fennec watches from across the floor.',
    artImageId: 243716,
    source: 'Gamebook round 6, gb6-a2-sister-water-2',
    fit: 'exact',
  },
  'a2-song': {
    file: 'sections/a2-song',
    alt: 'Zuzu stands bareheaded in a smoky street at dusk, a tall wooden bell tower rising behind him.',
    artImageId: 243665,
    source: 'Gamebook round 6, gb6-a2-song-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-tower': {
    file: 'sections/a2-tower',
    alt: 'Zuzu stands at the top of wooden steps in the evening, a lookout tower and pines behind him.',
    artImageId: 243720,
    source: 'Gamebook round 6, gb6-a2-tower-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-tower-fall': {
    file: 'sections/a2-tower-fall',
    alt: 'Zuzu stands in a dim timber stairwell, light falling on him from above.',
    artImageId: 243721,
    source: 'Gamebook round 6, gb6-a2-tower-fall-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-tracks': {
    file: 'sections/a2-tracks',
    alt: 'A pair of worn boots stands in a wooden tub among scattered brass shell casings.',
    artImageId: 243707,
    source: 'Gamebook round 6, gb6-a2-tracks-1',
    fit: 'exact',
    shape: 'square',
  },
  'a2-vigil': {
    file: 'sections/a2-vigil',
    alt: 'Zuzu sits bareheaded by a small fire beneath the bell tower at night, the bell hanging above him.',
    artImageId: 243696,
    source: 'Gamebook round 6, gb6-a2-vigil-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a2-walk-away': {
    file: 'sections/a2-walk-away',
    alt: 'An empty road runs through the dark toward a lone wooden tower with a lamp lit at its top.',
    artImageId: 243694,
    source: 'Gamebook round 6, gb6-a2-walk-away-2',
    fit: 'exact',
  },
  'a3-apple-days': {
    file: 'sections/a3-apple-days',
    alt: 'A small campfire burns in a hollow ringed by dry brush at night.',
    artImageId: 243758,
    source: 'Gamebook round 6, gb6-a3-apple-days-1',
    fit: 'exact',
  },
  'a3-candle-watch': {
    file: 'sections/a3-candle-watch',
    alt: 'A black candle drips wax across cracked stone, its smoke curling upward like a question mark.',
    artImageId: 243793,
    source: 'Gamebook round 6, gb6-a3-candle-watch-2',
    fit: 'exact',
    shape: 'square',
  },
  'a3-cold-dawn': {
    file: 'sections/a3-cold-dawn',
    alt: 'The fennec girl crouches by a small fire at dawn, poking it with a stick.',
    artImageId: 243742,
    source: 'Gamebook round 6, gb6-a3-cold-dawn-1',
    fit: 'exact',
  },
  'a3-fever': {
    file: 'sections/a3-fever',
    alt: 'The fennec girl stands alone in the dark with her wrists bandaged, ears drooping with worry.',
    artImageId: 243772,
    source: 'Gamebook round 6, gb6-a3-fever-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-first-day': {
    file: 'sections/a3-first-day',
    alt: 'Zuzu stands under a bare tree on a pale plain while a small fennec sits watching him from a distance.',
    artImageId: 243735,
    source: 'Gamebook round 6, gb6-a3-first-day-1',
    fit: 'exact',
  },
  'a3-going-back': {
    file: 'sections/a3-going-back',
    alt: 'The fennec girl sits alone on a rock under a huge full moon, ears up, watching the dark.',
    artImageId: 243881,
    source: 'Gamebook round 6, gb6-a3-going-back-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-hard-pace': {
    file: 'sections/a3-hard-pace',
    alt: 'The fennec girl walks a pale dune at dusk, carrying her little brother against her chest.',
    artImageId: 243741,
    source: 'Gamebook round 6, gb6-a3-hard-pace-1',
    fit: 'exact',
  },
  'a3-hollow-stone': {
    file: 'sections/a3-hollow-stone',
    alt: 'A flat-topped stone with a shallow hollow sits alone on bare ground in slanting light.',
    artImageId: 243739,
    source: 'Gamebook round 6, gb6-a3-hollow-stone-1',
    fit: 'exact',
    shape: 'square',
  },
  'a3-one-fire': {
    file: 'sections/a3-one-fire',
    alt: 'A koala and the fennec girl sit together at one small fire at the foot of a canyon.',
    artImageId: 243786,
    source: 'Gamebook round 6, gb6-a3-one-fire-1',
    fit: 'exact',
  },
  'a3-salt-pan': {
    file: 'sections/a3-salt-pan',
    alt: 'The fennec girl kneels on a white salt flat, her paws clasped, enormous ears spread.',
    artImageId: 243750,
    source: 'Gamebook round 6, gb6-a3-salt-pan-1',
    fit: 'exact',
  },
  'a3-salt-refused': {
    file: 'sections/a3-salt-refused',
    alt: 'The fennec girl stands her ground on a ridge of salt, scowling, with her fists at her sides.',
    artImageId: 243756,
    source: 'Gamebook round 6, gb6-a3-salt-refused-1',
    fit: 'exact',
    shape: 'square',
  },
  'a3-sandal-tracks': {
    file: 'sections/a3-sandal-tracks',
    alt: 'A black candle burns on cracked ground, a thin thread of smoke rising from it.',
    artImageId: 243744,
    source: 'Gamebook round 6, gb6-a3-sandal-tracks-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-search-dark': {
    file: 'sections/a3-search-dark',
    alt: 'The fennec girl stands alone in a dark rocky hollow, looking out with wide eyes.',
    artImageId: 243764,
    source: 'Gamebook round 6, gb6-a3-search-dark-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a3-search-dawn': {
    file: 'sections/a3-search-dawn',
    alt: 'The fennec girl lies asleep on the bare ground of the desert at dawn, curled on her side.',
    artImageId: 243767,
    source: 'Gamebook round 6, gb6-a3-search-dawn-2',
    fit: 'exact',
  },
  'a3-shade': {
    file: 'sections/a3-shade',
    alt: 'The fennec girl sits at the foot of a dead tree holding her little brother in her lap.',
    artImageId: 243737,
    source: 'Gamebook round 6, gb6-a3-shade-1',
    fit: 'exact',
    shape: 'square',
  },
  'a3-theft-kept': {
    file: 'sections/a3-theft-kept',
    alt: 'The fennec girl sits on a rock beside a small fire, holding something close against her chest.',
    artImageId: 243769,
    source: 'Gamebook round 6, gb6-a3-theft-kept-2',
    fit: 'exact',
    shape: 'square',
  },
  'a3-tracks-lost': {
    file: 'sections/a3-tracks-lost',
    alt: 'Zuzu stands small on a desert road at sunset, red cliffs rising behind him.',
    artImageId: 243748,
    source: 'Gamebook round 6, gb6-a3-tracks-lost-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-canyon-floor': {
    file: 'sections/a4-canyon-floor',
    alt: 'Zuzu walks the canyon floor beside the fennec girl and her little brother, high walls glowing above them.',
    artImageId: 243800,
    source: 'Gamebook round 6, gb6-a4-canyon-floor-1',
    fit: 'exact',
  },
  'a4-dry-well': {
    file: 'sections/a4-dry-well',
    alt: 'A grey she-jackal in a white shirt crouches among dark rocks beside a battered bowl.',
    artImageId: 243816,
    source: 'Gamebook round 6, gb6-a4-dry-well-1',
    fit: 'exact',
  },
  'a4-face-listen': {
    file: 'sections/a4-face-listen',
    alt: 'Zuzu stands still in drifting dust, katana on his back, head tilted as if listening.',
    artImageId: 243809,
    source: 'Gamebook round 6, gb6-a4-face-listen-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-feather-look': {
    file: 'sections/a4-feather-look',
    alt: 'Two fennec children stand side by side on a pale dune, looking at each other.',
    artImageId: 243867,
    source: 'Gamebook round 6, gb6-a4-feather-look-2',
    fit: 'exact',
  },
  'a4-hollis-why': {
    file: 'sections/a4-hollis-why',
    alt: 'A gaunt she-jackal in a patched shirt stands in a stone archway with a knife in her hand.',
    artImageId: 243824,
    source: 'Gamebook round 6, gb6-a4-hollis-why-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-peddler-exposed': {
    file: 'sections/a4-peddler-exposed',
    alt: 'An old prairie-dog woman in a long dress pours water from a jar onto the ground, a pup at her feet.',
    artImageId: 243849,
    source: 'Gamebook round 6, gb6-a4-peddler-exposed-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-peddler-paid': {
    file: 'sections/a4-peddler-paid',
    alt: 'A hare in a dark coat sits cross-legged by a small fire beside a glass jar, a young animal across from him.',
    artImageId: 243853,
    source: 'Gamebook round 6, gb6-a4-peddler-paid-2',
    fit: 'exact',
  },
  'a4-peddler-silent': {
    file: 'sections/a4-peddler-silent',
    alt: 'A weary prairie dog sits wrapped in a shawl against a wall, holding a small jar of water.',
    artImageId: 243850,
    source: 'Gamebook round 6, gb6-a4-peddler-silent-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-raider-kits': {
    file: 'sections/a4-raider-kits',
    alt: 'A small jackal kit in a grey wrap clutches a red cup, looking up with wide frightened eyes.',
    artImageId: 243838,
    source: 'Gamebook round 6, gb6-a4-raider-kits-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-shrine': {
    file: 'sections/a4-shrine',
    alt: 'A long empty stone corridor leads to a closed door with light behind it.',
    artImageId: 243872,
    source: 'Gamebook round 6, gb6-a4-shrine-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-shrine-watch': {
    file: 'sections/a4-shrine-watch',
    alt: 'A hooded figure with no face walks out of a dark archway between two burning candles.',
    artImageId: 243876,
    source: 'Gamebook round 6, gb6-a4-shrine-watch-1',
    fit: 'exact',
  },
  'a4-waystation': {
    file: 'sections/a4-waystation',
    alt: 'A tall hare in a long black coat stands at a desert waystation holding a jar of water beside a smaller hare.',
    artImageId: 243847,
    source: 'Gamebook round 6, gb6-a4-waystation-2',
    fit: 'exact',
  },
  'a4-well-paid': {
    file: 'sections/a4-well-paid',
    alt: 'A gaunt she-jackal in a long red cloak stands in a stone doorway beside a cooking pot.',
    artImageId: 243834,
    source: 'Gamebook round 6, gb6-a4-well-paid-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-well-scout': {
    file: 'sections/a4-well-scout',
    alt: 'A young raccoon in a long coat leaps down a rocky slope, kicking up dust.',
    artImageId: 243818,
    source: 'Gamebook round 6, gb6-a4-well-scout-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-well-vouched': {
    file: 'sections/a4-well-vouched',
    alt: 'A coil of rope lies beside a small wooden bucket lid on the dusty ground.',
    artImageId: 243820,
    source: 'Gamebook round 6, gb6-a4-well-vouched-1',
    fit: 'exact',
    shape: 'square',
  },
  'a4-well-won': {
    file: 'sections/a4-well-won',
    alt: 'A grey she-jackal kneels on the stones by the well, her knife lowered to the ground.',
    artImageId: 243831,
    source: 'Gamebook round 6, gb6-a4-well-won-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a4-witch-blood': {
    file: 'sections/a4-witch-blood',
    alt: 'A single long black feather lies across a bare branch.',
    artImageId: 243862,
    source: 'Gamebook round 6, gb6-a4-witch-blood-1',
    fit: 'exact',
    shape: 'square',
  },
  'a4-witch-memory': {
    file: 'sections/a4-witch-memory',
    alt: 'A wooden temple house with a curved roof stands alone in a valley ringed by mountains.',
    artImageId: 243860,
    source: 'Gamebook round 6, gb6-a4-witch-memory-1',
    fit: 'exact',
  },
  'a4-witch-refused': {
    file: 'sections/a4-witch-refused',
    alt: 'Zuzu stands alone beneath a huge dead tree at dusk, hands at his sides.',
    artImageId: 243864,
    source: 'Gamebook round 6, gb6-a4-witch-refused-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-commission': {
    file: 'sections/a5-commission',
    alt: 'The otter abbess pours water from a jug at a desk in a book-lined study.',
    artImageId: 243941,
    source: 'Gamebook round 7, gb7-a5-commission-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-crypt-key': {
    file: 'sections/a5-crypt-key',
    alt: 'A rabbit kit sits on the floor of a long lamplit crypt corridor beside two smaller rabbits.',
    artImageId: 243967,
    source: 'Gamebook round 7, gb7-a5-crypt-key-1',
    fit: 'exact',
  },
  'a5-crypt-wren': {
    file: 'sections/a5-crypt-wren',
    alt: 'A frightened otter novice in a grey habit stands in the dark arch of the crypt stair, between two wall candles.',
    artImageId: 243966,
    source: 'Gamebook round 7, gb7-a5-crypt-wren-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-day-two': {
    file: 'sections/a5-day-two',
    alt: 'A wooden bowl of honey-colored porridge sits on a bench under a bright window.',
    artImageId: 243927,
    source: 'Gamebook round 7, gb7-a5-day-two-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-delivered': {
    file: 'sections/a5-delivered',
    alt: 'Zuzu stands alone between wooden barrels in a rocky hollow, one paw open at his side.',
    artImageId: 243987,
    source: 'Gamebook round 7, gb7-a5-delivered-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-dream': {
    file: 'sections/a5-dream',
    alt: 'A pale road runs across dark desert toward a black jagged spire under a sky of stars.',
    artImageId: 243973,
    source: 'Gamebook round 7, gb7-a5-dream-1',
    fit: 'exact',
  },
  'a5-dream-empty': {
    file: 'sections/a5-dream-empty',
    alt: 'A black hole in the shape of a crow with spread wings hangs over a long empty road.',
    artImageId: 243977,
    source: 'Gamebook round 7, gb7-a5-dream-empty-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-dream-home': {
    file: 'sections/a5-dream-home',
    alt: 'A small temple tower with one lit window stands at the end of a wet path among mountains.',
    artImageId: 243975,
    source: 'Gamebook round 7, gb7-a5-dream-home-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-dream-wake': {
    file: 'sections/a5-dream-wake',
    alt: 'The fennec girl in a dark dress stands in a moonlit doorway, eyes half closed.',
    artImageId: 243980,
    source: 'Gamebook round 7, gb7-a5-dream-wake-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-errand-refused': {
    file: 'sections/a5-errand-refused',
    alt: 'The fennec girl sits alone on a step outside a closed wooden door.',
    artImageId: 243945,
    source: 'Gamebook round 7, gb7-a5-errand-refused-1',
    fit: 'exact',
  },
  'a5-errand-taken': {
    file: 'sections/a5-errand-taken',
    alt: 'A sealed letter and a glass of water sit on a table while a dark shape watches through the window.',
    artImageId: 243943,
    source: 'Gamebook round 7, gb7-a5-errand-taken-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-her-hands': {
    file: 'sections/a5-her-hands',
    alt: 'The otter abbess smiles over a bowl of stew between black candles, dark wax beneath her claws.',
    artImageId: 243919,
    source: 'Gamebook round 7, gb7-a5-her-hands-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-kit-caught': {
    file: 'sections/a5-kit-caught',
    alt: 'A rabbit kit kneels scrubbing the chapel steps with a bucket of water at dawn.',
    artImageId: 243972,
    source: 'Gamebook round 7, gb7-a5-kit-caught-2',
    fit: 'exact',
  },
  'a5-note-burned': {
    file: 'sections/a5-note-burned',
    alt: 'A scrap of paper burns in a small iron pot hanging from a beam.',
    artImageId: 243956,
    source: 'Gamebook round 7, gb7-a5-note-burned-2',
    fit: 'exact',
    shape: 'square',
  },
  'a5-rags-burned': {
    file: 'sections/a5-rags-burned',
    alt: 'The fennec girl huddles in a doorway in a plain white dress, arms wrapped around her knees.',
    artImageId: 243936,
    source: 'Gamebook round 7, gb7-a5-rags-burned-2',
    fit: 'exact',
    shape: 'square',
  },
  'a5-scullery': {
    file: 'sections/a5-scullery',
    alt: 'An otter nun stands in a lamplit doorway, a steaming washbasin on the floor beside her.',
    artImageId: 243926,
    source: 'Gamebook round 7, gb7-a5-scullery-2',
    fit: 'exact',
    shape: 'tall',
  },
  'a5-threshold': {
    file: 'sections/a5-threshold',
    alt: 'An otter nun kneels in a sunlit stone entry, gently washing the feet of a small fennec beside a basket of bread.',
    artImageId: 243917,
    source: 'Gamebook round 7, gb7-a5-threshold-1',
    fit: 'exact',
  },
  'a5-true-face': {
    file: 'sections/a5-true-face',
    alt: 'The otter abbess sits at a small round table across from the little fennec, a candle and a cup between them.',
    artImageId: 243922,
    source: 'Gamebook round 7, gb7-a5-true-face-2',
    fit: 'exact',
  },
  'a5-wagon-look': {
    file: 'sections/a5-wagon-look',
    alt: 'A covered wagon in the dark, a sealed letter lying on the floorboards beneath a candle.',
    artImageId: 243985,
    source: 'Gamebook round 7, gb7-a5-wagon-look-1',
    fit: 'exact',
    shape: 'square',
  },
  'a5-wren-taken': {
    file: 'sections/a5-wren-taken',
    alt: 'An empty bare room with plank walls, a small figure watching through the high window.',
    artImageId: 243953,
    source: 'Gamebook round 7, gb7-a5-wren-taken-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-badger': {
    file: 'sections/a6-badger',
    alt: 'A grizzled badger bounty hunter in a long coat and hat stands beside a lamp post with a coil of rope.',
    artImageId: 244001,
    source: 'Gamebook round 7, gb7-a6-badger-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-badger-iron': {
    file: 'sections/a6-badger-iron',
    alt: 'A revolver lies on a wet plank beside a lit lantern in the rain.',
    artImageId: 244006,
    source: 'Gamebook round 7, gb7-a6-badger-iron-2',
    fit: 'exact',
    shape: 'square',
  },
  'a6-badger-lied': {
    file: 'sections/a6-badger-lied',
    alt: 'The badger bounty hunter walks a dark forest road in his long coat and hat.',
    artImageId: 244007,
    source: 'Gamebook round 7, gb7-a6-badger-lied-1',
    fit: 'exact',
    shape: 'tall',
  },
  'a6-badger-rides': {
    file: 'sections/a6-badger-rides',
    alt: 'Under a sky full of stars, the badger bounty hunter stands on a ridge beside a small companion.',
    artImageId: 244015,
    source: 'Gamebook round 7, gb7-a6-badger-rides-1',
    fit: 'exact',
  },
  'a6-badger-spares': {
    file: 'sections/a6-badger-spares',
    alt: 'The badger bounty hunter tips his hat with one paw, a lantern in the other.',
    artImageId: 244013,
    source: 'Gamebook round 7, gb7-a6-badger-spares-1',
    fit: 'exact',
    shape: 'square',
  },
  'a6-kasa': {
    file: 'sections/a6-kasa',
    alt: 'A small mouse girl in an oversized grey cardigan holds up a lantern in a plank corridor, smiling.',
    artImageId: 243999,
    source: 'Gamebook round 7, gb7-a6-kasa-1',
    fit: 'exact',
    shape: 'square',
  },
  'a6-wall': {
    file: 'sections/a6-wall',
    alt: 'Zuzu sits by a lantern beside a small mouse girl in a dress, both looking at the wall of notices.',
    artImageId: 243997,
    source: 'Gamebook round 7, gb7-a6-wall-1',
    fit: 'exact',
  },
  'abbess-read': {
    file: 'sections/abbess-read',
    alt: 'The otter abbess in her black habit sits at a candlelit table, smiling over a bowl of stew.',
    artImageId: 243889,
    source: 'Gamebook round 7, gb7-abbess-read-1',
    fit: 'exact',
    shape: 'square',
  },
  'after-supper': {
    file: 'sections/after-supper',
    alt: "A long timber corridor lit by one lamp, a nun's dark silhouette standing in the far doorway.",
    artImageId: 243892,
    source: 'Gamebook round 7, gb7-after-supper-2',
    fit: 'exact',
  },
  aftermath: {
    file: 'sections/aftermath',
    alt: 'The coyote kneels in the dust in his long coat and hat, his right arm wrapped, beside the body of the crocodile.',
    artImageId: 243588,
    source: 'Gamebook round 6, gb6-aftermath-1',
    fit: 'exact',
    shape: 'square',
  },
  'bone-river': {
    file: 'sections/bone-river',
    alt: 'A huge bleached skull lies half buried in the sand of a red canyon.',
    artImageId: 243802,
    source: 'Gamebook round 6, gb6-bone-river-1',
    fit: 'exact',
  },
  'bridge-fall': {
    file: 'sections/bridge-fall',
    alt: 'Zuzu stands braced between swaying ropes in a deep canyon, dust rising around him.',
    artImageId: 243798,
    source: 'Gamebook round 6, gb6-bridge-fall-1',
    fit: 'exact',
    shape: 'tall',
  },
  'canyon-road': {
    file: 'sections/canyon-road',
    alt: 'A narrow wooden bridge stretches deep between towering red canyon walls toward a pale sun.',
    artImageId: 243797,
    source: 'Gamebook round 6, gb6-canyon-road-2',
    fit: 'exact',
  },
  chapel: {
    file: 'sections/chapel',
    alt: 'A plain chapel with tall windows, a bell rope hanging over an altar where something stands shrouded in white cloth.',
    artImageId: 243897,
    source: 'Gamebook round 7, gb7-chapel-1',
    fit: 'exact',
    shape: 'tall',
  },
  'cold-camp': {
    file: 'sections/cold-camp',
    alt: 'Zuzu crouches on a rock under the stars with no fire, his breath a small cloud in the cold night air.',
    artImageId: 243595,
    source: 'Gamebook round 6, gb6-cold-camp-2',
    fit: 'exact',
  },
  courtyard: {
    file: 'sections/courtyard',
    alt: 'A long adobe mission building with a small bell tower stands dark across an empty courtyard at night.',
    artImageId: 243893,
    source: 'Gamebook round 7, gb7-courtyard-1',
    fit: 'exact',
  },
  'crypt-glimpse': {
    file: 'sections/crypt-glimpse',
    alt: 'A vaulted stone crypt, a dark coiled shape carved or shadowed in the wall behind the altar.',
    artImageId: 243907,
    source: 'Gamebook round 7, gb7-crypt-glimpse-1',
    fit: 'exact',
  },
  dormitory: {
    file: 'sections/dormitory',
    alt: 'The fennec girl lies asleep on the floor of a bare room beside a single candle.',
    artImageId: 243902,
    source: 'Gamebook round 7, gb7-dormitory-2',
    fit: 'exact',
  },
  'dust-road': {
    file: 'sections/dust-road',
    alt: 'A twisted bare tree leans over a dirt track climbing toward a small shrine on a ridge under a purple dusk sky.',
    artImageId: 243592,
    source: 'Gamebook round 6, gb6-dust-road-1',
    fit: 'exact',
    shape: 'tall',
  },
  'hb-store-empty': {
    file: 'sections/hb-store-empty',
    alt: 'A dim, empty general store: bare shelves, a long wooden counter and dust hanging in the light from one window.',
    artImageId: 243659,
    source: 'Gamebook round 6, gb6-hb-store-empty-1',
    fit: 'exact',
  },
  'hb-store-find': {
    file: 'sections/hb-store-find',
    alt: 'A shallow wooden box packed with clean white linen sits on a scuffed store counter.',
    artImageId: 243658,
    source: 'Gamebook round 6, gb6-hb-store-find-2',
    fit: 'exact',
    shape: 'square',
  },
  'hollow-bell': {
    file: 'sections/hollow-bell',
    alt: 'Zuzu stands in a stone gateway with fire roaring behind him, paper notices pinned to the wall on either side.',
    artImageId: 243651,
    source: 'Gamebook round 6, gb6-hollow-bell-1',
    fit: 'exact',
  },
  'locked-door': {
    file: 'sections/locked-door',
    alt: 'A dark doorway stands ajar, two glowing eyes watching from the blackness inside.',
    artImageId: 243903,
    source: 'Gamebook round 7, gb7-locked-door-1',
    fit: 'exact',
    shape: 'tall',
  },
  'lost-them': {
    file: 'sections/lost-them',
    alt: 'Zuzu stands alone on a road between dark rocks under a full moon.',
    artImageId: 243730,
    source: 'Gamebook round 6, gb6-lost-them-2',
    fit: 'exact',
    shape: 'tall',
  },
  'night-watch': {
    file: 'sections/night-watch',
    alt: 'A tall hooded figure with no face stands in the dark behind a single burning candle.',
    artImageId: 243733,
    source: 'Gamebook round 6, gb6-night-watch-1',
    fit: 'exact',
    shape: 'tall',
  },
  posters: {
    file: 'sections/posters',
    alt: 'A long dim boardwalk under a roof, paper notices pinned on the plank walls.',
    artImageId: 243991,
    source: 'Gamebook round 7, gb7-posters-1',
    fit: 'exact',
  },
  saloon: {
    file: 'sections/saloon',
    alt: 'A rabbit barkeep with a red kerchief and dark vest stands behind her bar, bottles on the shelves.',
    artImageId: 243993,
    source: 'Gamebook round 7, gb7-saloon-1',
    fit: 'exact',
    shape: 'tall',
  },
  'saloon-truth': {
    file: 'sections/saloon-truth',
    alt: 'The rabbit barkeep leans her arms on the bar under a lamp, her eyes wet.',
    artImageId: 243996,
    source: 'Gamebook round 7, gb7-saloon-truth-2',
    fit: 'exact',
    shape: 'square',
  },
  'sister-trust': {
    file: 'sections/sister-trust',
    alt: 'Zuzu sits cross-legged in the ash, his wide hat shading his eyes, as a small fennec settles in close in front of him.',
    artImageId: 243663,
    source: 'Gamebook round 6, gb6-sister-trust-1',
    fit: 'exact',
    shape: 'tall',
  },
  standoff: {
    file: 'sections/standoff',
    alt: 'The one-eyed coyote kneels in dark water under a shaft of light, his hand resting near his revolver.',
    artImageId: 243579,
    source: 'Gamebook round 6, gb6-standoff-2',
    fit: 'exact',
    shape: 'square',
  },
  survivors: {
    file: 'sections/survivors',
    alt: 'A fennec girl with fierce orange eyes crouches on a burned boardwalk, clutching her little brother.',
    artImageId: 243661,
    source: 'Gamebook round 6, gb6-survivors-1',
    fit: 'exact',
  },
  'take-them': {
    file: 'sections/take-them',
    alt: 'An otter nun stands with folded paws before a barred iron gate.',
    artImageId: 243912,
    source: 'Gamebook round 7, gb7-take-them-2',
    fit: 'exact',
    shape: 'tall',
  },
  'they-follow': {
    file: 'sections/they-follow',
    alt: 'Zuzu walks a desert road at sunset, a small fennec trailing a few steps behind him.',
    artImageId: 243728,
    source: 'Gamebook round 6, gb6-they-follow-2',
    fit: 'exact',
  },
  tracks: {
    file: 'sections/tracks',
    alt: 'A tall iron gate stands shut under a stone arch, small footprints leading in and none coming out.',
    artImageId: 243896,
    source: 'Gamebook round 7, gb7-tracks-2',
    fit: 'exact',
    shape: 'square',
  },
  'two-fires': {
    file: 'sections/two-fires',
    alt: 'Zuzu sits on a rock beside a campfire on the open desert at night.',
    artImageId: 243732,
    source: 'Gamebook round 6, gb6-two-fires-2',
    fit: 'exact',
  },
  wagon: {
    file: 'sections/wagon',
    alt: 'An abandoned covered wagon stands on a desert road, a vulture perched on its roof.',
    artImageId: 243854,
    source: 'Gamebook round 6, gb6-wagon-1',
    fit: 'exact',
  },
  'wagon-find': {
    file: 'sections/wagon-find',
    alt: "Several pairs of small worn boots and an iron ring lie on the floorboards beside the wagon's side.",
    artImageId: 243856,
    source: 'Gamebook round 6, gb6-wagon-find-1',
    fit: 'exact',
    shape: 'square',
  },
}
