-- CreateTable: Todo
CREATE TABLE `Todo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `title` VARCHAR(512) NOT NULL,
  `description` TEXT NULL,
  `status` ENUM('OPEN', 'DONE', 'ARCHIVED') NOT NULL DEFAULT 'OPEN',
  `priority` ENUM('LOW', 'NORMAL', 'HIGH') NOT NULL DEFAULT 'NORMAL',
  `dueDate` DATETIME(3) NULL,
  `icon` VARCHAR(128) NULL,
  `imagePath` VARCHAR(764) NULL,
  `userId` INT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `Todo_userId_idx` (`userId`),
  CONSTRAINT `Todo_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
