-- AlterTable
ALTER TABLE `Art` ADD COLUMN `pitchId` INTEGER NULL,
    MODIFY `pitch` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Tag` ADD COLUMN `userId` INTEGER NULL DEFAULT 0;

-- AddForeignKey
ALTER TABLE `Art` ADD CONSTRAINT `Art_pitchId_fkey` FOREIGN KEY (`pitchId`) REFERENCES `Tag`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Tag` ADD CONSTRAINT `Tag_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
