<!-- components/ruler-hooked/ruler-hooked-stage.vue
     The composited play screen (compositing.md §5).

     TWO STACKS, deliberately. Underneath is the placeholder floor: one band per
     region, coloured by that region's current state, so choices visibly
     recomposite the scene even with no art at all. On top is the real composite:
     each region's /images/ruler-hooked/{region}-{state}[-{time}].webp drawn at
     FULL FRAME and stacked in z-order, transparent everywhere outside its own
     depth band, so the layers register against one another on a single canvas.

     The art used to be drawn inside its band instead (one <img> per flex-1 strip,
     object-cover). That silently contradicted the art direction it was being fed:
     art-direction.md §2 authors every layer full-play-screen with everything
     outside its band transparent, and eight bands in an h-96 column is roughly a
     20:1 strip -- so a correctly-authored layer was cropped to a thin slice of its
     own middle, and a layer authored to fit the strip could not be generated by
     any image model at that aspect ratio. Resolved as ruler-hooked/t-017 in favour
     of the compositing spec, because full-frame registration is what makes the
     art direction's shared key-light rule mean anything: a treeline-logged-night
     layer only sits convincingly in front of a far_shore-industrial-night layer if
     they are drawn on the same canvas. -->
<template>
  <div
    class="relative w-full overflow-hidden rounded-xl border border-base-300 shadow-inner"
    :aria-label="`Lakeside kingdom at ${scene?.time ?? 'day'}`"
  >
    <div class="flex h-72 flex-col sm:h-96">
      <div
        v-for="layer in layers"
        :key="layer.region"
        class="relative flex-1 transition-colors duration-500 ease-out"
        :class="layer.classes"
      >
        <span
          class="absolute bottom-1 left-2 text-[10px] font-medium uppercase tracking-wide text-white/70 drop-shadow"
        >
          {{ layer.label }}
        </span>
      </div>
    </div>
    <!-- Composited art, drawn over the whole canvas in z-order. DOM order is the
         stacking order for positioned siblings, and `layers` is already sorted
         ascending by z, so no explicit z-index is needed. Each layer covers the
         band labels underneath it exactly when it has art to show for them. -->
    <img
      v-for="layer in artLayers"
      :key="`art-${layer.region}`"
      :src="layer.src!"
      alt=""
      class="pointer-events-none absolute inset-0 h-full w-full object-cover"
      @error="onImgError(layer.region)"
    />
    <div
      class="pointer-events-none absolute right-2 top-2 rounded-full bg-black/40 px-2 py-0.5 text-xs text-white"
    >
      {{ scene?.time ?? 'day' }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { assetCandidates } from '~/utils/rulerHooked/compositor'
import { getPortraitUrl } from '~/utils/rulerHooked/portraitStore'
import { RULER_LAYER_FALLBACK_STATE } from '~/utils/rulerHooked/rulerPresets'
import type {
  RegionKey,
  RegionsManifest,
  SceneState,
} from '~/types/ruler-hooked'

const props = withDefaults(
  defineProps<{
    scene: SceneState | null
    regions: RegionsManifest
    showImages?: boolean
    /** t-021: a locally-stored custom portrait, when set, replaces the ruler
     *  region's preset layer entirely (highest priority — see resolveScene's
     *  ruler cosmetic axis for how presetId is picked underneath it). */
    rulerCustomPortraitId?: string | null
  }>(),
  {
    showImages: true,
    rulerCustomPortraitId: null,
  },
)

// Resolve the custom portrait id (if any) to a displayable object URL.
// Async by nature (IndexedDB) — starts null so the preset/fallback layer
// shows first and swaps in once resolved, never a gap.
const customPortraitUrl = ref<string | null>(null)
watch(
  () => props.rulerCustomPortraitId,
  async (id, _prev, onCleanup) => {
    let cancelled = false
    onCleanup(() => {
      cancelled = true
    })
    if (!id) {
      customPortraitUrl.value = null
      return
    }
    const url = await getPortraitUrl(id)
    if (!cancelled) customPortraitUrl.value = url
  },
  { immediate: true },
)
const prevUrl = ref<string | null>(null)
watch(customPortraitUrl, (url) => {
  // Revoke the previous object URL once it's no longer displayed, not before
  // (revoking the URL still in `src` would blank the image mid-swap).
  if (prevUrl.value && prevUrl.value !== url) URL.revokeObjectURL(prevUrl.value)
  prevUrl.value = url
})
onBeforeUnmount(() => {
  if (prevUrl.value) URL.revokeObjectURL(prevUrl.value)
})

// Per-region index into the asset fallback ladder (advances on <img> error).
const errIndex = reactive<Record<string, number>>({})
// If the custom portrait itself fails to load (corrupt/unreadable blob), stop
// offering it and degrade to the normal preset fallback ladder instead of
// retrying the same broken src forever.
const customPortraitFailed = ref(false)
function onImgError(region: string) {
  if (region === 'ruler' && customPortraitUrl.value) {
    customPortraitFailed.value = true
    return
  }
  errIndex[region] = (errIndex[region] ?? 0) + 1
}
watch(customPortraitUrl, () => {
  customPortraitFailed.value = false
})

// A readable placeholder palette keyed by state so recompositing is visible.
const STATE_CLASS: Record<string, string> = {
  // treeline
  wild: 'bg-gradient-to-b from-green-700 to-green-900',
  tended: 'bg-gradient-to-b from-green-500 to-green-700',
  logged: 'bg-gradient-to-b from-amber-700 to-yellow-900',
  overbuilt: 'bg-gradient-to-b from-stone-500 to-stone-700',
  // far_shore
  pristine: 'bg-gradient-to-b from-emerald-500 to-teal-700',
  farmed: 'bg-gradient-to-b from-lime-500 to-green-700',
  industrial: 'bg-gradient-to-b from-slate-500 to-slate-800',
  // village_edge
  hamlet: 'bg-gradient-to-b from-orange-300 to-amber-500',
  township: 'bg-gradient-to-b from-orange-400 to-amber-600',
  boomtown: 'bg-gradient-to-b from-zinc-400 to-zinc-600',
  // castle_grounds
  humble: 'bg-gradient-to-b from-indigo-300 to-indigo-500',
  flourishing: 'bg-gradient-to-b from-violet-400 to-purple-600',
  gaudy: 'bg-gradient-to-b from-fuchsia-400 to-yellow-500',
  // single-state / cosmetic
  open: 'bg-gradient-to-b from-sky-300 to-sky-500',
  clear: 'bg-gradient-to-b from-cyan-400 to-blue-600',
  grassy: 'bg-gradient-to-b from-green-400 to-green-600',
  fishing: 'bg-gradient-to-b from-amber-200 to-amber-400',
}

interface Layer {
  region: RegionKey
  label: string
  classes: string
  src: string | null
}

const layers = computed<Layer[]>(() => {
  const scene = props.scene
  if (!scene) return []
  const regs = props.regions.regions
  return (Object.keys(regs) as RegionKey[])
    .filter((k) => !!regs[k])
    .sort((a, b) => (regs[a]!.z ?? 0) - (regs[b]!.z ?? 0))
    .map((region) => {
      const state = scene.regionStates[region]
      const isRuler = region === 'ruler'
      // The ruler region falls back to its one already-rendered layer
      // (ruler-fishing.webp) until a given cosmetic preset's own file exists
      // (t-021) — every other region has no such fallback.
      const cands = props.showImages
        ? assetCandidates(
            region,
            state,
            scene.time,
            undefined,
            isRuler ? RULER_LAYER_FALLBACK_STATE : undefined,
          )
        : []
      const idx = errIndex[region] ?? 0
      // A custom portrait (once resolved) takes priority over any preset
      // layer for the ruler region specifically.
      const customSrc =
        isRuler && !customPortraitFailed.value ? customPortraitUrl.value : null
      return {
        region,
        label: state ? `${region} · ${state}` : region,
        classes: STATE_CLASS[state ?? 'open'] ?? 'bg-base-300',
        src: customSrc ?? cands[idx] ?? null,
      }
    })
})

/** Only the layers that actually resolved to a file, so v-for has no v-if beside it. */
const artLayers = computed<Layer[]>(() =>
  layers.value.filter((layer) => !!layer.src),
)
</script>
