-- AlterTable
ALTER TABLE `Pitch` ADD COLUMN `icon` VARCHAR(191) NULL,
    MODIFY `PitchType` ENUM('ARTPITCH', 'BRAINSTORM', 'WEIRDLANDIA', 'RANDOMLIST', 'TITLE', 'VIBE') NOT NULL DEFAULT 'ARTPITCH';

-- AlterTable
ALTER TABLE `User` ADD COLUMN `vibes` JSON NULL;
