-- AlterTable
ALTER TABLE `Art` MODIFY `promptId` INTEGER NULL DEFAULT 1,
    MODIFY `userId` INTEGER NULL DEFAULT 1,
    MODIFY `pitchId` INTEGER NULL DEFAULT 1,
    MODIFY `galleryId` INTEGER NULL DEFAULT 21,
    MODIFY `channelId` INTEGER NULL DEFAULT 1;

-- AlterTable
ALTER TABLE `Reward` MODIFY `userId` INTEGER NULL DEFAULT 1;

-- AlterTable
ALTER TABLE `Tag` MODIFY `channelId` INTEGER NULL DEFAULT 1;
