// 🐾 Auto-generated enriched animal data
// Do not edit this file manually.

import type { AnimalData } from './animalData'

export const enrichedAnimalDataList: AnimalData[] = [
  {
    "name": "Sloth",
    "scientificName": "Bradypus variegatus",
    "category": "real",
    "icon": "🦥",
    "description": "A slow-moving, tree-dwelling mammal with long claws and shaggy fur.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Sloth",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9f/Bradypus_variegatus_from_Costa_Rica.jpg",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium",
      "hasHair": true,
      "laysEggs": false,
      "texture": "furry"
    }
  },
  {
    "name": "Water Bear",
    "scientificName": "Hypsibius dujardini",
    "category": "real",
    "icon": "🧸",
    "description": "A microscopic, water-dwelling invertebrate with eight stubby legs and extreme resilience.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Tardigrade",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/0/00/Hys_dujardini_1.jpg",
    "traits": {
      "legs": 8,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": false,
      "environment": "water",
      "bodyType": "other",
      "size": "tiny",
      "hasHair": false,
      "hasFeathers": false,
      "laysEggs": true,
      "texture": "smooth"
    }
  },
  {
    "name": "Axolotl",
    "scientificName": "Ambystoma mexicanum",
    "category": "real",
    "icon": "🦎",
    "description": "A smiling aquatic salamander with feathery gills that never grows up.",
    "wikiUrl": "https://en.wikipedia.org/wiki/Axolotl",
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/69/Ambystoma_mexicanum_02.jpg",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "quadruped",
      "size": "small",
      "laysEggs": true,
      "texture": "smooth"
    }
  },
  {
    "name": "Flamingo",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Flamingo",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Flamingo%20animal"
  },
  {
    "name": "Raccoon",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Raccoon",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Raccoon%20animal"
  },
  {
    "name": "Platypus",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Platypus",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Platypus%20animal"
  },
  {
    "name": "Pangolin",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Pangolin",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Pangolin%20animal"
  },
  {
    "name": "Narwhal",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Narwhal",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Narwhal%20animal"
  },
  {
    "name": "Red Panda",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Red_Panda",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Red%20Panda%20animal"
  },
  {
    "name": "Kiwi Bird",
    "traits": {
      "legs": 2,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "hasFeathers": true,
      "bodyType": "winged",
      "size": "small"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Kiwi_Bird",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Kiwi%20Bird%20animal"
  },
  {
    "name": "Hedgehog",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Hedgehog",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Hedgehog%20animal"
  },
  {
    "name": "Manatee",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Manatee",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Manatee%20animal"
  },
  {
    "name": "Capybara",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Capybara",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Capybara%20animal"
  },
  {
    "name": "Quokka",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Quokka",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Quokka%20animal"
  },
  {
    "name": "Elephant Shrew",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 2,
      "tail": true,
      "environment": "land",
      "bodyType": "other",
      "size": "giant"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Elephant_Shrew",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Elephant%20Shrew%20animal"
  },
  {
    "name": "Okapi",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Okapi",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Okapi%20animal"
  },
  {
    "name": "Aardvark",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Aardvark",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Aardvark%20animal"
  },
  {
    "name": "Dugong",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Dugong",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Dugong%20animal"
  },
  {
    "name": "Sea Cucumber",
    "traits": {
      "legs": 0,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "amorphous",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Sea_Cucumber",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Sea%20Cucumber%20animal"
  },
  {
    "name": "Pufferfish",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Pufferfish",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Pufferfish%20animal"
  },
  {
    "name": "Blobfish",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Blobfish",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Blobfish%20animal"
  },
  {
    "name": "Octopus",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Octopus",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Octopus%20animal"
  },
  {
    "name": "Mongoose",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Mongoose",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Mongoose%20animal"
  },
  {
    "name": "Lynx",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Lynx",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Lynx%20animal"
  },
  {
    "name": "Fennec Fox",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "small"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Fennec_Fox",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Fennec%20Fox%20animal"
  },
  {
    "name": "Chinchilla",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Chinchilla",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Chinchilla%20animal"
  },
  {
    "name": "Cockatoo",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Cockatoo",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Cockatoo%20animal"
  },
  {
    "name": "Cassowary",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Cassowary",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Cassowary%20animal"
  },
  {
    "name": "Blue-Footed Booby",
    "traits": {
      "legs": 2,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "hasFeathers": true,
      "bodyType": "winged",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Blue-Footed_Booby",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Blue-Footed%20Booby%20animal"
  },
  {
    "name": "Emu",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Emu",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Emu%20animal"
  },
  {
    "name": "Armadillo",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Armadillo",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Armadillo%20animal"
  },
  {
    "name": "Toucan",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Toucan",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Toucan%20animal"
  },
  {
    "name": "Tarantula",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 2,
      "tail": true,
      "environment": "land",
      "bodyType": "other",
      "size": "tiny"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Tarantula",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Tarantula%20animal"
  },
  {
    "name": "Bearded Dragon",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "texture": "scaly",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Bearded_Dragon",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Bearded%20Dragon%20animal"
  },
  {
    "name": "Iguana",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "texture": "scaly",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Iguana",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Iguana%20animal"
  },
  {
    "name": "Sugar Glider",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Sugar_Glider",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Sugar%20Glider%20animal"
  },
  {
    "name": "Wallaby",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Wallaby",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Wallaby%20animal"
  },
  {
    "name": "Koala",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Koala",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Koala%20animal"
  },
  {
    "name": "Opossum",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Opossum",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Opossum%20animal"
  },
  {
    "name": "Wolverine",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Wolverine",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Wolverine%20animal"
  },
  {
    "name": "Tasmanian Devil",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Tasmanian_Devil",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Tasmanian%20Devil%20animal"
  },
  {
    "name": "Meerkat",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Meerkat",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Meerkat%20animal"
  },
  {
    "name": "Kinkajou",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Kinkajou",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Kinkajou%20animal"
  },
  {
    "name": "Millillillillipede",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Millillillillipede",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Millillillillipede%20animal"
  },
  {
    "name": "Yak",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Yak",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Yak%20animal"
  },
  {
    "name": "Alpaca",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Alpaca",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Alpaca%20animal"
  },
  {
    "name": "Llama",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Llama",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Llama%20animal"
  },
  {
    "name": "Oryx",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Oryx",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Oryx%20animal"
  },
  {
    "name": "Binturong",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Binturong",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Binturong%20animal"
  },
  {
    "name": "Harpy Eagle",
    "traits": {
      "legs": 2,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "hasFeathers": true,
      "bodyType": "winged",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Harpy_Eagle",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Harpy%20Eagle%20animal"
  },
  {
    "name": "Kingfisher",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Kingfisher",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Kingfisher%20animal"
  },
  {
    "name": "Loon",
    "traits": {
      "legs": 2,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "hasFeathers": true,
      "bodyType": "winged",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Loon",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Loon%20animal"
  },
  {
    "name": "Seahorse",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Seahorse",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Seahorse%20animal"
  },
  {
    "name": "Glowworm",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 2,
      "tail": true,
      "environment": "land",
      "bodyType": "other",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Glowworm",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Glowworm%20animal"
  },
  {
    "name": "Firefly",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 2,
      "tail": true,
      "environment": "land",
      "bodyType": "other",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Firefly",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Firefly%20animal"
  },
  {
    "name": "Praying Mantis",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "tiny"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Praying_Mantis",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Praying%20Mantis%20animal"
  },
  {
    "name": "Stick Insect",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 2,
      "tail": true,
      "environment": "land",
      "bodyType": "other",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Stick_Insect",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Stick%20Insect%20animal"
  },
  {
    "name": "Hermit Crab",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "crustacean",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Hermit_Crab",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Hermit%20Crab%20animal"
  },
  {
    "name": "Leafcutter Ant",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 2,
      "tail": true,
      "environment": "land",
      "bodyType": "other",
      "size": "tiny"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Leafcutter_Ant",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Leafcutter%20Ant%20animal"
  },
  {
    "name": "Giant Clam",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "crustacean",
      "size": "tiny"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Giant_Clam",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Giant%20Clam%20animal"
  },
  {
    "name": "Horseshoe Crab",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "crustacean",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Horseshoe_Crab",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Horseshoe%20Crab%20animal"
  },
  {
    "name": "Sea Dragon",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "texture": "scaly",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Sea_Dragon",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Sea%20Dragon%20animal"
  },
  {
    "name": "Moon Jellyfish",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Moon_Jellyfish",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Moon%20Jellyfish%20animal"
  },
  {
    "name": "Peacock",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Peacock",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Peacock%20animal"
  },
  {
    "name": "Albatross",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "bodyType": "winged",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Albatross",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Albatross%20animal"
  },
  {
    "name": "Hammerhead Shark",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Hammerhead_Shark",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Hammerhead%20Shark%20animal"
  },
  {
    "name": "Goblin Shark",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Goblin_Shark",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Goblin%20Shark%20animal"
  },
  {
    "name": "Manta Ray",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "tiny"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Manta_Ray",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Manta%20Ray%20animal"
  },
  {
    "name": "Stingray",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Stingray",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Stingray%20animal"
  },
  {
    "name": "Dolphin",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Dolphin",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Dolphin%20animal"
  },
  {
    "name": "Orca",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Orca",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Orca%20animal"
  },
  {
    "name": "Beluga Whale",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "giant"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Beluga_Whale",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Beluga%20Whale%20animal"
  },
  {
    "name": "Honey Badger",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Honey_Badger",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Honey%20Badger%20animal"
  },
  {
    "name": "Civet",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Civet",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Civet%20animal"
  },
  {
    "name": "Skunk",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Skunk",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Skunk%20animal"
  },
  {
    "name": "Zebra",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Zebra",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Zebra%20animal"
  },
  {
    "name": "Giant Anteater",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 2,
      "tail": true,
      "environment": "land",
      "bodyType": "other",
      "size": "tiny"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Giant_Anteater",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Giant%20Anteater%20animal"
  },
  {
    "name": "Proboscis Monkey",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Proboscis_Monkey",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Proboscis%20Monkey%20animal"
  },
  {
    "name": "Mandrill",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Mandrill",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Mandrill%20animal"
  },
  {
    "name": "Howler Monkey",
    "traits": {
      "legs": 2,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "hasFeathers": true,
      "bodyType": "winged",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Howler_Monkey",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Howler%20Monkey%20animal"
  },
  {
    "name": "Tamandua",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Tamandua",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Tamandua%20animal"
  },
  {
    "name": "Golden Lion Tamarin",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Golden_Lion_Tamarin",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Golden%20Lion%20Tamarin%20animal"
  },
  {
    "name": "Marmoset",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Marmoset",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Marmoset%20animal"
  },
  {
    "name": "Hoatzin",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Hoatzin",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Hoatzin%20animal"
  },
  {
    "name": "Frilled Lizard",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "texture": "scaly",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Frilled_Lizard",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Frilled%20Lizard%20animal"
  },
  {
    "name": "Komodo Dragon",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "texture": "scaly",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Komodo_Dragon",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Komodo%20Dragon%20animal"
  },
  {
    "name": "Sand Cat",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Sand_Cat",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Sand%20Cat%20animal"
  },
  {
    "name": "Snow Leopard",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Snow_Leopard",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Snow%20Leopard%20animal"
  },
  {
    "name": "Arctic Fox",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "small"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Arctic_Fox",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Arctic%20Fox%20animal"
  },
  {
    "name": "Pika",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Pika",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Pika%20animal"
  },
  {
    "name": "Gerbil",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Gerbil",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Gerbil%20animal"
  },
  {
    "name": "Kudu",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Kudu",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Kudu%20animal"
  },
  {
    "name": "Weasel",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Weasel",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Weasel%20animal"
  },
  {
    "name": "Ermine",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Ermine",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Ermine%20animal"
  },
  {
    "name": "Mink",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Mink",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Mink%20animal"
  },
  {
    "name": "Otter",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "small"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Otter",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Otter%20animal"
  },
  {
    "name": "Peafowl",
    "traits": {
      "legs": 2,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "hasFeathers": true,
      "bodyType": "winged",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Peafowl",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Peafowl%20animal"
  },
  {
    "name": "Puffin",
    "traits": {
      "legs": 2,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "hasFeathers": true,
      "bodyType": "winged",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Puffin",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Puffin%20animal"
  },
  {
    "name": "Numbat",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "bodyType": "winged",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Numbat",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Numbat%20animal"
  },
  {
    "name": "Wombat",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "bodyType": "winged",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Wombat",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Wombat%20animal"
  },
  {
    "name": "Tree Kangaroo",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Tree_Kangaroo",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Tree%20Kangaroo%20animal"
  },
  {
    "name": "Quoll",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Quoll",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Quoll%20animal"
  },
  {
    "name": "Cuttlefish",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Cuttlefish",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Cuttlefish%20animal"
  },
  {
    "name": "Sea Otter",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "small"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Sea_Otter",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Sea%20Otter%20animal"
  },
  {
    "name": "Sea Turtle",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Sea_Turtle",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Sea%20Turtle%20animal"
  },
  {
    "name": "Starfish",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Starfish",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Starfish%20animal"
  },
  {
    "name": "Crown-of-Thorns Starfish",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "serpentine",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Crown-of-Thorns_Starfish",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Crown-of-Thorns%20Starfish%20animal"
  },
  {
    "name": "Blue Jay",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Blue_Jay",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Blue%20Jay%20animal"
  },
  {
    "name": "Caracal",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Caracal",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Caracal%20animal"
  },
  {
    "name": "Echidna",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Echidna",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Echidna%20animal"
  },
  {
    "name": "Gharial",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Gharial",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Gharial%20animal"
  },
  {
    "name": "Mudskipper",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Mudskipper",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Mudskipper%20animal"
  },
  {
    "name": "Orchid Mantis",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 2,
      "tail": true,
      "environment": "land",
      "bodyType": "other",
      "size": "tiny"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Orchid_Mantis",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Orchid%20Mantis%20animal"
  },
  {
    "name": "Velvet Worm",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 2,
      "tail": true,
      "environment": "land",
      "bodyType": "other",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Velvet_Worm",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Velvet%20Worm%20animal"
  },
  {
    "name": "Rock Hyrax",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Rock_Hyrax",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Rock%20Hyrax%20animal"
  },
  {
    "name": "Shoebill Stork",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Shoebill_Stork",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Shoebill%20Stork%20animal"
  },
  {
    "name": "Indian Star Tortoise",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Indian_Star_Tortoise",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Indian%20Star%20Tortoise%20animal"
  },
  {
    "name": "Galapagos Tortoise",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Galapagos_Tortoise",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Galapagos%20Tortoise%20animal"
  },
  {
    "name": "Leafy Sea Dragon",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "texture": "scaly",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Leafy_Sea_Dragon",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Leafy%20Sea%20Dragon%20animal"
  },
  {
    "name": "Fairy Penguin",
    "traits": {
      "legs": 2,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "hasFeathers": true,
      "bodyType": "winged",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Fairy_Penguin",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Fairy%20Penguin%20animal"
  },
  {
    "name": "Dingo",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Dingo",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Dingo%20animal"
  },
  {
    "name": "Clouded Leopard",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Clouded_Leopard",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Clouded%20Leopard%20animal"
  },
  {
    "name": "Spider Monkey",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Spider_Monkey",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Spider%20Monkey%20animal"
  },
  {
    "name": "Pallas’s Cat",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Pallass_Cat",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Pallas%E2%80%99s%20Cat%20animal"
  },
  {
    "name": "Pink Fairy Armadillo",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Pink_Fairy_Armadillo",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Pink%20Fairy%20Armadillo%20animal"
  },
  {
    "name": "Japanese Spider Crab",
    "traits": {
      "legs": 6,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "water",
      "bodyType": "crustacean",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Japanese_Spider_Crab",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Japanese%20Spider%20Crab%20animal"
  },
  {
    "name": "Atlantic Puffin",
    "traits": {
      "legs": 2,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "hasFeathers": true,
      "bodyType": "winged",
      "size": "tiny"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Atlantic_Puffin",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Atlantic%20Puffin%20animal"
  },
  {
    "name": "Hummingbird",
    "traits": {
      "legs": 2,
      "eyes": 2,
      "wings": 2,
      "antennae": 0,
      "tail": true,
      "environment": "air",
      "hasFeathers": true,
      "bodyType": "winged",
      "size": "small"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Hummingbird",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Hummingbird%20animal"
  },
  {
    "name": "Black Swan",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Black_Swan",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Black%20Swan%20animal"
  },
  {
    "name": "Ocelot",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Ocelot",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Ocelot%20animal"
  },
  {
    "name": "Tapir",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Tapir",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Tapir%20animal"
  },
  {
    "name": "Civet Cat",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Civet_Cat",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Civet%20Cat%20animal"
  },
  {
    "name": "Golden Snub-Nosed Monkey",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Golden_Snub-Nosed_Monkey",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Golden%20Snub-Nosed%20Monkey%20animal"
  },
  {
    "name": "Draco Lizard",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "texture": "scaly",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Draco_Lizard",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Draco%20Lizard%20animal"
  },
  {
    "name": "Ribbon Eel",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Ribbon_Eel",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Ribbon%20Eel%20animal"
  },
  {
    "name": "Leaf Tailed Gecko",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "texture": "scaly",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Leaf_Tailed_Gecko",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Leaf%20Tailed%20Gecko%20animal"
  },
  {
    "name": "Rainbow Lorikeet",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Rainbow_Lorikeet",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Rainbow%20Lorikeet%20animal"
  },
  {
    "name": "African Wild Dog",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/African_Wild_Dog",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=African%20Wild%20Dog%20animal"
  },
  {
    "name": "Slow Loris",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Slow_Loris",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Slow%20Loris%20animal"
  },
  {
    "name": "Tarsier",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Tarsier",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Tarsier%20animal"
  },
  {
    "name": "Indian Pangolin",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Indian_Pangolin",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Indian%20Pangolin%20animal"
  },
  {
    "name": "Springhare",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Springhare",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Springhare%20animal"
  },
  {
    "name": "Spotted Hyena",
    "traits": {
      "legs": 4,
      "eyes": 2,
      "wings": 0,
      "antennae": 0,
      "tail": true,
      "environment": "land",
      "bodyType": "quadruped",
      "size": "medium"
    },
    "wikiUrl": "https://en.wikipedia.org/wiki/Spotted_Hyena",
    "imageUrl": "https://www.google.com/search?tbm=isch&q=Spotted%20Hyena%20animal"
  }
]
