// stores/utils/randomQuote.ts

const quotes = [
  '“Code is like humor. When you have to explain it, it’s bad.” – Cory House',
  '“Before software can be reusable it first has to be usable.” – Ralph Johnson',
  '“Deleted code is debugged code.” – Jeff Sickel',
  '“It works on my machine.” – Every developer, ever',
  '“Programming is the art of telling another human what one wants the computer to do.” – Donald Knuth',
  '“The best way to get a project done faster is to start sooner.” – Jim Highsmith',
  '“Computers are good at following instructions, but not at reading your mind.” – Donald Knuth',
  '“To iterate is human, to recurse divine.” – L. Peter Deutsch',
  '“There are two ways to write error-free programs; only the third one works.” – Alan Perlis',
  '“Talk is cheap. Show me the code.” – Linus Torvalds',
  '“Any fool can write code that a computer can understand. Good programmers write code that humans can understand.” – Martin Fowler',
  '“Software is a great combination between artistry and engineering.” – Bill Gates',
  '“You should name a variable using the same care with which you name a first-born child.” – Robert C. Martin',
  '“The question of whether computers can think is like asking whether submarines can swim.” – Edsger Dijkstra',
  '“Walking on water and developing software from a specification are easy if both are frozen.” – Edward V Berard',
  '“The computer was born to solve problems that did not exist before.” – Bill Gates',
  '“A computer once beat me at chess, but it was no match for me at kickboxing.” – Emo Philips',
  '“Debugging is like being the detective in a crime movie where you are also the murderer.” – Filipe Fortes',
  '“I don’t care if it works on your machine! We are not shipping your machine!” – Vidiu Platon',
  '“The most dangerous phrase in software engineering: ‘We’ve always done it this way.’” – Grace Hopper',
  '“The problem with troubleshooting is that trouble shoots back.” – Unknown',
  '“AI will not replace you. A person using AI will.” – Unknown',
  '“To understand recursion, one must first understand recursion.” – Unknown',
  '“First, solve the problem. Then, write the code.” – John Johnson',
  '“If debugging is the process of removing bugs, then programming must be the process of putting them in.” – Edsger Dijkstra',
  '“You can’t have great software without a great team, and most software teams behave like dysfunctional families.” – Jim McCarthy',
  '“Simplicity is the soul of efficiency.” – Austin Freeman',
  '“A user interface is like a joke. If you have to explain it, it’s not that good.” – Unknown',
  '“The future is already here – it’s just not evenly distributed.” – William Gibson',
  '“Don’t document bad code – rewrite it.” – Brian Kernighan',
  '“AI: Artificial intelligence is no match for natural stupidity.” – Unknown',
  '“Programming isn’t about what you know; it’s about what you can figure out.” – Chris Pine',
  '“Software and cathedrals are much the same – first we build them, then we pray.” – Sam Redwine',
  '“I see your point, but I still think you're wrong.” – Anonymous reviewer',
  '“Beware of bugs in the above code; I have only proved it correct, not tried it.” – Donald Knuth',
  '“In theory, there is no difference between theory and practice. But, in practice, there is.” – Jan L. A. van de Snepscheut',
  '“AI doesn’t have a soul. It has a sandbox.” – Unknown',
  '“Computers make very fast, very accurate mistakes.” – Unknown',
  '“Make it work, make it right, make it fast.” – Kent Beck',
]

export function randomQuote() {
  return quotes[Math.floor(Math.random() * quotes.length)]
}
