export const materialList = [
    'Mythril',
    'Adamantium',
    'Dragon Scale',
    'Obsidian',
    'Moonstone',
    'Starsteel',
    'Quantum Fiber',
    'Void Crystal',
    'Aether Silk',
    'Plasma Alloy',
    'Pyroclastic Rock',
    'Glacial Shard',
    'Thunderstone',
    'Solar Glass',
    'Nano-carbon',
    'Ethereal Mist',
    'Phoenix Feather',
    'Prismatic Ore',
    'Chrono Dust',
    'Nebula Thread',
    'Shadow Weave',
    'Demonic Bone',
    'Angelite',
    'Enchanted Bark',
    'Living Wood',
    'Astral Ore',
    'Cursed Iron',
    'Bio-metal',
    'Warped Stone',
    'Venom Glass',
    'Storm Weave',
    'Eclipse Stone',
    'Glowstone',
    'Liquid Gold',
    'Fire Opal',
    'Hollow Steel',
    'Titanite',
    'Vortex Gem',
    'Shimmer Cloth',
    'Lunar Resin',
    'Cryo Iron',
    'Starlight Powder',
    'Bone Glass',
    'Radiant Amber',
    'Magic-infused Clay',
    'Galactic Granite',
    'Warped Velvet',
    'Spire Crystal',
    'Ghost Iron',
    'Dark Matter Thread',
    'Platinum Filigree',
    'Frostbite Alloy',
    'Ancient Marble',
    'Bloodstone',
    'Spectral Quartz',
    'Cloudstone',
    'Voidsteel',
    'Runestone',
    'Blaze Ore',
    'Charged Crystal',
    'Eldritch Thread',
    'Soul Sand',
    'Temporal Resin',
    'Ironwood',
    'Ashglass',
    'Specter Silk',
    'Starfire Iron',
    'Molten Core',
    'Crimson Coral',
    'Echo Crystal',
    'Timeglass',
    'Fulgurite',
    'Tidal Pearl',
    'Whisperwood',
    'Shadow Oak',
    'Pulse Metal',
    'Infernal Brimstone',
    'Cosmic Ice',
    'Radiant Silk',
    'Phantom Glass',
    'Heavensteel',
    'Dragonbone Porcelain',
    'Cursed Velvet',
    'Amberlight',
    'Dreamcloth',
    'Prismarine Shard',
    'Arcane Silver',
    'Tanglewood',
    'Mirror Alloy',
    'Stormglass',
    'Nether Ore',
    'Chimeric Thread',
    'Hexstone',
    'Starfruit Fiber',
    'Shadewood',
    'Oblivion Alloy',
    'Cryolite',
    'Moonlit Granite',
    'Solar Flame',
  ]

export function randomMaterial(): string {
  return materialList[Math.floor(Math.random() * materialList.length)]
}