export function useRandomQuirk() {
  const quirks = [
    'Always speaks in riddles.',
    'Has an uncanny sense of direction but only in forests.',
    'Collects buttons from every town they visit.',
    'Can’t resist counting things aloud.',
    'Refuses to eat food unless it’s arranged in a specific order.',
    'Laughs uncontrollably at the mention of pickles.',
    'Only communicates through song when nervous.',
    'Writes poetry on any available surface.',
    'Believes their shadow is plotting against them.',
    'Carries a bag of marbles, claiming they’re magical.',
    'Gets distracted by shiny objects mid-conversation.',
    'Knows an unusual amount about clouds and weather patterns.',
    'Can mimic the sound of any animal perfectly.',
    'Refuses to walk on tiled floors with odd patterns.',
    'Always wears mismatched socks intentionally.',
    'Has an imaginary friend named "Bartholomew" who gives advice.',
    'Constantly names inanimate objects.',
    'Terrified of butterflies but loves moths.',
    'Draws symbols in the dirt whenever they stop walking.',
    'Only drinks tea that’s been stirred counterclockwise.',
    'Whistles haunting melodies when they’re deep in thought.',
    'Can’t resist making puns in dire situations.',
    'Owns a collection of unusual hats, one for every day of the week.',
    'Believes that sneezing wards off evil spirits.',
    'Has a pet rock they insist is sentient.',
    'Can identify anyone’s favorite fruit just by looking at them.',
    'Doodles elaborate maps of imaginary lands.',
    'Talks to plants as if they’re old friends.',
    'Carries a pocket full of acorns for "emergencies."',
    'Believes they’re being followed by an invisible duck.',
    'Can’t sleep unless they hum a lullaby to themselves.',
    'Refuses to use umbrellas, claiming they’re bad luck.',
    'Wears a scarf year-round, even in summer.',
    'Is a professional finger snapper, complete with routines.',
    'Refuses to touch books with even page numbers.',
    'Obsessed with finding "the perfect stick."',
    'Always leaves a breadcrumb trail wherever they go.',
    'Carries a notebook full of cryptic, self-written proverbs.',
    'Takes "invisible notes" with a pretend quill.',
    'Invents strange handshakes for every new person they meet.',
    'Taps their foot exactly 12 times before sitting down.',
    'Believes that certain colors bring them good luck.',
    'Keeps an assortment of dried herbs in their pockets.',
    'Has a superstition about only stepping on cracks.',
    'Keeps a list of "enemies" that includes animals and objects.',
    'Hums the same three notes whenever they’re planning something.',
    'Can’t stop spinning coins when deep in thought.',
    'Collects feathers and treats them as treasure.',
    'Only walks in the shadows, avoiding direct sunlight.',
    'Has a knack for predicting when someone will hiccup.',
    'Knows an absurd amount of trivia about cheese.',
    'Carries a compass but never uses it.',
    'Invents elaborate backstories for people they meet.',
    'Laughs at their own jokes before finishing them.',
    'Only wears boots, even in formal settings.',
    'Has a strong aversion to mirrors.',
    'Compulsively organizes objects by size.',
    'Can’t help but correct incorrect grammar in ancient texts.',
    'Uses overly dramatic hand gestures for mundane tasks.',
    'Refuses to sit on chairs with cushions.',
    'Has trained themselves to remember everything in rhyme.',
    'Owns a collection of jars filled with "mysterious substances."',
    'Can identify bird calls but refuses to explain how.',
    'Writes letters to fictional characters.',
    'Claims they can speak to fish but not other animals.',
    'Uses completely nonsensical phrases as insults.',
    'Believes sneezing too many times in a row causes bad luck.',
    'Carries a candle everywhere "just in case."',
    'Talks to their weapon as if it has feelings.',
    'Has a superstition about wearing mismatched gloves.',
    'Insists on starting every conversation with "Once upon a time..."',
    'Keeps a collection of "lucky pebbles" from different regions.',
    'Carries a spoon at all times, "just in case of pudding."',
    'Constantly checks behind them as if someone’s there.',
    'Gives names to every stray cat they encounter.',
    'Refuses to cross bridges without whistling a tune.',
    'Invents riddles for strangers and expects answers.',
    'Sprinkles salt around their bed before sleeping.',
    'Keeps a tiny mirror they believe shows "true intentions."',
    'Dances a little jig whenever they see a rainbow.',
    'Believes they can charm birds by chirping back at them.',
    'Knows every type of moss by sight and smell.',
    'Collects oddly shaped sticks and claims they’re magical.',
    'Carries an empty journal for "recording important events."',
    'Sniffs books to judge their "character."',
    'Keeps an invisible "force field" around themselves.',
    'Constantly sketches "the same recurring dream."',
    'Carries a secret recipe for soup at all times.',
    'Only eats foods in alphabetical order.',
    'Can juggle but only uses fruits.',
    'Talks to doors before opening them.',
    'Knows an absurd amount of facts about frogs.',
    'Always starts conversations by quoting obscure poetry.',
    'Leaves cryptic notes in bottles wherever they go.',
    'Refuses to touch objects made of copper.',
    'Believes staring contests determine trustworthiness.',
    'Wears mismatched earrings to "confuse the spirits."',
    'Whispers to the moon before going to sleep.',
  ]

  function randomQuirk() {
    return quirks[Math.floor(Math.random() * quirks.length)]
  }

  return { randomQuirk }
}
