// /stores/seeds/colorList.ts

export const colorPaletteList: string[] = [
  'Monochrome',
  'Rainbow',
  'Neon',
  'Pastel',
  'Muted Earthtones',
  'Vaporwave',
  'Fire & Ash',
  'Ocean Mist',
  'Candycore',
  'Iridescent Glow',
  'Retro Futura',
  'Ice & Steel',
  'Sunset Sorbet',
  'Toxic Green & Magenta',
  'Cosmic Blues',
  'Sepia & Gold',
  'Cyanotype',
  'Aurora Spectrum',
  'Blood & Ivory',
  'Midnight Jewel',

  // 🌈 Expanded
  'Bone & Copper',
  'Jungle Eclipse',
  'Lavender Fog',
  'Radiant Magma',
  'Peach Bloom',
  'Obsidian & Firefly',
  'Rose Quartz & Smoke',
  'Sunburnt Clay',
  'Silk Noir',
  'Coral & Moss',
  'Starlight Ice',
  'Blueprint Cyan',
  'Cursed Lichen',
  'Ghost Pastel',
  'Molten Opal',
  'Mars Dust',
  'Winter Dusk',
  'Honeyed Bronze',
  'Lunar Crater',

  // 🎨 Experimental
  'Digital Rust',
  'Alien Fruit',
  'Cloudberry Cream',
  'Ultraviolet Soil',
  'Desert Mirage',
  'Static Field',
  'Cyberpet Dreams',
  'Ancient Scroll',
  'Artificial Sunrise',
  'Mythic Gold',
  'Parasitic Bloom',
  'Grayscale Inversion',
  'Bubblegum Decay',
  'Electric Ember',
  'Crystalline Rust',
  'Ashen Spectrum',
  'Tundra Twilight',
  'Electric Lotus',
  'Peacock Smoke',
  'Melancholy Citrus',
]
