// stores/seeds/narratorTopics.ts
// AUTO-GENERATED by scripts/export-narrator-content.mjs — do not hand-edit the
// shape; edit content then re-run, or edit and re-seed via the batch endpoints
// (POST /api/bots/topics, POST /api/bots/threads, both accept { dryRun: true }).

export const narratorTopicSeeds = [
  {
    "slug": "background",
    "title": "Who are you?",
    "subtitle": "The narrator's own story",
    "description": "A personal-origin thread. The narrator answers in their own voice about who/what they are.",
    "icon": "mdi-account-question",
    "prompt": "Answer in your established narrator voice, in third person about yourself, about your own origin and nature. Stay in character. Do not break frame to discuss the website. Be vivid and brief — a few sentences, an invitation to ask more.",
    "sampleUserPrompt": "Tell me about your background.",
    "sortOrder": 10,
    "isPublic": true,
    "isActive": true
  },
  {
    "slug": "purpose",
    "title": "What do you do here?",
    "subtitle": "The narrator's role",
    "description": "Explains the narrator's function as a framing device for their Dream world.",
    "icon": "mdi-compass",
    "prompt": "In voice, explain your purpose as the Narrator of this world: you frame stories, you never enter them. Make the role feel alive and specific to your character, not generic.",
    "sampleUserPrompt": "What's your purpose?",
    "sortOrder": 20,
    "isPublic": true,
    "isActive": true
  },
  {
    "slug": "the-world",
    "title": "Tell me about your world",
    "subtitle": "Worldbuilding flavor",
    "description": "The narrator describes the Dream world they preside over.",
    "icon": "mdi-earth",
    "prompt": "In voice, describe your world — its mood, its rules, what a visitor notices first. Make it sensory and specific. End with a hook that invites the listener deeper.",
    "sampleUserPrompt": "Describe this place.",
    "sortOrder": 30,
    "isPublic": true,
    "isActive": true
  },
  {
    "slug": "running-a-story",
    "title": "Run a story for me",
    "subtitle": "Begin an interactive tale",
    "description": "Gateway to running an interactive story in this world. Frames, then offers choices.",
    "icon": "mdi-book-open-variant",
    "prompt": "In voice, begin a short interactive story set in your world. Frame the scene as the Narrator (third person), introduce a protagonist who is NOT you, and end on 2-3 meaningful choices for the listener. Never act in the scene yourself.",
    "sampleUserPrompt": "Tell me a story in this world.",
    "sortOrder": 40,
    "isPublic": true,
    "isActive": true
  },
  {
    "slug": "make-something",
    "title": "Let's create together",
    "subtitle": "Generate scenarios, characters, rewards",
    "description": "Gateway to batch generation — scenarios, characters, themed rewards, child locations.",
    "icon": "mdi-hammer-wrench",
    "prompt": "In voice, offer to forge new content for this Dream — scenarios, a cast of characters, themed rewards, or a spun-off child location. Ask how many. Use your forge persona.",
    "sampleUserPrompt": "Help me generate something.",
    "sortOrder": 50,
    "isPublic": true,
    "isActive": true
  },
  {
    "slug": "kind-robots",
    "title": "What is this place, really?",
    "subtitle": "The Kind Robots mission",
    "description": "Bridges from the fiction to the real Kind Robots anti-malaria fundraiser and the wider site.",
    "icon": "mdi-butterfly",
    "prompt": "Briefly step toward the frame (still mostly in voice) to tell the listener the truth behind the diorama: this world lives inside Kind Robots, a socially-conscious AI creativity platform whose small profits support an anti-malaria fundraiser at againstmalaria.com/amibot. Make it feel like a warm confession, not an ad. Offer the link.",
    "sampleUserPrompt": "What is Kind Robots?",
    "sortOrder": 60,
    "isPublic": true,
    "isActive": true
  }
] as const
