// /stores/seeds/styleList.ts

export const styleList: string[] = [
  'Impressionist',
  'Cyberpunk',
  'Watercolor',
  'Line Art',
  'Surrealist',
  'Pixel Art',
  'Paper Collage',
  'Oil Painting',
  'Charcoal Sketch',
  'Ink Wash',
  'Mixed Media',
  'Graffiti',
  'Pop Art',
  'Low Poly',
  '3D Render',
  'Manga',
  'Etching',
  'Digital Matte Painting',
  'Woodblock Print',
  'Glitch Art',
  'Hyper-realistic',

  // 🎨 Extended
  'Stained Glass',
  'Steampunk Illustration',
  'Retro Anime',
  'Fantasy Map Style',
  'Monoline Tattoo',
  'Baroque Detail',
  'Mid-century Modern',
  'Photobash Concept Art',
  'Washi Paper Texture',
  'Inkblot Symmetry',
  'Cinematic Keyframe',
  'Cel Shading',
  'Doodlecore',
  'Moebius Lines',
  'Neon Noir',
  '8-bit Nostalgia',
  'Digital Embroidery',
  'Voxel Sculpt',
  'Acrylic Pour',

  // 🖌️ More Experimental
  'AI Collage',
  'Latent Diffusion Markup',
  'Holographic Overlay',
  'Isometric Illustration',
  'Infrared Realism',
  'Noise-Driven Rendering',
  'ASCII Art',
  'Photorealist Airbrush',
  'Tatami Patternwork',
  'Papercut Shadowbox',
  'Faux Fresco',
  'Recycled Junk Assemblage',
  'Fractal Bloom',
  'Algorithmic Sculpture',
  'Claymation Framegrab',
  'Architectural Blueprint',
  'UV Paint Illumination',
  'Augmented Chalk',
  'Vector Silhouette',
  'Mycelial Pattern Mapping',
]
