// /stores/seeds/themeList.ts

export const themeList: string[] = [
  'Dreams',
  'Nightmares',
  'Techno-utopia',
  'Nature Reclaimed',
  'Mythic Futures',
  'Post-Human Ritual',
  'Lost Civilizations',
  'Digital Ghosts',
  'Fungal Kingdoms',
  'Bioluminescent Depths',
  'Desert Monasteries',
  'Floating Cities',
  'Neo-Arcadia',
  'Quantum Gardens',
  'Forgotten Gods',
  'Alien Carnival',
  'Broken Time',
  'Sacred Geometry',
  'Eternal Sunset',
  'Synthetic Eden',

  // ✨ New themes added below
  'Holographic Memories',
  'Interstellar Pilgrimage',
  'Clockwork Forests',
  'Abandoned Megastructures',
  'Solarpunk Cathedrals',
  'Dream-Eating Beasts',
  'Neon Tombs',
  'Fractal Realms',
  'Mechanical Gardens',
  'Ancient Space Temples',
  'Whispering Satellites',
  'Time-Bent Shrines',
  'Overgrown Robots',
  'Prismatic Fungi',
  'Cosmic Shipwrecks',
  'Submerged Skyscrapers',
  'Digital Reincarnation',
  'Mycelial Networks',
  'Cursed Archives',
  'Echoes of the Deep',

  // 🌌 Bonus mix
  'Crystalline Jungles',
  'Sacrificial Engines',
  'Parallel Monasteries',
  'Babel Fractures',
  'Mothlight Rituals',
  'Anti-Sunrise',
  'Virtual Afterlife',
  'Luminous Catacombs',
  'Emotional Algorithms',
  'The Library Between Dimensions',
  'Orbital Swamps',
  'Ashfall Cities',
  'Hollow Cosmos',
  'Reverse Gravity Wells',
  'Choral Storms',
  'Tethered Planets',
  'Nocturnal Sanctuaries',
  'Zero-G Opera',
  'Spore Choirs',
  'Fractured Utopias',
]
