// /stores/seeds/validCheckpoints.ts

import type { Resource } from '@prisma/client'

export const validCheckpoints: Partial<Resource>[] = [
  {
    name: 'dreamshaperXL_v21TurboDPMSDE.safetensors',
    customLabel: 'dreamshaper XL',
    localPath: 'SDXL/dreamshaperXL_v21TurboDPMSDE.safetensors',
    description: 'New SDXL Model',
    generation: 'SDXL',
    isMature: false,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'sdxlUnstableDiffusers_nihilmania.safetensors',
    customLabel: 'SDXL Unstable Diffusers',
    localPath: 'SDXL/sdxlUnstableDiffusers_nihilmania.safetensors',
    description: 'New SDXL Model',
    generation: 'SDXL',
    isMature: false,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'duchaitenStylelikeme_v15Fp16NoEma.safetensors',
    customLabel: 'Duchaiten Stylelikeme',
    localPath: 'SDXL/duchaitenStylelikeme_v15Fp16NoEma.safetensors',
    description: 'New SDXL Model',
    generation: 'SDXL',
    isMature: false,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'duchaitendreamworld_V30.safetensors',
    customLabel: 'Duchaiten Dreamworld',
    localPath: 'SDXL/duchaitendreamworld_V30.safetensors',
    description: 'New SDXL Model',
    generation: 'SDXL',
    isMature: false,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'duchaitenAiartSDXL_v33515.safetensors',
    customLabel: 'Duchaiten AI Art SDXL',
    localPath: 'SDXL/duchaitenAiartSDXL_v33515.safetensors',
    description: 'New SDXL Model',
    generation: 'SDXL',
    isMature: false,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'RealitiesEdgeXLLIGHTNING_TURBOV7.safetensors',
    customLabel: 'Realities Edge XL',
    localPath: 'SDXL/RealitiesEdgeXLLIGHTNING_TURBOV7.safetensors',
    description: 'New SDXL Model',
    generation: 'SDXL',
    isMature: false,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'samaritan3dCartoon_v40SDXL.safetensors',
    customLabel: 'Samaritan 3d Cartoon',
    localPath: 'SDXL/samaritan3dCartoon_v40SDXL.safetensors',
    description: 'New SDXL Model',
    generation: 'SDXL',
    isMature: false,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'darkSushiMixMix_colorful.safetensors',
    customLabel: 'DarkSushi Colorful Mix',
    localPath: '1.5/darkSushiMixMix_colorful.safetensors',
    description: 'Auto-imported from 1.5 model folder.',
    generation: '1.5',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'epicrealism_naturalSinRC1VAE.safetensors',
    customLabel: 'EpicRealism Natural',
    localPath: '1.5/epicrealism_naturalSinRC1VAE.safetensors',
    description: 'Auto-imported from 1.5 model folder.',
    generation: '1.5',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'ponyFaetality_v11.safetensors [499513276a]',
    customLabel: 'Pony Faetality',
    localPath: '_Pony/ponyFaetality_v11.safetensors',
    description: 'Auto-imported from _Pony model folder.',
    generation: 'Pony',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'cyberrealisticPony_v61.safetensors',
    customLabel: 'CyberRealistic Pony',
    localPath: 'ARCHIVE/CyberRealistic_Pony/cyberrealisticPony_v61.safetensors',
    description: 'Auto-imported from ARCHIVE model folder.',
    generation: 'ARCHIVE',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'revAnimated_v2Rebirth.safetensors',
    customLabel: 'Rev Animated Rebirth',
    localPath: 'ARCHIVE/revAnimated_v2Rebirth.safetensors',
    description: 'Auto-imported from ARCHIVE model folder.',
    generation: 'ARCHIVE',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'cartoonArcadiaSDXLSD1_v2.safetensors [eb2b3e9a5f]',
    customLabel: 'Cartoon Arcadia',
    localPath: 'cartoonArcadiaSDXLSD1_v2.safetensors',
    description: 'Auto-imported from base model folder.',
    generation: 'base',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'disneyrealcartoonmix_v10.1.safetensors [d803b444ed]',
    customLabel: 'DisneyReal Cartoonmix',
    localPath: 'disneyrealcartoonmix_v10.1.safetensors',
    description: 'Auto-imported from base model folder.',
    generation: 'base',
    isMature: false,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'hotart_3SPO.safetensors',
    customLabel: 'Hot Art',
    localPath: 'hotart_3SPO.safetensors',
    description: 'Auto-imported from base model folder.',
    generation: 'base',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'ivisionIllustration_ivision10.safetensors',
    customLabel: 'iVision Illustration',
    localPath: 'ivisionIllustration_ivision10.safetensors',
    description: 'Auto-imported from base model folder.',
    generation: 'base',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'realcartoonPony_v1.safetensors',
    customLabel: 'RealCartoon Pony',
    localPath: 'realcartoonPony_v1.safetensors [2295809170]',
    description: 'Auto-imported from base model folder.',
    generation: 'base',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'bigLove_xl25.safetensors',
    customLabel: 'Big Love',
    localPath: 'SDXL/bigLove_xl25.safetensors [19447d345a]',
    description: 'Auto-imported from SDXL model folder.',
    generation: 'SDXL',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'biglust17_v17.safetensors',
    customLabel: 'Big Lust17',
    localPath: 'SDXL/biglust17_v17.safetensors',
    description: 'Auto-imported from SDXL model folder.',
    generation: 'SDXL',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'lustifySDXLNSFW_oltFIXEDTEXTURES.safetensors',
    customLabel: 'Lustify',
    localPath: 'SDXL/lustifySDXLNSFW_oltFIXEDTEXTURES.safetensors',
    description: 'Auto-imported from SDXL model folder.',
    generation: 'SDXL',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'duskMixXLIllustration_v15.safetensors',
    customLabel: 'DuskMix XL Illustration',
    localPath: 'SDXL/tier2/duskMixXLIllustration_v15.safetensors',
    description: 'Auto-imported from SDXL model folder.',
    generation: 'SDXL',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
  {
    name: 'ThinkDiffusionXL.safetensors',
    customLabel: 'Think Diffusion',
    localPath: 'SDXL/tier2/ThinkDiffusionXL.safetensors [a21c9949ef]',
    description: 'Auto-imported from SDXL model folder.',
    generation: 'SDXL',
    isMature: true,
    resourceType: 'CHECKPOINT',
    userId: 1,
  },
]
