// /stores/seeds/validSamplers.ts

import type { Resource } from '@prisma/client'

export const validSamplers: Partial<Resource>[] = [
  {
    name: 'DPM++ 2M Karras',
    resourceType: 'SAMPLER',
    isMature: false,
    userId: 1,
  },
  {
    name: 'DPM++ SDE Karras',
    resourceType: 'SAMPLER',
    isMature: false,
    userId: 1,
  },
  {
    name: 'DPM++ 2M SDE Exponential',
    resourceType: 'SAMPLER',
    isMature: false,
    userId: 1,
  },
  {
    name: 'DPM++ 2M SDE Karras',
    resourceType: 'SAMPLER',
    isMature: false,
    userId: 1,
  },
  { name: 'Euler a', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'Euler', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'LMS', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'Heun', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'DPM2', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'DPM2 a', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'DPM++ 2S a', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'DPM++ 2M', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'DPM++ SDE', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'DPM++ 2M SDE', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  {
    name: 'DPM++ 2M SDE Heun',
    resourceType: 'SAMPLER',
    isMature: false,
    userId: 1,
  },
  {
    name: 'DPM++ 2M SDE Heun Karras',
    resourceType: 'SAMPLER',
    isMature: false,
    userId: 1,
  },
  {
    name: 'DPM++ 2M SDE Heun Exponential',
    resourceType: 'SAMPLER',
    isMature: false,
    userId: 1,
  },
  { name: 'DPM++ 3M SDE', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  {
    name: 'DPM++ 3M SDE Karras',
    resourceType: 'SAMPLER',
    isMature: false,
    userId: 1,
  },
  {
    name: 'DPM++ 3M SDE Exponential',
    resourceType: 'SAMPLER',
    isMature: false,
    userId: 1,
  },
  { name: 'DPM fast', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'DPM adaptive', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'LMS Karras', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'DPM2 Karras', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  {
    name: 'DPM2 a Karras',
    resourceType: 'SAMPLER',
    isMature: false,
    userId: 1,
  },
  {
    name: 'DPM++ 2S a Karras',
    resourceType: 'SAMPLER',
    isMature: false,
    userId: 1,
  },
  { name: 'Restart', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'DDIM', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'PLMS', resourceType: 'SAMPLER', isMature: false, userId: 1 },
  { name: 'UniPC', resourceType: 'SAMPLER', isMature: false, userId: 1 },
]
