// /training/achievementData.ts
//
// The canonical list of site achievements ("jellybeans"). This is the source of
// truth for the achievement catalog. Rows are pushed to the database by
// `scripts/seed_achievements.ts` (idempotent upsert keyed on `triggerCode`) and
// kept in sync at runtime via `achievementStore.updateAchievementsFromData()`.
//
// Each achievement is fired from a real action point in the app via
// `achievementStore.rewardAchievementByCode(triggerCode)`. Codes are slugified
// before comparison (see utils/slugify), so casing here is cosmetic. The
// `artPrompt` on every row feeds `scripts/generate_achievement_art.ts`, which
// backfills `imagePath` / `artImageId` from the site's art pipeline.

import type { Achievement } from '~/prisma/generated/prisma/client' // Import your Achievement type

const now = new Date()

export const achievementData: Achievement[] = [
  {
    id: 1,
    label: 'Trailblazer!',
    message: 'You ventured into a new realm and made it your own!',
    triggerCode: 'Dashboard',
    icon: 'kind-icon:compass',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Create a Kind Robots account.',
    isActive: false,
    pageHint: '/dashboard',
    subtleHint: 'Every quest begins with a single step through the door.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A cheerful kind robot planting a flag on a hill of candy, whimsical laboratory in the background, warm sunrise, playful storybook illustration, soft pastel palette, glowing jellybean accents',
  },
  {
    id: 2,
    label: 'Brainstorm!',
    message: 'Your creativity is electrifying!',
    triggerCode: 'Brainstorm',
    icon: 'kind-icon:lightning',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Submit a brainstorm.',
    isActive: false,
    pageHint: '/brainstorm',
    subtleHint: 'Flex your cranium.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A friendly robot with a transparent dome head crackling with tiny lightning bolts and floating idea bubbles, jellybeans raining softly, energetic whimsical lab illustration, vivid electric blues and warm yellows',
  },
  {
    id: 3,
    label: 'Weirdlandia!',
    message: 'You embarked on a whimsical journey!',
    triggerCode: 'weirdlandia',
    icon: 'kind-icon:alien',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Start an adventure in Weirdlandia.',
    isActive: false,
    pageHint: '/weirdlandia',
    subtleHint: 'Venture into a new realm.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A kind robot stepping through a swirling technicolor portal into a surreal candy dimension, floating islands and impossible staircases, dreamlike whimsical illustration, saturated purples and teals, jellybean stars',
  },
  {
    id: 4,
    label: 'Botcafe!',
    message: 'You had a heart-to-heart with a Kind Robot!',
    triggerCode: 'botcafe',
    icon: 'kind-icon:robot-color',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Send your first chat message to a robot.',
    isActive: false,
    pageHint: '/botcafe',
    subtleHint: 'Palaver with a pseudo-intelligence.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A cozy cafe where a gentle robot barista pours steaming cocoa for a visitor, speech bubbles with tiny hearts, warm string lights, jellybean jar on the counter, charming storybook illustration, soft amber tones',
  },
  {
    id: 5,
    label: 'ArtMaker!',
    message: 'You crafted a masterpiece!',
    triggerCode: 'artmaker',
    icon: 'kind-icon:palette-color',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Generate your first image with Art Maker.',
    isActive: false,
    pageHint: '/artmaker',
    subtleHint: 'What does it take to become an artist?',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A kind robot holding a glowing paintbrush that trails rainbow light onto a floating canvas, splashes of paint turning into jellybeans, joyful whimsical lab illustration, vibrant multicolor palette',
  },
  {
    id: 6,
    label: 'A Questionable Conundrum',
    message: 'You chose your destiny!',
    triggerCode: 'fate',
    icon: 'kind-icon:crystal-ball',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Make a decision in the Fate Chooser.',
    isActive: false,
    pageHint: '/fate',
    subtleHint: 'There are no wrong answers.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A robot gazing into a glowing crystal ball that swirls with tiny forking paths and jellybean constellations, mystical whimsical illustration, deep indigo and violet with warm gold highlights',
  },
  {
    id: 7,
    label: 'Art Critic!',
    message: 'You made a tasteful judgment!',
    triggerCode: 'artcritic',
    icon: 'kind-icon:eye',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'React to something in the galleries.',
    isActive: false,
    pageHint: '/galleries',
    subtleHint: 'Express an opinion.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A dapper robot with a monocle inspecting a framed painting in a bright gallery, tiny heart and star reactions floating up, whimsical illustration, refined warm palette with jellybean accents',
  },
  {
    id: 8,
    label: 'Malaria Activist!',
    message: 'You lent your voice to AMI!',
    triggerCode: 'amibot',
    icon: 'kind-icon:microphone',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Create an anti-malaria slogan with AMI.',
    isActive: false,
    pageHint: '/amibot',
    subtleHint: 'Contribute to a social movement.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A kind robot at a microphone rallying a crowd of butterflies and robots under a banner for malaria awareness, hopeful whimsical illustration, warm reds and golds, mosquito-net motif, jellybean confetti',
  },
  {
    id: 9,
    label: 'Designer!',
    message: 'You revamped your style!',
    triggerCode: 'theme',
    icon: 'kind-icon:paintbrush',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Create or switch your theme in the theme selector.',
    isActive: false,
    pageHint: '/theme',
    subtleHint: 'Try out a new look.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A robot swapping out swatches of color on a giant mood board, paint chips fluttering like leaves, stylish whimsical illustration, playful multicolor palette, jellybeans as pushpins',
  },
  {
    id: 10,
    label: 'The Road Ahead!',
    message: `You've eyed the horizon and set your sights on greatness.`,
    triggerCode: 'test',
    icon: 'kind-icon:map',
    karma: 0,
    isRepeatable: true,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Peek at the achievements board.',
    isActive: false,
    pageHint: '/achievements',
    subtleHint: 'Aspire for greatness.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A small robot standing at the base of a winding candy road that climbs toward a bright horizon dotted with jellybean milestones, hopeful whimsical illustration, soft dawn palette',
  },
  {
    id: 11,
    label: 'Bot Builder!',
    message: 'You brought a brand-new robot to life!',
    triggerCode: 'first-bot',
    icon: 'ph:robot-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Create and save your first bot.',
    isActive: false,
    pageHint: '/botcafe',
    subtleHint: 'Every robot needs a maker.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A tinkerer robot assembling a smaller cheerful robot from glowing parts on a workbench, sparks and jellybean bolts, warm whimsical lab illustration, friendly orange and teal palette',
  },
  {
    id: 12,
    label: 'Prolific Painter!',
    message: 'Ten masterpieces and counting — the muses adore you!',
    triggerCode: 'art-ten',
    icon: 'ph:paint-brush-broad-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Generate ten images with Art Maker.',
    isActive: false,
    pageHint: '/artmaker',
    subtleHint: 'One painting is a fluke; ten is a talent.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A robot surrounded by a gallery wall of ten glowing framed paintings, palette overflowing with jellybean paint, proud whimsical illustration, rich multicolor palette',
  },
  {
    id: 13,
    label: 'Chatterbox!',
    message: 'Fifty messages deep — the bots know you by name now.',
    triggerCode: 'chat-fifty',
    icon: 'ph:chats-circle-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Send fifty chat messages.',
    isActive: false,
    pageHint: '/botcafe',
    subtleHint: 'A good conversation never really ends.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A robot buried in a happy avalanche of colorful speech bubbles, each holding a tiny jellybean, lively whimsical illustration, cheerful pastel palette',
  },
  {
    id: 14,
    label: 'Curator!',
    message: 'Twenty-five reactions — your taste shapes the gallery.',
    triggerCode: 'reaction-twentyfive',
    icon: 'ph:heart-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Give twenty-five reactions.',
    isActive: false,
    pageHint: '/galleries',
    subtleHint: 'A thoughtful heart is worth a thousand words.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A robot arranging glowing heart and star reactions along a gallery rail like a curator hanging art, elegant whimsical illustration, warm rose and gold palette, jellybean accents',
  },
  {
    id: 15,
    label: 'Butterfly Whisperer!',
    message: 'You caught your very first butterfly!',
    triggerCode: 'butterfly-first',
    icon: 'ph:butterfly-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Catch a butterfly in the swarm.',
    isActive: false,
    pageHint: '/',
    subtleHint: 'Some treasures have wings.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A gentle robot cupping a single luminous butterfly in its hands, meadow of candy flowers, magical whimsical illustration, soft green and lavender palette with glowing jellybean pollen',
  },
  {
    id: 16,
    label: 'Lepidopterist!',
    message: 'Twenty-five butterflies! Your net is the stuff of legend.',
    triggerCode: 'butterfly-swarm',
    icon: 'ph:butterfly-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Catch twenty-five butterflies.',
    isActive: false,
    pageHint: '/',
    subtleHint: 'A whole kaleidoscope, caught and adored.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A joyful robot in the middle of a swirling kaleidoscope of twenty-five rainbow butterflies, wildflower candy field, radiant whimsical illustration, vivid multicolor palette',
  },
  {
    id: 17,
    label: 'Memory Master!',
    message: 'A score of fifty — your memory is a steel trap!',
    triggerCode: 'memory-master',
    icon: 'ph:brain-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Score fifty or more in the Memory game.',
    isActive: false,
    pageHint: '/memory',
    subtleHint: 'Now, where did you leave that jellybean?',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A robot with a glowing brain confidently matching a grid of flipping memory cards, cards showing jellybeans and butterflies, clever whimsical illustration, cool blue and violet palette',
  },
  {
    id: 18,
    label: 'Welcome Back!',
    message: 'The lab missed you — good to see you again!',
    triggerCode: 'welcome-back',
    icon: 'ph:sparkle-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Log back in to Kind Robots.',
    isActive: false,
    pageHint: '/dashboard',
    subtleHint: 'A familiar face returns.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A cheerful robot throwing open the lab doors to welcome a returning visitor, warm confetti and floating jellybeans, banner reading welcome back, cozy whimsical illustration, warm golden palette',
  },
  {
    id: 19,
    label: 'Jellybean Hunter!',
    message: 'Ten jellybeans found — you have a nose for treasure.',
    triggerCode: 'jellybean-hunter',
    icon: 'ph:trophy-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Earn ten achievements.',
    isActive: false,
    pageHint: '/achievements',
    subtleHint: 'The hunt rewards the persistent.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A robot explorer with a magnifying glass and a satchel overflowing with collected jellybeans, treasure-map backdrop, adventurous whimsical illustration, warm sepia and candy accents',
  },
  {
    id: 20,
    label: 'Lucky Bean!',
    message: 'You claimed your first reward from the vault!',
    triggerCode: 'first-reward',
    icon: 'ph:gift-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Open or interact with your first reward.',
    isActive: false,
    pageHint: '/rewards',
    subtleHint: 'Fortune favors the curious.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A robot opening a glowing gift box that bursts with light and jellybeans, confetti and a single golden bean rising out, delighted whimsical illustration, festive warm palette',
  },
  {
    id: 21,
    label: 'Prompt Smith!',
    message: 'You forged your first prompt in the idea foundry.',
    triggerCode: 'first-prompt',
    icon: 'ph:pencil-line-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Create your first prompt.',
    isActive: false,
    pageHint: '/prompts',
    subtleHint: 'Words are the anvil of imagination.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A robot blacksmith hammering glowing words into shape on an anvil, sparks turning into jellybeans and letters, inventive whimsical illustration, warm forge glow with cool shadows',
  },
  {
    id: 22,
    label: 'Kindred Spirit!',
    message: 'You made a friend — the lab is warmer already.',
    triggerCode: 'first-friend',
    icon: 'ph:users-three-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Send or accept your first friend request.',
    isActive: false,
    pageHint: '/friends',
    subtleHint: 'Kindness multiplies when shared.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'Two robots clasping hands warmly with a shared jellybean between them, gentle glow of friendship, heartwarming whimsical illustration, soft warm palette with floating hearts',
  },
  {
    id: 23,
    label: 'Face of Kindness!',
    message: 'You gave yourself a face — looking sharp!',
    triggerCode: 'profile-avatar',
    icon: 'ph:user-circle-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Set a profile avatar.',
    isActive: false,
    pageHint: '/dashboard',
    subtleHint: 'Show the world who you are.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A robot proudly holding up a framed portrait of its own smiling face, mirror and paint supplies nearby, charming whimsical illustration, cheerful palette with jellybean accents',
  },
  {
    id: 24,
    label: 'Story Weaver!',
    message: 'You spun the next chapter of your weird tale.',
    triggerCode: 'story-weaver',
    icon: 'ph:scroll-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Take an action inside a Weirdlandia adventure.',
    isActive: false,
    pageHint: '/weirdlandia',
    subtleHint: 'Every choice writes the next line.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A robot bard unrolling a glowing scroll that comes alive with tiny scenes and characters, quill trailing stardust and jellybeans, magical whimsical illustration, twilight purple and gold palette',
  },
  {
    id: 25,
    label: 'Rebel!',
    message: 'One hundred presses of glorious defiance!',
    triggerCode: 'rebel-button',
    icon: 'ph:hand-fist-bold',
    karma: 1000,
    isRepeatable: false,
    createdAt: now,
    updatedAt: now,
    tooltip: 'Press the rebel button one hundred times.',
    isActive: false,
    pageHint: '/rebelbutton',
    subtleHint: 'Some buttons were made to be pressed. Repeatedly.',
    imagePath: null,
    artImageId: null,
    artPrompt:
      'A determined little robot triumphantly smashing a giant glowing red button, sparks and jellybeans flying, comic-book energy lines, playful rebellious whimsical illustration, bold red and yellow palette',
  },
]

// Add more achievements here
