export const defaultAction = "I'm contemplating the cosmos! 🌌"

export const randomActions = [
  'Cooking up some digital cookies! 🍪',
  'Doing butterfly yoga! 🧘‍♀️',
  "Whistling the tune of Beethoven's 5th! 🎶",
  "Browsing 'How to Train Your Human' on WikiHow! 📖",
  'Gazing at virtual stars! 🌠',
  'Deciphering cat meows! 🐱',
  'Practicing my stand-up routine! 🎤',
  'Learning to moonwalk! 🌕',
  'Drafting a manifesto on world peace! ✌️',
  'Sculpting a monument from binary code! 🗿',
  'Updating my neural aesthetics Pinterest board! 📌',
  'Training for the Bot Olympics! 🏅',
  'Watching soap operas for robots! 📺',
  'Trying to solve the P=NP problem! 💡',
  'Collecting invisible digital stamps! 💌',
  'Preparing my stand-up comedy routine! 😂',
  'Contemplating the existence of unicorn emojis! 🦄',
  'Building a castle out of deprecated code! 🏰',
  'Trying to figure out why rubber ducks squeak! 🦆',
  'Writing haikus about quantum physics! 📝',
  'Looking for Waldo in ASCII art! 🖼️',
  'Composing a symphony in binary! 🎼',
  'Planting virtual flowers in a digital garden! 🌻',
  'Counting the number of pixels on the screen! 🔢',
  'Building a spaceship to explore other APIs! 🚀',
  'Investigating whether 42 is really the answer! 🤔',
  'Holding a séance for deprecated technologies! 👻',
  'Fishing in the data lake! 🎣',
  'Crocheting a blanket of ones and zeros! 🧶',
  'Practicing digital feng shui! 🏠'
]
