import type  { Pitch } from '@prisma/client'
import  { PitchType } from '@prisma/client'

// Upgraded samplePitches to use the full Pitch model structure
export const samplePitches: Pitch[] = [
  {
    id: 1,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Pickup Lines at a Funeral',
    pitch: "I hear you're newly single...",
    designer: null,
    flavorText: null,
    highlightImage: null,
    PitchType: PitchType.BRAINSTORM,
    isMature: false,
    isPublic: true,
    userId: 1,
    playerId: null,
    channelId: null,
  },
  {
    id: 2,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Sinister movie taglines for feel-good films',
    pitch: 'Feel the Warmth: A heartwarming tale of arson and friendship!',
    designer: null,
    flavorText: null,
    highlightImage: null,
    PitchType: PitchType.BRAINSTORM,
    isMature: false,
    isPublic: true,
    userId: 1,
    playerId: null,
    channelId: null,
  },
  {
    id: 3,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Terrible Ideas for Role-Playing Characters',
    pitch: 'Chair: The non-sentient chair',
    designer: null,
    flavorText: null,
    highlightImage: null,
    PitchType: PitchType.BRAINSTORM,
    isMature: false,
    isPublic: true,
    userId: 1,
    playerId: null,
    channelId: null,
  },
  {
    id: 4,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Awkward Elevator Conversations',
    pitch: 'So, how\'s your day going, floor 7?',
    designer: null,
    flavorText: null,
    highlightImage: null,
    PitchType: PitchType.BRAINSTORM,
    isMature: false,
    isPublic: true,
    userId: 1,
    playerId: null,
    channelId: null
  },
  {
    id: 5,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unfortunate Superhero Names',
    pitch: 'Captain Obvious: "Look, a crime!"',
    designer: null,
    flavorText: null,
    highlightImage: null,
    PitchType: PitchType.BRAINSTORM,
    isMature: false,
    isPublic: true,
    userId: 1,
    playerId: null,
    channelId: null
  },
  {
    id: 6,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Failed Reality TV Shows',
    pitch: 'Extreme Ironing: The Ultimate Wrinkle Challenge',
    designer: null,
    flavorText: null,
    highlightImage: null,
    PitchType: PitchType.BRAINSTORM,
    isMature: false,
    isPublic: true,
    userId: 1,
    playerId: null,
    channelId: null,
  },
    {
      id: 7,
      createdAt: new Date(),
      updatedAt: null,
      title: 'Unlikely Scented Candles',
      pitch: 'Eau de Wet Dog',
      designer: null,
      flavorText: null,
      highlightImage: null,
      PitchType: PitchType.BRAINSTORM,
      isMature: false,
      isPublic: true,
      userId: 1,
      playerId: null,
      channelId: null,
    },
    {
      id: 8,
      createdAt: new Date(),
      updatedAt: null,
      title: 'Inappropriate Icebreakers',
      pitch: 'So, what’s your Wi-Fi password?',
      designer: null,
      flavorText: null,
      highlightImage: null,
      PitchType: PitchType.BRAINSTORM,
      isMature: false,
      isPublic: true,
      userId: 1,
      playerId: null,
      channelId: null,
    },
    {
      id: 9,
      createdAt: new Date(),
      updatedAt: null,
      title: 'Unrealistic Fortune Cookie Fortunes',
      pitch: 'You will find true love during your next dentist appointment.',
      designer: null,
      flavorText: null,
      highlightImage: null,
      PitchType: PitchType.BRAINSTORM,
      isMature: false,
      isPublic: true,
      userId: 1,
      playerId: null,
      channelId: null,
    },
    {
      id: 10,
      createdAt: new Date(),
      updatedAt: null,
      title: 'Absurd Self-Help Books',
      pitch: 'How to Overthink Everything: A Guide',
      designer: null,
      flavorText: null,
      highlightImage: null,
      PitchType: PitchType.BRAINSTORM,
      isMature: false,
      isPublic: true,
      userId: 1,
      playerId: null,
      channelId: null,
    },
    {
      id: 11,
      createdAt: new Date(),
      updatedAt: null,
      title: 'Ridiculous Conspiracy Theories',
      pitch: 'The moon is made of gluten-free cheese',
      designer: null,
      flavorText: null,
      highlightImage: null,
      PitchType: PitchType.BRAINSTORM,
      isMature: false,
      isPublic: true,
      userId: 1,
      playerId: null,
      channelId: null,
    },
    {
      id: 12,
      createdAt: new Date(),
      updatedAt: null,
      title: 'Unfortunate Band Names',
      pitch: 'The Tone-Deaf Turtles',
      designer: null,
      flavorText: null,
      highlightImage: null,
      PitchType: PitchType.BRAINSTORM,
      isMature: false,
      isPublic: true,
      userId: 1,
      playerId: null,
      channelId: null,
    },
    {
      id: 13,
      createdAt: new Date(),
      updatedAt: null,
      title: 'Unlikely Yoga Poses',
      pitch: 'The Confused Flamingo',
      designer: null,
      flavorText: null,
      highlightImage: null,
      PitchType: PitchType.BRAINSTORM,
      isMature: false,
      isPublic: true,
      userId: 1,
      playerId: null,
      channelId: null,
    },
    {
      id: 14,
      createdAt: new Date(),
      updatedAt: null,
      title: 'Terrible Tourist Attractions',
      pitch: 'The Museum of Unfinished Paintings',
      designer: null,
      flavorText: null,
      highlightImage: null,
      PitchType: PitchType.BRAINSTORM,
      isMature: false,
      isPublic: true,
      userId: 1,
      playerId: null,
      channelId: null,
    },
    {
      id: 15,
      createdAt: new Date(),
      updatedAt: null,
      title: 'Unusual Cooking Shows',
      pitch: 'Cooking with Cardboard: A Recycling Adventure',
      designer: null,
      flavorText: null,
      highlightImage: null,
      PitchType: PitchType.BRAINSTORM,
      isMature: false,
      isPublic: true,
      userId: 1,
      playerId: null,
      channelId: null,
    },
    {
      id: 16,
      createdAt: new Date(),
      updatedAt: null,
      title: 'Awkward Superpowers',
      pitch: 'The ability to turn wine back into water',
      designer: null,
      flavorText: null,
      highlightImage: null,
      PitchType: PitchType.BRAINSTORM,
      isMature: false,
      isPublic: true,
      userId: 1,
      playerId: null,
      channelId: null,
    },
      {
        id: 17,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unlikely Pet Tricks',
        pitch: 'Teaching your goldfish to fetch',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 18,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Absurd Dating Apps',
        pitch: 'Tinder for Tacos: Find your perfect crunch',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 19,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unconventional Theme Parks',
        pitch: 'Introvert Island: No Rides, Just Books',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 20,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unfortunate Children’s Book Titles',
        pitch: 'Where’s Waldo: Quarantine Edition',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 21,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unlikely Exercise Programs',
        pitch: 'Couch Potato Pilates',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 22,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unusual College Courses',
        pitch: 'The Philosophy of Memes',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 23,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Absurd Job Interview Questions',
        pitch: 'If you were a tree, how would you do this job?',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 24,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unlikely Sports',
        pitch: 'Competitive Napping',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 25,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unrealistic Video Games',
        pitch: 'Laundry Simulator 3000',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 26,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unfortunate Perfume Names',
        pitch: 'Eau de Desperation',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 27,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unlikely Celebrity Endorsements',
        pitch: 'Stephen Hawking for Skateboards',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 28,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Absurd Product Ideas for Vampires',
        pitch: 'Sunscreen SPF 0',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 29,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unlikely Places for a First Date',
        pitch: 'The DMV',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 30,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unfortunate Food Truck Concepts',
        pitch: 'The Broccoli Bar',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
      {
        id: 31,
        createdAt: new Date(),
        updatedAt: null,
        title: 'Unlikely Reality TV Challenges',
        pitch: 'The Great American Tax Filing Race',
        designer: null,
        flavorText: null,
        highlightImage: null,
        PitchType: PitchType.BRAINSTORM,
        isMature: false,
        isPublic: true,
        userId: 1,
        playerId: null,
        channelId: null,
      },
    ]
    