import type { Dream } from '~/prisma/generated/prisma/client'
import { DreamType, CreationSource } from '~/prisma/generated/prisma/client'

// Migrated from samplePitches: Pitch was absorbed into the Dream model.
// All entries use DreamType.BRAINSTORM to match the original PitchType.BRAINSTORM.
export const sampleDreams: Dream[] = [
  {
    id: 1,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Pickup Lines at a Funeral',
    slug: 'pickup-lines-at-a-funeral',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: "I hear you're newly single...",
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 2,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Sinister movie taglines for feel-good films',
    slug: 'sinister-movie-taglines-for-feel-good-films',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Feel the Warmth: A heartwarming tale of arson and friendship!',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 3,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Terrible Ideas for Role-Playing Characters',
    slug: 'terrible-ideas-for-role-playing-characters',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Chair: The non-sentient chair',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 4,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Awkward Elevator Conversations',
    slug: 'awkward-elevator-conversations',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: "So, how's your day going, floor 7?",
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 5,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unfortunate Superhero Names',
    slug: 'unfortunate-superhero-names',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Captain Obvious: "Look, a crime!"',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 6,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Failed Reality TV Shows',
    slug: 'failed-reality-tv-shows',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Extreme Ironing: The Ultimate Wrinkle Challenge',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 7,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unlikely Scented Candles',
    slug: 'unlikely-scented-candles',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Eau de Wet Dog',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 8,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Inappropriate Icebreakers',
    slug: 'inappropriate-icebreakers',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'So, what’s your Wi-Fi password?',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 9,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unrealistic Fortune Cookie Fortunes',
    slug: 'unrealistic-fortune-cookie-fortunes',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'You will find true love during your next dentist appointment.',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 10,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Absurd Self-Help Books',
    slug: 'absurd-self-help-books',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'How to Overthink Everything: A Guide',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 11,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Ridiculous Conspiracy Theories',
    slug: 'ridiculous-conspiracy-theories',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'The moon is made of gluten-free cheese',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 12,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unfortunate Band Names',
    slug: 'unfortunate-band-names',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'The Tone-Deaf Turtles',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 13,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unlikely Yoga Poses',
    slug: 'unlikely-yoga-poses',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'The Confused Flamingo',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 14,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Terrible Tourist Attractions',
    slug: 'terrible-tourist-attractions',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'The Museum of Unfinished Paintings',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 15,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unusual Cooking Shows',
    slug: 'unusual-cooking-shows',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Cooking with Cardboard: A Recycling Adventure',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 16,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Awkward Superpowers',
    slug: 'awkward-superpowers',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'The ability to turn wine back into water',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 17,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unlikely Pet Tricks',
    slug: 'unlikely-pet-tricks',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Teaching your goldfish to fetch',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 18,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Absurd Dating Apps',
    slug: 'absurd-dating-apps',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Tinder for Tacos: Find your perfect crunch',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 19,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unconventional Theme Parks',
    slug: 'unconventional-theme-parks',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Introvert Island: No Rides, Just Books',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 20,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unfortunate Children’s Book Titles',
    slug: 'unfortunate-children-s-book-titles',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Where’s Waldo: Quarantine Edition',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 21,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unlikely Exercise Programs',
    slug: 'unlikely-exercise-programs',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Couch Potato Pilates',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 22,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unusual College Courses',
    slug: 'unusual-college-courses',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'The Philosophy of Memes',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 23,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Absurd Job Interview Questions',
    slug: 'absurd-job-interview-questions',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'If you were a tree, how would you do this job?',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 24,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unlikely Sports',
    slug: 'unlikely-sports',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Competitive Napping',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 25,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unrealistic Video Games',
    slug: 'unrealistic-video-games',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Laundry Simulator 3000',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 26,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unfortunate Perfume Names',
    slug: 'unfortunate-perfume-names',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Eau de Desperation',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 27,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unlikely Celebrity Endorsements',
    slug: 'unlikely-celebrity-endorsements',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Stephen Hawking for Skateboards',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 28,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Absurd Product Ideas for Vampires',
    slug: 'absurd-product-ideas-for-vampires',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'Sunscreen SPF 0',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 29,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unlikely Places for a First Date',
    slug: 'unlikely-places-for-a-first-date',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'The DMV',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 30,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unfortunate Food Truck Concepts',
    slug: 'unfortunate-food-truck-concepts',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'The Broccoli Bar',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
  {
    id: 31,
    createdAt: new Date(),
    updatedAt: null,
    title: 'Unlikely Reality TV Challenges',
    slug: 'unlikely-reality-tv-challenges',
    dreamType: DreamType.BRAINSTORM,
    description: ' ',
    pitch: 'The Great American Tax Filing Race',
    flavorText: null,
    examples: null,
    artPrompt: ' ',
    imagePath: null,
    highlightImage: null,
    icon: '',
    designer: null,
    creationSource: CreationSource.AI,
    userId: 1,
    isPublic: true,
    isMature: false,
    isActive: true,
    artImageId: null,
    artCollectionId: null,
    scenarioId: null,
  },
]
