-- AlterTable
ALTER TABLE `Character` MODIFY `statValue1` INTEGER NULL DEFAULT 59,
    MODIFY `statValue2` INTEGER NULL DEFAULT 49,
    MODIFY `statValue3` INTEGER NULL DEFAULT 72,
    MODIFY `statValue4` INTEGER NULL DEFAULT 93,
    MODIFY `statValue6` INTEGER NULL DEFAULT 71;

-- AlterTable
ALTER TABLE `Scenario` ADD COLUMN `artPrompt` VARCHAR(191) NULL;
