// utils/rulerHooked/characterArt.ts
//
// Portrait/expression asset contract for ruler-hooked's Character cast
// (ruler-hooked/t-028, answering FULL-GAME-GAP-AUDIT.md's character-parity
// finding: "repository evidence does not show ... a portrait/expression
// asset set for the game cast"). This is deliberately just a schema + a
// prompt builder, not rendered art -- the render queue is ~1400+ jobs deep
// (t-028's own scope note), so this defines what art SHOULD exist so a
// future batch has a stable target instead of one-off prompts, while the
// game itself degrades gracefully in the meantime.
//
// Mirrors the ruler cosmetics fallback ladder (rulerPresets.ts /
// ruler-hooked-cosmetics-picker.vue): a missing expression-specific file
// falls back to a single neutral portrait, which itself falls back to an
// initial-letter badge -- never a broken image or a blocked UI.

/** Every Character in the cast gets (at most) these four expression variants.
 *  Four, not the full kind_robots `Expression` enum, on purpose: this is a
 *  reaction-to-the-player's-choices set for a standing advisor/narrator, not
 *  a full animation rig. `neutral`/`pleased`/`concerned`/`alarmed` map onto
 *  the ExpressionMedia rows the seed script writes as
 *  NEUTRAL/PROUD/ANXIOUS/AFRAID respectively (server/utils's Expression
 *  enum) -- see scripts/seed_ruler_hooked_characters.ts. */
export const CHARACTER_EXPRESSION_KEYS = [
  'neutral',
  'pleased',
  'concerned',
  'alarmed',
] as const
export type CharacterExpressionKey = (typeof CHARACTER_EXPRESSION_KEYS)[number]

/** Public asset path for one character's expression-specific portrait. */
export function characterPortraitPath(
  slug: string,
  expression: CharacterExpressionKey,
): string {
  return `/images/ruler-hooked/character-${slug}-${expression}.webp`
}

/** The always-attempted fallback once no expression-specific file exists yet. */
export function characterFallbackPortraitPath(slug: string): string {
  return `/images/ruler-hooked/character-${slug}.webp`
}

const EXPRESSION_DIRECTION: Record<CharacterExpressionKey, string> = {
  neutral:
    'a calm, attentive resting expression, three-quarter portrait, plain court background',
  pleased: 'a warm, approving half-smile, slightly brighter lighting',
  concerned: 'a furrowed, worried expression, leaning slightly forward',
  alarmed: 'wide-eyed alarm, mid-gesture, tighter framing',
}

export interface CharacterPortraitPromptInput {
  name: string
  /** CharacterRef.role, e.g. "castle steward and advisor". */
  role?: string
  /** CharacterRef.quirks, folded in as a light identifying detail. */
  quirks?: string
  expression: CharacterExpressionKey
}

/**
 * ArtJob-shaped prompt text for one character + expression. Kept as one
 * definition the render pipeline and the game's own fallback ladder both
 * read from, per t-028's note: "define portrait/expression requirements so
 * the art has a schema to target." Every CharacterRef in content.ts needs
 * exactly CHARACTER_EXPRESSION_KEYS.length prompts, generated by calling
 * this once per expression.
 */
export function characterPortraitPrompt(
  input: CharacterPortraitPromptInput,
): string {
  const role = input.role ? `, ${input.role}` : ''
  const quirks = input.quirks ? ` Known for: ${input.quirks}.` : ''
  return (
    `Portrait of ${input.name}${role}. ${EXPRESSION_DIRECTION[input.expression]}. ` +
    `Painterly fantasy-court illustration style consistent with the ruler-hooked ` +
    `cast (see utils/rulerHooked/rulerPresets.ts).${quirks}`
  )
}
