-- AlterTable
ALTER TABLE `Reaction` MODIFY `reactionCategory` ENUM('ART', 'ART_IMAGE', 'PITCH', 'COMPONENT', 'CHANNEL', 'CHAT_EXCHANGE', 'BOT', 'GALLERY', 'MESSAGE', 'POST', 'PROMPT', 'RESOURCE', 'REWARD', 'TAG', 'TITLE') NOT NULL DEFAULT 'ART',
    ALTER COLUMN `artImageId` DROP DEFAULT;
