### Get gallery by Name
GET https://kindrobots.org/api/gallery/name/acrocats
Accept: application/json

###

### Get all gallery
GET https://kindrobots.org/api/gallery
Accept: application/json

###

### Get gallery by ID
GET https://kindrobots.org/api/gallery/id/1
Accept: application/json

###


### Get gallery count
GET https://kindrobots.org/api/gallery/count
Accept: application/json

###

### Create a gallery
POST https://kindrobots.org/api/gallery
Content-Type: application/json

{
  "name": "acrocats",
  "content": "/images/acrocats/gallery.json",
  "description": "Acrocat Ranch Foster Kitten Rescue",
  "highlightImage": "/images/acrocats/PXL_20220903_023602144.jpg",
  "isNSFW": false,
  "isAuth": false,
  "user": "cafepurr"
}

###
### Get Random Gallery
GET https://kindrobots.org/api/gallery/random
Content-Type: application/json

###

### Get Random Image
GET https://kindrobots.org/api/gallery/random/image
Content-Type: application/json


###

#### Create multiple gallery
POST https://kindrobots.org/api/gallery/
Content-Type: application/json

[
  {
    "name": "amibot",
    "content": "/images/amibot/gallery.json",
    "description": "AMIb0t, The Anti Malaria Intelligence",
    "highlightImage": "/images/amibot/amibot1.webp"
  },
  {
    "name": "avatars",
    "content": "/images/avatars/gallery.json",
    "description": "Collection of avatar images",
    "highlightImage": "/images/avatars/avatar2.webp"
  },
  {
    "name": "background",
    "content": "/images/background/gallery.json",
    "description": "Assorted background images",
    "highlightImage": "/images/background/background001.webp"
  },
  {
    "name": "botcafe",
    "content": "/images/botcafe/gallery.json",
    "description": "The Bot Cafe Gallery",
    "highlightImage": "/images/botcafe/botcafe1.webp"
  },
  {
    "name": "cafepurr",
    "content": "/images/cafepurr/gallery.json",
    "description": "Cafe Purr - A place for cat lovers",
    "highlightImage": "/images/cafepurr/cafepurr1.webp"
  },
  {
    "name": "ducky",
    "content": "/images/ducky/gallery.json",
    "description": "Ducky's delightful gallery",
    "highlightImage": "/images/ducky/ducky1.webp"
  },
  {
    "name": "fantasycore",
    "content": "/images/fantasycore/gallery.json",
    "description": "FantasyCore: A journey into imagination",
    "highlightImage": "/images/fantasycore/fantasycore1.webp"
  },
  {
    "name": "floof",
    "content": "/images/floof/gallery.json",
    "description": "The Fluffy Floof Gallery",
    "highlightImage": "/images/floof/floof1.webp"
  },
  {
    "name": "flower",
    "content": "/images/flower/gallery.json",
    "description": "Blossoming Flower Gallery",
    "highlightImage": "/images/flower/flower1.webp"
  },
  {
    "name": "redbubble",
    "content": "/images/redbubble/gallery.json",
    "description": "RedBubble - Exploding with color",
    "highlightImage": "/images/redbubble/redbubble1.webp"
  },
  {
    "name": "seuss",
    "content": "/images/seuss/gallery.json",
    "description": "The wonderful world of Dr. Seuss",
    "highlightImage": "/images/seuss/seuss1.webp"
  },
  {
    "name": "wonderbot",
    "content": "/images/wonderbot/gallery.json",
    "description": "WonderBot - The gallery of a wonder",
    "highlightImage": "/images/wonderbot/wonderbot1.webp"
  },
  {
    "name": "wondercat",
    "content": "/images/wondercat/gallery.json",
    "description": "WonderCat: The Purr-fect Gallery",
    "highlightImage": "/images/wondercat/wondercat1.webp"
  },
  {
    "name": "wonderchest",
    "content": "/images/wonderchest/gallery.json",
    "description": "The WonderChest - A trove of treasures",
    "highlightImage": "/images/wonderchest/wonderchest1.webp"
  },
  {
    "name": "wondershed",
    "content": "/images/wondershed/gallery.json",
    "description": "The WonderShed - A shed full of wonders",
    "highlightImage": "/images/wondershed/wondershed1.webp"
  }
]

###
### Update galleries
PATCH https://kindrobots.org/api/gallery/batch
Content-Type: application/json

[
{ "name": "acrocats",
"imagePaths": "acrocats-19.webp,acrocats-20.webp,acrocats-21.webp,acrocats-22.webp,acrocats-23.webp,acrocats-24.webp,acrocats-25.webp,acrocats-26.webp,acrocats-27.webp,acrocats-28.webp,acrocats-29.webp,acrocats-30.webp,acrocats-31.webp,acrocats-32.webp,acrocats-33.webp,acrocats-34.webp,acrocats-35.webp,acrocats-36.webp,acrocats-37.webp,acrocats-38.webp,acrocats-39.webp,acrocats-40.webp,acrocats-41.webp,acrocats-42.webp,acrocats-43.webp,acrocats-44.webp,acrocats-45.webp,acrocats-46.webp,acrocats-47.webp,acrocats-48.webp,acrocats-49.webp,acrocats-50.webp,acrocats-51.webp,acrocats-52.webp,acrocats-53.webp,acrocats-54.webp,acrocats-55.webp,acrocats-56.webp,acrocats-57.webp"
}]