-- AlterTable
ALTER TABLE `Pitch` MODIFY `PitchType` ENUM('ARTPITCH', 'BRAINSTORM', 'WEIRDLANDIA', 'RANDOMLIST', 'TITLE', 'VIBE', 'BOT', 'INSPIRATION', 'DREAM', 'CHARACTER', 'REWARD', 'SCENARIO', 'TEXT', 'LOCATION') NOT NULL DEFAULT 'ARTPITCH';
