### Get gallery by Name
GET https://kindrobots.org/api/gallery/name/acrocats
Accept: application/json

###

### Get all gallery
GET https://kindrobots.org/api/gallery
Accept: application/json

###

### Get gallery by ID
GET https://kindrobots.org/api/gallery/id/1
Accept: application/json

###


### Get gallery count
GET https://kindrobots.org/api/gallery/count
Accept: application/json

###

### Create a gallery
POST https://kindrobots.org/api/gallery
Content-Type: application/json

[{
  "name": "weirdlandia",
  "content": "/images/weirdlandia/gallery.json",
  "description": "The Weirdest of Locations",
  "highlightImage": "/images/weirdlandia/weird1.png",
  "isNSFW": false,
  "imagePaths": "weird1.png"
}]

###
### Get Random Gallery
GET https://kindrobots.org/api/gallery/random
Content-Type: application/json

###
### Get Random number of images
GET https://kindrobots.org/api/gallery/random/count/16
Content-Type: application/json

###
### Get Random Image
GET https://kindrobots.org/api/gallery/random/image
Content-Type: application/json


###

### Get Random Image from Gallery
GET https://kindrobots.org/api/gallery/random/name/weirdlandia
Content-Type: application/json


###

#### Create multiple gallery
POST https://kindrobots.org/api/gallery/
Content-Type: application/json

[
  {
    "name": "amibot",
    "content": "/images/amibot/gallery.json",
    "description": "AMIb0t, The Anti Malaria Intelligence",
    "highlightImage": "/images/amibot/amibot1.webp"
  },
  {
    "name": "avatars",
    "content": "/images/avatars/gallery.json",
    "description": "Collection of avatar images",
    "highlightImage": "/images/avatars/avatar2.webp"
  },
  {
    "name": "background",
    "content": "/images/background/gallery.json",
    "description": "Assorted background images",
    "highlightImage": "/images/background/background001.webp"
  },
  {
    "name": "botcafe",
    "content": "/images/botcafe/gallery.json",
    "description": "The Bot Cafe Gallery",
    "highlightImage": "/images/botcafe/botcafe1.webp"
  },
  {
    "name": "cafepurr",
    "content": "/images/cafepurr/gallery.json",
    "description": "Cafe Purr - A place for cat lovers",
    "highlightImage": "/images/cafepurr/cafepurr1.webp"
  },
  {
    "name": "ducky",
    "content": "/images/ducky/gallery.json",
    "description": "Ducky's delightful gallery",
    "highlightImage": "/images/ducky/ducky1.webp"
  },
  {
    "name": "fantasycore",
    "content": "/images/fantasycore/gallery.json",
    "description": "FantasyCore: A journey into imagination",
    "highlightImage": "/images/fantasycore/fantasycore1.webp"
  },
  {
    "name": "floof",
    "content": "/images/floof/gallery.json",
    "description": "The Fluffy Floof Gallery",
    "highlightImage": "/images/floof/floof1.webp"
  },
  {
    "name": "flower",
    "content": "/images/flower/gallery.json",
    "description": "Blossoming Flower Gallery",
    "highlightImage": "/images/flower/flower1.webp"
  },
  {
    "name": "redbubble",
    "content": "/images/redbubble/gallery.json",
    "description": "RedBubble - Exploding with color",
    "highlightImage": "/images/redbubble/redbubble1.webp"
  },
  {
    "name": "seuss",
    "content": "/images/seuss/gallery.json",
    "description": "The wonderful world of Dr. Seuss",
    "highlightImage": "/images/seuss/seuss1.webp"
  },
  {
    "name": "wonderbot",
    "content": "/images/wonderbot/gallery.json",
    "description": "WonderBot - The gallery of a wonder",
    "highlightImage": "/images/wonderbot/wonderbot1.webp"
  },
  {
    "name": "wondercat",
    "content": "/images/wondercat/gallery.json",
    "description": "WonderCat: The Purr-fect Gallery",
    "highlightImage": "/images/wondercat/wondercat1.webp"
  },
  {
    "name": "wonderchest",
    "content": "/images/wonderchest/gallery.json",
    "description": "The WonderChest - A trove of treasures",
    "highlightImage": "/images/wonderchest/wonderchest1.webp"
  },
  {
    "name": "wondershed",
    "content": "/images/wondershed/gallery.json",
    "description": "The WonderShed - A shed full of wonders",
    "highlightImage": "/images/wondershed/wondershed1.webp"
  }
]

###
### Update galleries
PATCH https://kindrobots.org/api/gallery/batch
Content-Type: application/json

[
{ "name": "weirdlandia",
"imagePaths": "weird-34.png,weird-52.png,weird-55.png,weird-2.png,weird-42.png,weird-69.png,weird-32.png,weird-29.png,weird-43.png,weird-7.png,weird-6.png,weird-38.png,weird-44.png,weird-68.png,weird-47.png,weird-21.png,weird-39.png,weird-66.png,weird-56.png,weird-26.png,weird-50.png,weird1.png,weird-62.png,weird-65.png,weird-53.png,weird-19.png,weird-5.png,weird-54.png,weird-63.png,weird-31.png,weird-60.png,weird-28.png,weird-12.png,weird-4.png,weird-49.png,weird-20.png,weird-30.png,weird-33.png,weird-11.png,weird-16.png,weird-23.png,weird-41.png,weird-36.png,weird-17.png,weird-46.png,weird-70.png,weird-27.png,weird-13.png,weird01.png,weird-51.png,weird-67.png,weird-25.png,weird-64.png,weird-18.png,weird-59.png,weird-61.png,weird-48.png,weird-35.png,weird-9.png,weird-45.png,weird-3.png,weird-22.png,weird-14.png,weird-58.png,weird-24.png,weird-15.png,weird-10.png,weird-57.png,weird-37.png,weird-8.png,weird-40.png"
}]