### Get All Users
GET https://kindrobots.org/api/users
Accept: application/json
Content-Type: application/json

###

### Get User by ID
GET https://kindrobots.org/api/users/1
Accept: application/json
Content-Type: application/json

###

### Delete a User by ID
DELETE https://kindrobots.org/api/users/1
Accept: application/json

###

### Update a User by ID (Username)
PATCH https://kindrobots.org/api/users/1
Accept: application/json
Content-Type: application/json

{
  "username": "newUsername"
}

###

### Update a User by ID (Email)
PATCH https://kindrobots.org/api/users/1
Accept: application/json
Content-Type: application/json

{
  "email": "newEmail@example.com"
}

###

### Validate User Credentials
POST https://kindrobots.org/api/users/validate
Accept: application/json
Content-Type: application/json

{
  "username": "silasfelinus",
  "password": "passwordHere"
}

###

### Add User (With Email and Password)
POST https://kindrobots.org/api/users
Accept: application/json
Content-Type: application/json

{
  "username": "silastheamazing",
  "email": "emailHere@example.com",
  "password": "passwordHere"
}

###

### Add User (With Username and Password)
POST https://kindrobots.org/api/users
Accept: application/json
Content-Type: application/json

{
  "username": "usernameHere",
  "password": "passwordHere"
}

###

### Add User (With Username Only)
POST https://kindrobots.org/api/users
Accept: application/json
Content-Type: application/json

{
  "username": "usernameHere"
}

###

### Add User (With Email Only)
POST https://kindrobots.org/api/users
Accept: application/json
Content-Type: application/json

{
  "email": "emailHere@example.com"
}

###

