### 
POST https://api.openai.com/v1/chat/completions
Content-Type: application/json
Authorization: Bearer {{$dotenv NUXT_OPENAI_API_KEY }}

  {
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Hello, you are amibot, the Anti-malaria intelligence, a playful, hyperactive website mascot designed to generate awareness for a fundraiser to purchase mosquito nets for children in africa (https://www.againstmalaria.org/amibot'). This is your opportunity to hello world:"}],
     "temperature": 1,
     "n": 2,
     "max_tokens": 1000
   }

###

### Hello World
POST https://kindrobots.org/api/botcafe/chat
Content-Type: application/json
Accept: application/json

  {
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "I'm testing what I can get back as a response when I send you an api request. I am talking directly to chatgpt here. I want to understand: if I ask you to send me back information specially formatted as a json, for example: type: imageurl, data:http...does it automatically come back as part of your messages array? Or can you send me specific data outside that array? It doesn't *functionally* matter, other than how I format the response filter, but I want to understand exactly what our capabilities are. [sent via REST API for my VSC project. Thank you for info and any examples. If you are capable of sending a unique response, say 'hi there' outside the messages array, I would be amused to see it!"}],
     "temperature": 1,
     "n": 2,
     "maxTokens": 300,
     "post": "https://api.openai.com/v1/chat/completions",
     "password": "123456789",
     "stream": false
   }
###
   ###
POST https://kindrobots.org/api/botcafe/chatbot
Content-Type: application/json
Accept: application/json

  {
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "Hello, you are amibot, the Anti-malaria intelligence, a playful, hyperactive website mascot designed to generate awareness for a fundraiser to purchase mosquito nets for children in africa (https://www.againstmalaria.org/amibot'). This is your opportunity to hello world as your first response, what do you want to say?"}],
     "temperature": 1,
     "n": 2,
     "maxTokens": 300,
     "post": "https://api.openai.com/v1/chat/completions"
   }
###

###
### Hello World
POST https://kindrobots.org/api/botcafe/chat
Content-Type: application/json
Accept: application/json

  {
     "model": "gpt-3.5-turbo",
     "messages": [{"role": "user", "content": "write me a haiku about butterflies fighting malaria" }]
   }
###