// /server/api/chatgpt/utils/contracts/publicSelects.ts
import type { Prisma } from '~/prisma/generated/prisma/client'

export const publicArtSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  path: true,
  checkpoint: true,
  checkpointResourceId: true,
  sampler: true,
  seed: true,
  steps: true,
  designer: true,
  isPublic: true,
  isMature: true,
  promptId: true,
  userId: true,
  pitchId: true,
  galleryId: true,
  promptString: true,
  cfg: true,
  cfgHalf: true,
  serverId: true,
  serverName: true,
  serverUrl: true,
  artImageId: true,
  imagePath: true,
  genres: true,
  negativePrompt: true,
} satisfies Prisma.ArtSelect

export const publicArtCollectionSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  userId: true,
  label: true,
  isMature: true,
  isPublic: true,
  description: true,
  username: true,
} satisfies Prisma.ArtCollectionSelect

export const publicArtImageSelect = {
  id: true,
  galleryId: true,
  createdAt: true,
  updatedAt: true,
  userId: true,
  artId: true,
  fileName: true,
  fileType: true,
  rarity: true,
  botId: true,
  componentId: true,
  milestoneId: true,
  pitchId: true,
  promptId: true,
  reactionId: true,
  resourceId: true,
  rewardId: true,
  tagId: true,
  chatId: true,
  characterId: true,
  butterflyId: true,
} satisfies Prisma.ArtImageSelect

export const privateArtImageSelect = {
  ...publicArtImageSelect,
  imageData: true,
} satisfies Prisma.ArtImageSelect

export const publicBotSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  BotType: true,
  name: true,
  subtitle: true,
  description: true,
  avatarImage: true,
  botIntro: true,
  userIntro: true,
  prompt: true,
  trainingPath: true,
  theme: true,
  personality: true,
  modules: true,
  sampleResponse: true,
  tagline: true,
  isPublic: true,
  isMature: true,
  underConstruction: true,
  canDelete: true,
  userId: true,
  designer: true,
  serverId: true,
  serverName: true,
  artImageId: true,
} satisfies Prisma.BotSelect

export const publicButterflySelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  name: true,
  message: true,
  wingTopColor: true,
  wingBottomColor: true,
  speed: true,
  wingSpeed: true,
  scale: true,
  rarityNumber: true,
  artImageId: true,
  designer: true,
  userId: true,
  isPublic: true,
  artId: true,
  artCollectionId: true,
  botId: true,
  characterId: true,
  pitchId: true,
  promptId: true,
  rewardId: true,
  scenarioId: true,
  tagId: true,
} satisfies Prisma.ButterflySelect

export const publicCharacterSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  name: true,
  achievements: true,
  alignment: true,
  experience: true,
  level: true,
  class: true,
  species: true,
  backstory: true,
  drive: true,
  inventory: true,
  statName1: true,
  statValue1: true,
  statName2: true,
  statValue2: true,
  statName3: true,
  statValue3: true,
  statName4: true,
  statValue4: true,
  statName5: true,
  statValue5: true,
  statName6: true,
  statValue6: true,
  quirks: true,
  skills: true,
  genre: true,
  artImageId: true,
  isPublic: true,
  isMature: true,
  userId: true,
  artPrompt: true,
  goalStat1Name: true,
  goalStat1Value: true,
  goalStat2Name: true,
  goalStat2Value: true,
  goalStat3Name: true,
  goalStat3Value: true,
  goalStat4Name: true,
  goalStat4Value: true,
  honorific: true,
  imagePath: true,
  designer: true,
  personality: true,
} satisfies Prisma.CharacterSelect

export const publicChatSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  type: true,
  sender: true,
  recipient: true,
  content: true,
  title: true,
  isPublic: true,
  isFavorite: true,
  previousEntryId: true,
  originId: true,
  userId: true,
  botId: true,
  recipientId: true,
  artImageId: true,
  promptId: true,
  botName: true,
  channel: true,
  botResponse: true,
  characterId: true,
  isRead: true,
  isMature: true,
  dreamId: true,
  serverId: true,
  serverName: true,
} satisfies Prisma.ChatSelect

export const publicComponentSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  folderName: true,
  componentName: true,
  isWorking: true,
  underConstruction: true,
  isBroken: true,
  title: true,
  notes: true,
  artImageId: true,
} satisfies Prisma.ComponentSelect

export const publicDreamSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  title: true,
  slug: true,
  description: true,
  currentVibe: true,
  currentPrompt: true,
  userId: true,
  pitchId: true,
  artId: true,
  artImageId: true,
  textServerId: true,
  artServerId: true,
  artCollectionId: true,
  galleryId: true,
  scenarioId: true,
  accessMode: true,
  isPublic: true,
  isMature: true,
  isActive: true,
} satisfies Prisma.DreamSelect

export const privateDreamSelect = {
  ...publicDreamSelect,
  privacyCode: true,
} satisfies Prisma.DreamSelect

export const publicGallerySelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  name: true,
  description: true,
  url: true,
  custodian: true,
  content: true,
  highlightImage: true,
  imagePaths: true,
  isMature: true,
  userId: true,
  isPublic: true,
} satisfies Prisma.GallerySelect

export const publicPitchSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  title: true,
  pitch: true,
  designer: true,
  flavorText: true,
  highlightImage: true,
  PitchType: true,
  creationSource: true,
  isMature: true,
  isPublic: true,
  userId: true,
  imagePrompt: true,
  description: true,
  artImageId: true,
  examples: true,
  icon: true,
} satisfies Prisma.PitchSelect

export const publicPromptSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  prompt: true,
  userId: true,
  galleryId: true,
  isMature: true,
  isPublic: true,
  creationSource: true,
  pitchId: true,
  botId: true,
  artImageId: true,
} satisfies Prisma.PromptSelect

export const publicReactionSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  comment: true,
  userId: true,
  reactionType: true,
  reactionCategory: true,
  rating: true,
  artId: true,
  artImageId: true,
  artCollectionId: true,
  botId: true,
  butterflyId: true,
  characterId: true,
  chatId: true,
  componentId: true,
  dreamId: true,
  galleryId: true,
  pitchId: true,
  promptId: true,
  resourceId: true,
  rewardId: true,
  scenarioId: true,
  tagId: true,
  themeId: true,
} satisfies Prisma.ReactionSelect

export const publicResourceSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  name: true,
  customLabel: true,
  MediaPath: true,
  customUrl: true,
  civitaiUrl: true,
  huggingUrl: true,
  localPath: true,
  description: true,
  isPublic: true,
  isMature: true,
  resourceType: true,
  supportedServer: true,
  userId: true,
  artImageId: true,
  generation: true,
} satisfies Prisma.ResourceSelect

export const publicRewardSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  icon: true,
  text: true,
  power: true,
  collection: true,
  rarity: true,
  label: true,
  userId: true,
  artImageId: true,
  imagePath: true,
  imagePrompt: true,
  isPublic: true,
  isMature: true,
} satisfies Prisma.RewardSelect

export const publicScenarioSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  title: true,
  description: true,
  intros: true,
  userId: true,
  artImageId: true,
  imagePath: true,
  locations: true,
  artPrompt: true,
  genres: true,
  inspirations: true,
  isMature: true,
  isPublic: true,
} satisfies Prisma.ScenarioSelect

export const publicServerSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  title: true,
  label: true,
  description: true,
  serverType: true,
  category: true,
  baseUrl: true,
  endpointPath: true,
  healthPath: true,
  userId: true,
  isMature: true,
  isPublic: true,
  isOfficial: true,
  isDefault: true,
  isActive: true,
  isEditable: true,
  browserBaseUrl: true,
  backendBaseUrl: true,
  workflowPath: true,
  workflowVersion: true,
  defaultWidth: true,
  defaultHeight: true,
  defaultSteps: true,
  defaultCfg: true,
  defaultSampler: true,
  defaultScheduler: true,
  accessMode: true,
  requiresClientSideCheck: true,
  isPrivateNetwork: true,
  allowBrowserRequests: true,
  requiresApiKey: true,
  apiKeyName: true,
  useOidc: true,
  oidcProvider: true,
  supportsTxt2Img: true,
  supportsImg2Img: true,
  supportsChat: true,
  supportsComfyWorkflow: true,
  supportsCheckpointOverride: true,
  supportsSampler: true,
  supportsNegativePrompt: true,
  supportsSeed: true,
  supportsSteps: true,
  supportsVideo: true,
  supportsFlux: true,
  supportsKontext: true,
  supportsInpaint: true,
  supportsOutpaint: true,
  supportsImageEdit: true,
  supportsWorkflowUpload: true,
  supportsBatch: true,
  apiLink: true,
  model: true,
  designer: true,
  version: true,
  notes: true,
  sortOrder: true,
  lastCheckedAt: true,
  lastStatus: true,
  generationEngine: true,
  defaultTransport: true,
} satisfies Prisma.ServerSelect

export const publicSmartIconSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  title: true,
  type: true,
  designer: true,
  userId: true,
  icon: true,
  label: true,
  link: true,
  component: true,
  isMature: true,
  isPublic: true,
  description: true,
  category: true,
  modelType: true,
} satisfies Prisma.SmartIconSelect

export const publicTagSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  label: true,
  title: true,
  flavorText: true,
  pitch: true,
  isPublic: true,
  isMature: true,
  userId: true,
  artImageId: true,
} satisfies Prisma.TagSelect

export const publicThemeSelect = {
  id: true,
  name: true,
  values: true,
  userId: true,
  isPublic: true,
  createdAt: true,
  tagline: true,
  room: true,
  colorScheme: true,
  prefersDark: true,
} satisfies Prisma.ThemeSelect

export const publicModelSelects = {
  Art: publicArtSelect,
  ArtCollection: publicArtCollectionSelect,
  ArtImage: publicArtImageSelect,
  Bot: publicBotSelect,
  Butterfly: publicButterflySelect,
  Character: publicCharacterSelect,
  Chat: publicChatSelect,
  Component: publicComponentSelect,
  Dream: publicDreamSelect,
  Gallery: publicGallerySelect,
  Pitch: publicPitchSelect,
  Prompt: publicPromptSelect,
  Reaction: publicReactionSelect,
  Resource: publicResourceSelect,
  Reward: publicRewardSelect,
  Scenario: publicScenarioSelect,
  Server: publicServerSelect,
  SmartIcon: publicSmartIconSelect,
  Tag: publicTagSelect,
  Theme: publicThemeSelect,
} as const

export const privateModelSelects = {
  Dream: privateDreamSelect,
  ArtImage: privateArtImageSelect,
} as const

export type PublicModelName = keyof typeof publicModelSelects
export type PrivateModelName = keyof typeof privateModelSelects
