-- AlterTable
ALTER TABLE `Gallery` ADD COLUMN `isAuth` BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE `Pitch` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL DEFAULT '',
    `content` VARCHAR(191) NOT NULL DEFAULT '',
    `supplement` VARCHAR(191) NOT NULL DEFAULT '',
    `isNSFW` BOOLEAN NOT NULL DEFAULT false,
    `user` VARCHAR(191) NOT NULL DEFAULT 'cafepurr',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
