// Fixture pile data for the Butterfly Gallery store. Stands in for the real
// art-archive-backed feed (butterfly-gallery/t-004) so UI work never waits on
// archive integration -- shape-compatible with ButterflyPileEntry so swapping
// in a live provider later is a data-source change, not a component rewrite.
import type {
  ButterflyBinConfig,
  ButterflyPileEntry,
} from '@/types/butterflyGallery'
import { defaultArtFor } from '@/utils/defaultArtPool'

export function createButterflyGalleryFixtureEntries(): ButterflyPileEntry[] {
  return [
    {
      id: 9001,
      thumbnailPath: defaultArtFor('butterfly-fixture-1'),
      displayPath: defaultArtFor('butterfly-fixture-1'),
      isMature: false,
      isPublic: true,
      processed: false,
      trashed: false,
      rating: null,
      folder: 'inbox',
      collections: [],
      prompt: 'a lighthouse at dawn, watercolor',
      negativePrompt: 'blurry, low detail',
      resource: { checkpoint: 'sdxl-base-fixture', loras: [] },
      generationMetadata: { sampler: 'DPM++ 2M', steps: 30, seed: 10001 },
      matchState: 'matched',
      pendingGenerationJobIds: [],
    },
    {
      id: 9002,
      thumbnailPath: defaultArtFor('butterfly-fixture-2'),
      displayPath: defaultArtFor('butterfly-fixture-2'),
      isMature: true,
      isPublic: false,
      processed: false,
      trashed: false,
      rating: 3,
      folder: 'inbox',
      collections: ['favorites'],
      prompt: 'portrait study, oil paint',
      negativePrompt: null,
      resource: {
        checkpoint: 'fixture-mature-checkpoint',
        loras: ['fixture-portrait-lora'],
      },
      generationMetadata: { sampler: 'Euler a', steps: 24, seed: 10002 },
      matchState: 'matched',
      pendingGenerationJobIds: [],
    },
    {
      id: 9003,
      thumbnailPath: defaultArtFor('butterfly-fixture-3'),
      displayPath: defaultArtFor('butterfly-fixture-3'),
      isMature: false,
      isPublic: true,
      processed: true,
      trashed: false,
      rating: 5,
      folder: 'sorted',
      collections: ['landscapes'],
      prompt: 'mountain range, ink wash',
      negativePrompt: null,
      resource: { checkpoint: null, loras: [] },
      generationMetadata: null,
      matchState: 'unmatched',
      pendingGenerationJobIds: [],
    },
    {
      id: 9004,
      thumbnailPath: defaultArtFor('butterfly-fixture-4'),
      displayPath: defaultArtFor('butterfly-fixture-4'),
      isMature: false,
      isPublic: true,
      processed: false,
      trashed: false,
      rating: null,
      folder: 'inbox',
      collections: [],
      prompt: null,
      negativePrompt: null,
      resource: { checkpoint: 'fixture-checkpoint-b', loras: [] },
      generationMetadata: null,
      matchState: 'missing',
      pendingGenerationJobIds: [],
    },
    {
      id: 9005,
      thumbnailPath: defaultArtFor('butterfly-fixture-5'),
      displayPath: defaultArtFor('butterfly-fixture-5'),
      isMature: false,
      isPublic: true,
      processed: false,
      trashed: true,
      rating: 1,
      folder: 'sorted',
      collections: [],
      prompt: 'city skyline at night',
      negativePrompt: 'blurry',
      resource: {
        checkpoint: 'fixture-checkpoint-b',
        loras: ['fixture-night-lora'],
      },
      generationMetadata: { sampler: 'DPM++ 2M', steps: 28, seed: 10005 },
      matchState: 'matched',
      pendingGenerationJobIds: [],
    },
  ]
}

export function createDefaultButterflyBins(): ButterflyBinConfig[] {
  return [
    {
      id: 'preset-five',
      label: '5★ + Featured Collection',
      side: 'left',
      icon: 'kind-icon:star',
      kind: 'preset',
      payload: {
        rating: 5,
        collection: 'featured',
        processed: true,
      },
      sortOrder: 0,
      enabled: true,
    },
    {
      id: 'preset-four',
      label: '4★ + Favorite Tag',
      side: 'left',
      icon: 'kind-icon:heart',
      kind: 'preset',
      payload: {
        rating: 4,
        collection: 'favorites',
        processed: true,
      },
      sortOrder: 1,
      enabled: true,
    },
    {
      id: 'preset-three',
      label: '3★ Keep As Is',
      side: 'left',
      icon: 'kind-icon:check',
      kind: 'preset',
      payload: {
        rating: 3,
        processed: true,
      },
      sortOrder: 2,
      enabled: true,
    },
    {
      id: 'preset-two',
      label: '2★ + Move to Study',
      side: 'left',
      icon: 'kind-icon:folder',
      kind: 'preset',
      payload: {
        rating: 2,
        folder: 'study',
        processed: true,
      },
      sortOrder: 3,
      enabled: true,
    },
    {
      id: 'preset-one',
      label: '1★ + Low Star Archive',
      side: 'left',
      icon: 'kind-icon:archive',
      kind: 'preset',
      payload: {
        rating: 1,
        collection: 'archive',
        processed: true,
      },
      sortOrder: 4,
      enabled: true,
    },
    {
      id: 'trash',
      label: 'Trash',
      side: 'right',
      icon: 'kind-icon:trash',
      kind: 'trash',
      payload: {},
      sortOrder: 0,
      enabled: true,
    },
  ]
}
