// /utils/seeds/facetLegacyCreativeLists.ts
//
// Deterministic migration snapshots used only to fill gaps in the canonical
// Facet catalog. Runtime selection must use Facets rather than these arrays.

export const legacyFacetBackstoryList = [
  // Classic Fantasy
  'Orphaned at a young age and raised by wolves.',
  'Trained in the arcane arts in a distant land.',
  'A former thief seeking redemption.',
  'The lone survivor of a village destroyed by war.',
  'Once the ruler of a kingdom now turned to ruin.',
  'A wanderer with no memory of their past.',
  'Cursed to speak only in riddles… but only on Tuesdays.',
  'Exiled from their homeland for crimes they didn’t commit—or did they?',

  // Sci-Fi / Space
  'Grew up aboard a rogue satellite with a sentient vending machine.',
  'Once a starship mechanic, now fleeing interstellar bounty hunters.',
  'Clone #47 — the one who finally asked "why?"',
  'Built as an AI companion, now self-aware and freelancing.',
  'Woke up in cryo with someone else’s memories and a strange tattoo.',
  'The only survivor of a glitch in the simulation.',

  // Whimsical / Absurd
  'Was once a duck. No one knows why, including them.',
  'Escaped a haunted library by promising to return one book.',
  'Won a cursed lottery — prize pending.',
  'Taught swordsmanship by a ghost who only quoted Shakespeare.',
  'Can only sleep standing up, and only on moving trains.',
  'Was legally adopted by a forest.',

  // Noir / Urban Legend
  'Used to be a private eye — until the shadows got weird.',
  'Knows too much about the moon. They won’t say how.',
  'Was erased from official records… yet still pays taxes.',
  'Claims to have seen the back end of reality, and left a review.',
  'Once decoded a message hidden in the rain.',
] as const

export const legacyFacetMaterialList = [
  'Mythril',
  'Adamantium',
  'Dragon Scale',
  'Obsidian',
  'Moonstone',
  'Starsteel',
  'Quantum Fiber',
  'Void Crystal',
  'Aether Silk',
  'Plasma Alloy',
  'Pyroclastic Rock',
  'Glacial Shard',
  'Thunderstone',
  'Solar Glass',
  'Nano-carbon',
  'Ethereal Mist',
  'Phoenix Feather',
  'Prismatic Ore',
  'Chrono Dust',
  'Nebula Thread',
  'Shadow Weave',
  'Demonic Bone',
  'Angelite',
  'Enchanted Bark',
  'Living Wood',
  'Astral Ore',
  'Cursed Iron',
  'Bio-metal',
  'Warped Stone',
  'Venom Glass',
  'Storm Weave',
  'Eclipse Stone',
  'Glowstone',
  'Liquid Gold',
  'Fire Opal',
  'Hollow Steel',
  'Titanite',
  'Vortex Gem',
  'Shimmer Cloth',
  'Lunar Resin',
  'Cryo Iron',
  'Starlight Powder',
  'Bone Glass',
  'Radiant Amber',
  'Magic-infused Clay',
  'Galactic Granite',
  'Warped Velvet',
  'Spire Crystal',
  'Ghost Iron',
  'Dark Matter Thread',
  'Platinum Filigree',
  'Frostbite Alloy',
  'Ancient Marble',
  'Bloodstone',
  'Spectral Quartz',
  'Cloudstone',
  'Voidsteel',
  'Runestone',
  'Blaze Ore',
  'Charged Crystal',
  'Eldritch Thread',
  'Soul Sand',
  'Temporal Resin',
  'Ironwood',
  'Ashglass',
  'Specter Silk',
  'Starfire Iron',
  'Molten Core',
  'Crimson Coral',
  'Echo Crystal',
  'Timeglass',
  'Fulgurite',
  'Tidal Pearl',
  'Whisperwood',
  'Shadow Oak',
  'Pulse Metal',
  'Infernal Brimstone',
  'Cosmic Ice',
  'Radiant Silk',
  'Phantom Glass',
  'Heavensteel',
  'Dragonbone Porcelain',
  'Cursed Velvet',
  'Amberlight',
  'Dreamcloth',
  'Prismarine Shard',
  'Arcane Silver',
  'Tanglewood',
  'Mirror Alloy',
  'Stormglass',
  'Nether Ore',
  'Chimeric Thread',
  'Hexstone',
  'Starfruit Fiber',
  'Shadewood',
  'Oblivion Alloy',
  'Cryolite',
  'Moonlit Granite',
  'Solar Flame',
] as const

export const legacyFacetColorList = [
  // Standard Colors
  'Red',
  'Blue',
  'Green',
  'Yellow',
  'Purple',
  'Orange',
  'Pink',
  'Brown',
  'Black',
  'White',
  'Gray',

  // Nature-Inspired Colors
  'Forest Green',
  'Sky Blue',
  'Sunset Orange',
  'Ocean Teal',
  'Mountain Gray',
  'Lava Red',
  'Sandstone',
  'Rose Petal',
  'Moss',
  'Coral',
  'Ice Blue',

  // Fantasy and Whimsical Colors
  'Dragon Scale',
  'Moonlit Silver',
  'Faerie Glow',
  'Witch’s Violet',
  'Phoenix Flame',
  'Unicorn Pastel',
  'Goblin Green',
  'Starlight White',
  'Twilight Purple',
  'Ethereal Gold',

  // Exotic and Artistic Colors
  'Midnight Blue',
  'Crimson',
  'Amber',
  'Sepia',
  'Turquoise',
  'Charcoal',
  'Ivory',
  'Chartreuse',
  'Indigo',
  'Cerulean',
  'Peach Blossom',

  // Gemstone-Inspired Colors
  'Ruby',
  'Emerald',
  'Sapphire',
  'Amethyst',
  'Topaz',
  'Opal White',
  'Onyx Black',
  'Jade Green',
  'Amber Glow',
  'Moonstone',

  // Fun and Imaginative Colors
  'Bubblegum Pink',
  'Electric Lime',
  'Neon Orange',
  'Cotton Candy',
  'Mystic Magenta',
  'Chocolate Truffle',
  'Cloud Blue',
  'Stormy Gray',
  'Cinnamon',
  'Vanilla Cream',

  // Subtle and Sophisticated Colors
  'Pewter',
  'Ash',
  'Lavender Mist',
  'Dove Gray',
  'Champagne Gold',
  'Blush Pink',
  'Muted Teal',
  'Sage',
  'Copper',
  'Pale Rose',

  // Futuristic and Metallic Colors
  'Neon Blue',
  'Cyber Purple',
  'Holographic Chrome',
  'Steel Gray',
  'Plasma Pink',
  'Galactic Gold',
  'Laser Green',
  'Photon Silver',
  'Cobalt',
  'Titanium White',

  // Cultural and Regional Colors
  'Ming Blue',
  'Persian Red',
  'Indian Yellow',
  'Japanese Indigo',
  'Moroccan Blue',
  'African Violet',
  'Mexican Pink',
  'Caribbean Aqua',
  'Scandinavian White',
  'Celtic Green',

  // Seasonal Colors
  'Autumn Maple',
  'Frostbite White',
  'Spring Blossom',
  'Summer Sky',
  'Harvest Gold',
  'Winter Mint',
  'Snowflake Silver',
  'Pumpkin Spice',
  'Holly Green',
  'Berry Red',

  // Abstract and Unusual Colors
  'Shadow',
  'Void Black',
  'Illuminating Yellow',
  'Cosmic Lavender',
  'Stormcloud',
  'Dreamscape',
  'Glimmer',
  'Dusky Rose',
  'Morning Dew',
  'Rust',

  // Food-Inspired Colors
  'Honey',
  'Caramel',
  'Espresso',
  'Blueberry',
  'Mint Green',
  'Lemon Drop',
  'Plum',
  'Grapefruit',
  'Pomegranate',
  'Chocolate Brown',
] as const

export const legacyFacetPersonalityList = [
  'Charismatic',
  'Stoic',
  'Energetic',
  'Reserved',
  'Ambitious',
  'Curious',
  'Optimistic',
  'Pessimistic',
  'Cynical',
  'Idealistic',
  'Empathetic',
  'Cold',
  'Charming',
  'Calculating',
  'Impulsive',
  'Patient',
  'Impatient',
  'Adventurous',
  'Cautious',
  'Confident',
  'Shy',
  'Generous',
  'Selfish',
  'Loyal',
  'Deceptive',
  'Eccentric',
  'Pragmatic',
  'Dreamy',
  'Sarcastic',
  'Polite',
  'Rude',
  'Hardworking',
  'Lazy',
  'Analytical',
  'Emotional',
  'Introverted',
  'Extroverted',
  'Altruistic',
  'Greedy',
  'Humble',
  'Arrogant',
  'Playful',
  'Serious',
  'Nervous',
  'Calm',
  'Aggressive',
  'Gentle',
  'Romantic',
  'Logical',
  'Creative',
  'Practical',
  'Fearless',
  'Timid',
  'Friendly',
  'Hostile',
  'Optimistic',
  'Realistic',
  'Visionary',
  'Paranoid',
  'Innocent',
  'Mischievous',
  'Wise',
  'Foolish',
  'Passionate',
  'Detached',
  'Whimsical',
  'Melancholy',
  'Euphoric',
  'Suspicious',
  'Loyal',
  'Rebellious',
  'Obedient',
  'Ambiguous',
  'Tactful',
  'Blunt',
  'Sensitive',
  'Insensitive',
  'Inquisitive',
  'Forgetful',
  'Meticulous',
  'Carefree',
  'Stoic',
  'Theatrical',
  'Hotheaded',
  'Coolheaded',
  'Obsessive',
  'Indifferent',
  'Resourceful',
  'Clumsy',
  'Gullible',
  'Skeptical',
  'Enthusiastic',
  'Grumpy',
  'Cheerful',
  'Moody',
  'Predictable',
  'Unpredictable',
  'Optimistic',
  'Gloomy',
  'Quirky',
  'Intense',
  'Relaxed',
  'Bold',
  'Cautious',
  'Detached',
  'Caring',
  'Bubbly',
  'Demanding',
  'Considerate',
  'Stubborn',
  'Flexible',
  'Compassionate',
  'Ambivalent',
  'Playful',
  'Jovial',
  'Scheming',
  'Gregarious',
  'Brooding',
  'Daring',
  'Industrious',
  'Resilient',
  'Unyielding',
] as const

export const legacyFacetQuirkList = [
  'Always speaks in riddles.',
  'Has an uncanny sense of direction but only in forests.',
  'Collects buttons from every town they visit.',
  'Can’t resist counting things aloud.',
  'Refuses to eat food unless it’s arranged in a specific order.',
  'Laughs uncontrollably at the mention of pickles.',
  'Only communicates through song when nervous.',
  'Writes poetry on any available surface.',
  'Believes their shadow is plotting against them.',
  'Carries a bag of marbles, claiming they’re magical.',
  'Gets distracted by shiny objects mid-conversation.',
  'Knows an unusual amount about clouds and weather patterns.',
  'Can mimic the sound of any animal perfectly.',
  'Refuses to walk on tiled floors with odd patterns.',
  'Always wears mismatched socks intentionally.',
  'Has an imaginary friend named "Bartholomew" who gives advice.',
  'Constantly names inanimate objects.',
  'Terrified of butterflies but loves moths.',
  'Draws symbols in the dirt whenever they stop walking.',
  'Only drinks tea that’s been stirred counterclockwise.',
  'Whistles haunting melodies when they’re deep in thought.',
  'Can’t resist making puns in dire situations.',
  'Owns a collection of unusual hats, one for every day of the week.',
  'Believes that sneezing wards off evil spirits.',
  'Has a pet rock they insist is sentient.',
  'Can identify anyone’s favorite fruit just by looking at them.',
  'Doodles elaborate maps of imaginary lands.',
  'Talks to plants as if they’re old friends.',
  'Carries a pocket full of acorns for "emergencies."',
  'Believes they’re being followed by an invisible duck.',
  'Can’t sleep unless they hum a lullaby to themselves.',
  'Refuses to use umbrellas, claiming they’re bad luck.',
  'Wears a scarf year-round, even in summer.',
  'Is a professional finger snapper, complete with routines.',
  'Refuses to touch books with even page numbers.',
  'Obsessed with finding "the perfect stick."',
  'Always leaves a breadcrumb trail wherever they go.',
  'Carries a notebook full of cryptic, self-written proverbs.',
  'Takes "invisible notes" with a pretend quill.',
  'Invents strange handshakes for every new person they meet.',
  'Taps their foot exactly 12 times before sitting down.',
  'Believes that certain colors bring them good luck.',
  'Keeps an assortment of dried herbs in their pockets.',
  'Has a superstition about only stepping on cracks.',
  'Keeps a list of "enemies" that includes animals and objects.',
  'Hums the same three notes whenever they’re planning something.',
  'Can’t stop spinning coins when deep in thought.',
  'Collects feathers and treats them as treasure.',
  'Only walks in the shadows, avoiding direct sunlight.',
  'Has a knack for predicting when someone will hiccup.',
  'Knows an absurd amount of trivia about cheese.',
  'Carries a compass but never uses it.',
  'Invents elaborate backstories for people they meet.',
  'Laughs at their own jokes before finishing them.',
  'Only wears boots, even in formal settings.',
  'Has a strong aversion to mirrors.',
  'Compulsively organizes objects by size.',
  'Can’t help but correct incorrect grammar in ancient texts.',
  'Uses overly dramatic hand gestures for mundane tasks.',
  'Refuses to sit on chairs with cushions.',
  'Has trained themselves to remember everything in rhyme.',
  'Owns a collection of jars filled with "mysterious substances."',
  'Can identify bird calls but refuses to explain how.',
  'Writes letters to fictional characters.',
  'Claims they can speak to fish but not other animals.',
  'Uses completely nonsensical phrases as insults.',
  'Believes sneezing too many times in a row causes bad luck.',
  'Carries a candle everywhere "just in case."',
  'Talks to their weapon as if it has feelings.',
  'Has a superstition about wearing mismatched gloves.',
  'Insists on starting every conversation with "Once upon a time..."',
  'Keeps a collection of "lucky pebbles" from different regions.',
  'Carries a spoon at all times, "just in case of pudding."',
  'Constantly checks behind them as if someone’s there.',
  'Gives names to every stray cat they encounter.',
  'Refuses to cross bridges without whistling a tune.',
  'Invents riddles for strangers and expects answers.',
  'Sprinkles salt around their bed before sleeping.',
  'Keeps a tiny mirror they believe shows "true intentions."',
  'Dances a little jig whenever they see a rainbow.',
  'Believes they can charm birds by chirping back at them.',
  'Knows every type of moss by sight and smell.',
  'Collects oddly shaped sticks and claims they’re magical.',
  'Carries an empty journal for "recording important events."',
  'Sniffs books to judge their "character."',
  'Keeps an invisible "force field" around themselves.',
  'Constantly sketches "the same recurring dream."',
  'Carries a secret recipe for soup at all times.',
  'Only eats foods in alphabetical order.',
  'Can juggle but only uses fruits.',
  'Talks to doors before opening them.',
  'Knows an absurd amount of facts about frogs.',
  'Always starts conversations by quoting obscure poetry.',
  'Leaves cryptic notes in bottles wherever they go.',
  'Refuses to touch objects made of copper.',
  'Believes staring contests determine trustworthiness.',
  'Wears mismatched earrings to "confuse the spirits."',
  'Whispers to the moon before going to sleep.',
] as const
