// GENERATED by scripts/sync_cthulhuquarium_canon.mjs from the cthulhuquarium
// canon repo. Do not edit by hand -- edit the canon and re-run the sync.

export const CTHULHUQUARIUM_BACKGROUND_UNLOCKS: Record<string, string> = {
  parlour: 'default',
  'kelp-stair': 'bestiary_5',
  'sunken-pantry': 'bestiary_10',
  'drowned-chapel': 'bestiary_15',
  'wreck-of-the-portsmouth': 'bestiary_20',
  'sorting-office': 'bestiary_25',
  'counting-house': 'bestiary_35',
  'flooded-conservatory': 'bestiary_50',
  catacomb: 'bestiary_70',
  'abyssal-plain': 'bestiary_95',
  'opera-house': 'bestiary_125',
  'the-reading-room': 'bestiary_151',
  'public-baths': 'first_full_tank',
  hatchery: 'first_evolution',
  scullery: 'first_spotless_tank',
  'duelling-ground': 'first_rivalry_resolved',
}

export const CTHULHUQUARIUM_SCENE_IDS: string[] = [
  'intro',
  'first_unlock',
  'first_hatch',
  'first_breed',
  'bestiary_complete',
  'milestone_bestiary_5',
  'milestone_bestiary_10',
  'milestone_bestiary_15',
  'milestone_bestiary_20',
  'milestone_bestiary_25',
  'milestone_bestiary_35',
  'milestone_bestiary_50',
  'milestone_bestiary_70',
  'milestone_bestiary_95',
  'milestone_bestiary_125',
  'milestone_bestiary_151',
  'milestone_first_full_tank',
  'milestone_first_evolution',
  'milestone_first_spotless_tank',
  'milestone_first_rivalry_resolved',
]
