-- AlterTable
ALTER TABLE `Bot` MODIFY `BotType` ENUM('CHATBOT', 'RAPBOT', 'CODEBOT', 'PROMPTMAKER', 'ARTMAKER', 'ARTREMIXER', 'ARTDESIGNER', 'STORYTELLER', 'QUESTMASTER', 'PROJECTMANAGER') NOT NULL DEFAULT 'CHATBOT';

-- AlterTable
ALTER TABLE `BotInput` MODIFY `BotType` ENUM('CHATBOT', 'RAPBOT', 'CODEBOT', 'PROMPTMAKER', 'ARTMAKER', 'ARTREMIXER', 'ARTDESIGNER', 'STORYTELLER', 'QUESTMASTER', 'PROJECTMANAGER') NOT NULL;
