import type { Prisma } from '~/prisma/generated/prisma/client'

export const chatMutationSelect = {
  id: true,
  createdAt: true,
  updatedAt: true,
  type: true,
  sender: true,
  recipient: true,
  content: true,
  title: true,
  isPublic: true,
  isFavorite: true,
  previousEntryId: true,
  originId: true,
  userId: true,
  botId: true,
  recipientId: true,
  artImageId: true,
  promptId: true,
  botName: true,
  channel: true,
  botResponse: true,
  characterId: true,
  isRead: true,
  isMature: true,
  serverId: true,
  serverName: true,
  dreamId: true,
  isActive: true,
  readAt: true,
  projectId: true,
} satisfies Prisma.ChatSelect
